### ISSUE TITLE
"invalid session token: failed to verify signature: failed to verify id token signature" with argocd v2.5.2 and dex >= v2.35.x

### ISSUE THREAD

**Issue by mconigliaro** [argoproj/argo-cd#11392]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I found https://github.com/argoproj/argo-cd/pull/11219, which supposedly fixes https://github.com/argoproj/argo-cd/issues/11071 by using `ghcr.io/dexidp/dex:v2.35.3` instead of `ghcr.io/dexidp/dex:v2.35.3-distroless`. When I try using any of these `v2.35.x` images, I get the following error when attempting to log in via SSO:

```
invalid session token: failed to verify signature: failed to verify id token signature
```

Possible regression of https://github.com/argoproj/argo-cd/issues/1113?

**To Reproduce**

Using helm chart version `5.14.1`, set `dex.image.tag` to `v2.35.x` (e.g. `v2.35.3`).

**Expected behavior**

SSO should work.

**Screenshots**

**Version**

```shell
argocd: v2.5.2+148d8da
  BuildDate: 2022-11-07T16:42:47Z
  GitCommit: 148d8da7a996f6c9f4d102fdd8e688c2ff3fd8c7
  GitTreeState: clean
  GoVersion: go1.18.8
  Compiler: gc
  Platform: linux/amd64
```

**Comment by hyt05** [comment]
I encountered the same problem, I integrated with keycloak, click logout on the UI interface, and re-use keycloak to log in to the browser, the following error will appear
```
failed to get token: oauth2: cannot fetch token: 401 Unauthorized
Response: {"error":"unauthorized_client","error_description":"Invalid client secret"}
```
I need to fail 3 times before I can log in successfully

**Comment by davidtaddei** [comment]
I have also encountered this using the Dex GitHub Connector. The Dex server logs appear to have logged in successfully and I can see my GH user information however the argocd server then cannot validate the token.

**Comment by VazeeKevin** [comment]
same issue with Github connector after upgrading ArgoCD from `v2.4` to `v2.5.10`.
argocd-dex-server log:
```
time="2023-02-06T10:41:48Z" level=info msg="login successful: connector \"github\", [...]
```
argocd-server log:
```
time="2023-02-06T10:42:07Z" level=info msg="Initializing OIDC provider (issuer: https://[argocdDomain]/api/dex)"
time="2023-02-06T10:42:07Z" level=warning msg="Failed to verify token: failed to verify token: Failed to query provider \"https://[argocdDomain]/api/dex\": 404 Not Found: Not Found\n"
```
client log:
```
{"error":"invalid session: failed to verify the token","code":16,"message":"invalid session: failed to verify the token"}
```

**Comment by michaelfedell** [comment]
Anyone able to identify if this is a bug in the current version of the connector, or is it simply a configuration error?

I am seeing the same issue (Dex logs report successful login, ArgoCD server reports "failed to verify") with the a similar config (GitHub Dex Connector, config snippet below)

<details>
<summary>Dex Connector Config</summary>

```yaml
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: <redacted>
          clientSecret: <redacted>
          orgs:
            - name: <my-org>
```

</details>

**Comment by BernardoABC** [comment]
@michaelfedell I was experiencing the same issue, fixed by deleting the argocd-server pod. After a new pod was ready I was able to log in.

**Comment by VazeeKevin** [comment]
@BernardoABC thanks a lot for your feedback, it's now working properly after deleting `argocd-server` pods

**Comment by D3vl0per** [comment]
Oh my God! That's worked! Thanks @BernardoABC !

**Comment by michaelfedell** [comment]
hah - I kind of hate it when problems just solve themselves, but either way, it's resolved! thanks for sharing your experience

**Comment by purduemike** [comment]
Not sure where this should happen. But, the pod(s) that need restarting should auto restart by some trigger. I'm using a helm chart to deploy ArgoCD.

**Comment by Vinaum8** [comment]
argocd app list
FATA[0000] rpc error: code = Unauthenticated desc = invalid session: signature is invalid

**Comment by Vinaum8** [comment]
argocd account list
FATA[0000] rpc error: code = Unauthenticated desc = invalid session: signature is invalid

**Comment by Vinaum8** [comment]
argocd login $ARGOCD_HOST_PRODUCTION --username admin --server $ARGOCD_HOST_PRODUCTION --grpc-web --config $ARGOCD_CONFIG_HOME/$ARGOCD_HOST_PRODUCTION
Password: 
'admin:login' logged in successfully
Context 'argocd-manager.appnext.fit' updated

Same error, but login is successfully.
Argocd version 2.7.7

**Comment by sspreitzer** [comment]
I have this error every time rolling out a fresh Kubernetes cluster and ArgoCD installation. After one restart of the ArgoCD server pods everything works fine.

I would hate to implement a workaround in my Terraform manifests just to fix this.

I am not using dex. Any idea to what could cause this problem?

CA on the IdP is letsencrypt.

```
time="2023-07-31T08:41:37Z" level=info msg="Initializing OIDC provider (issuer: https://id.xxxx.xxx/auth/realms/master)"
time="2023-07-31T08:41:37Z" level=warning msg="Failed to verify token: failed to verify token: Failed to query provider \"https://id.xxxx.xxx/auth/realms/master\": Get \"https://id.xxxx.xxx/auth/realms/master/.well-known/openid-configuration\": x509: certificate signed by unknown authority"
time="2023-07-31T08:41:37Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = invalid session: failed to verify the token" grpc.code=Unauthenticated grpc.method=List grpc.service=cluster.ClusterService grpc.start_time="2023-07-31T08:41:37Z" grpc.time_ms=15.149 span.kind=server system=grpc
time="2023-07-31T08:41:37Z" level=info msg="Initializing OIDC provider (issuer: https://id.xxxx.xxx/auth/realms/master)"
time="2023-07-31T08:41:38Z" level=warning msg="Failed to verify token: failed to verify token: Failed to query provider \"https://id.xxxx.xxx/auth/realms/master\": Get \"https://id.xxxx.xxx/auth/realms/master/.well-known/openid-configuration\": x509: certificate signed by unknown authority"
time="2023-07-31T08:41:38Z" level=info msg="received unary call /session.SessionService/GetUserInfo" grpc.method=GetUserInfo grpc.request.content= grpc.service=session.SessionService grpc.start_time="2023-07-31T08:41:37Z" span.kind=server system=grpc
time="2023-07-31T08:41:38Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GetUserInfo grpc.service=session.SessionService grpc.start_time="2023-07-31T08:41:37Z" grpc.time_ms=15.4 span.kind=server system=grpc
```

**Comment by wadexu007** [comment]
> Anyone able to identify if this is a bug in the current version of the connector, or is it simply a configuration error?
> 
> I am seeing the same issue (Dex logs report successful login, ArgoCD server reports "failed to verify") with the a similar config (GitHub Dex Connector, config snippet below)
> 
> Dex Connector Config
> ```yaml
>   dex.config: |
>     connectors:
>       - type: github
>         id: github
>         name: GitHub
>         config:
>           clientID: <redacted>
>           clientSecret: <redacted>
>           orgs:
>             - name: <my-org>
> ```

Hi @michaelfedell, do you know what's the org name if using personal Github account?

**Comment by suryaval** [comment]
Issue occured when trying to add target cluster using argocd-cli

```
{"level":"fatal","msg":"rpc error: code = Unauthenticated desc = invalid session: failed to verify the token","time":"2023-12-18T16:18:59-06:00"}
```

Resolved by resetting the argocd context i.e. re-login to argocd cluster via SSO. This issue happens when the ArgoCD server is restarted and argocd context gets invalidated.

**Comment by abdennour** [comment]
same issue when call 
```
curl --location 'https://argocd.company.lan/api/v1/applications/myapp?refresh=true' \
--header 'Content-Type: application/json' \
--header 'Authorization: ••••••' 
```
though, `POST /api/v1/applications/myapp/sync` works fine with the same Bearer token.

**Comment by okanozeren** [comment]
Hi,
I also face with the similar issue on our K8s setup. I can't log-in with the Google OIDC configuration. It worked once I configured it first but then I started to get the below error. Looks like login then it kicks me out.
Neither any pod deletion nor deployment restart didn't help. I reinstalled everything, still doesn't work.
Glad to hear any recommendation.

Helm chart version: `argo-cd-7.8.7`
ArgoCD server image: `quay.io/argoproj/argocd:v2.14.3`
Dex image: `ghcr.io/dexidp/dex:v2.41.1`

```
time="2025-03-03T10:11:57Z" level=warning msg="Failed to verify token: failed to verify token: token verification failed for all audiences: error for aud \"***.apps.googleusercontent.com\": failed to verify signature: failed to verify id token signature"
time="2025-03-03T10:11:57Z" level=info msg="received unary call /version.VersionService/Version" grpc.method=Version grpc.request.content= grpc.service=version.VersionService grpc.start_time="2025-03-03T10:11:57Z" span.kind=server system=grpc
time="2025-03-03T10:11:57Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=Version grpc.service=version.VersionService grpc.start_time="2025-03-03T10:11:57Z" grpc.time_ms=8.733 span.kind=server system=grpc
time="2025-03-03T10:11:57Z" level=info msg="Initializing OIDC provider (issuer: https://accounts.google.com)"
time="2025-03-03T10:11:57Z" level=info msg="OIDC supported scopes: [openid email groups profile offline_access]"
```

**Comment by okanozeren** [comment]
Hi, is there any recommendation about to sort this problem out permenantly or as a workaround?

**Comment by gojanpaolo** [comment]
I was getting a similar issue when trying to put argocd behind istio by following [this docs](https://argo-cd.readthedocs.io/en/latest/operator-manual/ingress/#istio). 

changing the path to just `/` instead of `/argocd` resolves the issue.

<details>

<summary>yaml files</summary>

```
# Use --insecure so Ingress can send traffic with HTTP
# --bashref /argocd is the subpath like https://IP/argocd
# env was added because of https://github.com/argoproj/argo-cd/issues/3572 error
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: argocd-server
spec:
 template:
   spec:
     containers:
     - args:
       - /usr/local/bin/argocd-server
       - --staticassets
       - /shared/app
       - --redis
       - argocd-redis:6379
       - --insecure
       # serve in `/` instead of `/argocd`
       #- --basehref
       #- /argocd
       #- --rootpath
       #- /argocd
       name: argocd-server
       env:
       - name: ARGOCD_MAX_CONCURRENT_LOGIN_REQUESTS_COUNT
         value: "0"
```
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: argocd-virtualservice
  namespace: argocd
spec:
  exportTo:
  - .
  - istio-system
  hosts:
  - "*"
  gateways:
  - istio-system/default-gateway
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: argocd-server
        port:
          number: 80
```

</details>

Looking into why that works and potentially finding out how to have it serve `/argocd` (or other path) properly.

**Comment by gojanpaolo** [comment]
I am now able to serve `/argocd` path as well.
The issue is that I had an invalid `argocd.token` stored in my chrome browser.
F12 > Application > Cookies > argocd.token
Deleting that cookie resolve the issues and `/argocd` just worked following the docs I linked above

<details>

<summary>/argocd yaml files</summary>

```
apiVersion: apps/v1
kind: Deployment
metadata:
 name: argocd-server
spec:
 template:
   spec:
     containers:
     - args:
       - /usr/local/bin/argocd-server
       - --staticassets
       - /shared/app
       - --redis
       - argocd-redis:6379
       - --insecure
       - --basehref
       - /argocd
       - --rootpath
       - /argocd
       name: argocd-server
       env:
       - name: ARGOCD_MAX_CONCURRENT_LOGIN_REQUESTS_COUNT
         value: "0"
```

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: argocd-virtualservice
  namespace: argocd
spec:
  exportTo:
  - .
  - istio-system
  hosts:
  - "*"
  gateways:
  - istio-system/default-gateway
  http:
  - match:
    - uri:
        prefix: "/argocd"
    route:
    - destination:
        host: argocd-server
        port:
          number: 80
```

*** I used a different gateway then the docs

</details>
