### ISSUE TITLE
2.6 RC1: multi source application needs a hard refresh to deploy changes

### ISSUE THREAD

**Issue by marcportabellaclotet-mt** [argoproj/argo-cd#11772]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When creating a multi source application, argocd needs a hard refresh to deploy changes, when changes are applied in the sources.

**To Reproduce**
Create an application with helm source and values from git repo.

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
  labels:
    type: deployment
    application: argo-rollouts
spec:
  project: default
  sources:
    - repoURL: 'https://argoproj.github.io/argo-helm'
      targetRevision: 2.21.1
      chart: argo-rollouts
      helm:
        valueFiles:
        - $values/argocd/applications/values/argo-rollouts/values-common.yaml
    - repoURL: https://github.com/xxx/yyy.git
      targetRevision: HEAD
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argo-rollouts
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
```
Once the app is deployed, upgrading the values in the git repo, does not trigger any change in argocd. 
In order to make argocd aware of this change, a hard-refresh is needed.

**Expected behavior**

Argocd controller should note that the repo is out of sync, without the need of a hard-refresh.

**Comment by lukas-unity** [comment]
It also returns this log line https://github.com/argoproj/argo-cd/issues/11770 (now fixed)

**Comment by crenshaw-dev** [comment]
Just confirmed that order doesn't matter. Even if the values-file source is first, the application controller doesn't catch the new commit.

**Comment by endersonmaia** [comment]
@marcportabellaclotet-mt what "hard-refresh" means ? you had to run argo CLI or use the web UI

I ask this 'cause in my case, I don't use the CLI nor the web UI, so how to hard-refresh ?

**Comment by endersonmaia** [comment]
In my case, my Application stays in `SyncStatus: OutOfSync`  and `HealthStatus: MIssing` and I'm defining the `syncPolicy` as:

```yaml
...
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
```

Before, when I was using a `configManagementPlugins` workaround from [this commen](https://github.com/argoproj/argo-cd/issues/2789#issuecomment-604400914), I could make the Application sync and so on after adding the `syncPolicy` section.

**Comment by crenshaw-dev** [comment]
@endersonmaia can you provide your full Application spec?

I think @marcportabellaclotet-mt is probably triggering a hard refresh in the UI or CLI. So if you're running Argo CD headless, I think you're just stuck if the application controller doesn't see the new commit.

**Comment by endersonmaia** [comment]
> So if you're running Argo CD headless, I think you're just stuck if the application controller doesn't see the new commit.

It doesn't work even with the "original" commit, since I'm not even sending a new commit to the values repository. (should I open a new issue?)

**Comment by crenshaw-dev** [comment]
Yep! Sounds like a Different Thing. 🙂

**Comment by endersonmaia** [comment]
> @endersonmaia can you provide your full Application spec?

This was generated from an `ApplicationSet` with git generator.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  destination:
    namespace: my-app
    server: https://kubernetes.default.svc
  project: default
  sources:
  - chart: my-chart
    helm:
      releaseName: my-app
      valueFiles:
      - $values/myorg-aws-dev.values.yaml
      - $values/network.values.yaml
      - $values/my-dapp/network.yaml
      values: |
        ingress:
          subDomain: network.dev.myorg.io
    repoURL: https://myorg.github.io/helm-charts
    targetRevision: 0.4.1
  - path: ./echo-python/
    ref: values
    repoURL: https://github.com/myorg-private-repo/deployments
    targetRevision: poc/argocd-applicationset
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
```

**Comment by crenshaw-dev** [comment]
@endersonmaia any chance you can put together an app to reproduce the bug which uses publicly-available sources?

**Comment by marcportabellaclotet-mt** [comment]
I am using hard-refresh from UI. It also can be done via cli.
@endersonmaia : 
Your issue may be related to [argocd plugin support](https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/2.4-2.5/#argocd-cm-plugins-cmps-are-deprecated)
```
argocd-cm plugins (CMPs) are deprecated[¶](https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/2.4-2.5/#argocd-cm-plugins-cmps-are-deprecated)

Starting with Argo CD v2.5, installing config management plugins (CMPs) via the argocd-cm ConfigMap is deprecated. Support will be removed in v2.6.
```

**Comment by messiahUA** [comment]
I'm facing the same problem with a simple app:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: default
  sources:
  - chart: ingress-nginx
    helm:
      valueFiles:
      - $values/values/ingress-nginx/values.yaml
      - $values/values/ingress-nginx/values-main.yaml
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.4.0
  - ref: values
    repoURL: https://github.com/messiahUA/argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
```

**Comment by naimo84** [comment]
I can second that 😉 
Hard refresh works 👍 

I can reproduce it with publicly-available sources like from @messiahUA, bt also with my companies apps ;)

Cheers

**Comment by logamanig** [comment]
I'm also facing this issue

**Comment by crenshaw-dev** [comment]
Thanks for the confirmations! We'll get this sorted before 2.6 GA.

**Comment by yebolenko** [comment]
any progress on this issue?
when 2.6 official release will be available?

**Comment by crenshaw-dev** [comment]
No progress yet.

2.6 GA is currently [anticipated Feb. 6](https://github.com/orgs/argoproj/projects/25).

**Comment by yebolenko** [comment]
Michael, thank you for this update.
Do I understand correctly, that this fix will be included as a part of 2.6?

**Comment by crenshaw-dev** [comment]
@yebolenko yep! I consider this a blocking bug for the multi-source feature.

**Comment by crenshaw-dev** [comment]
Draft PR is up for the fix. Unfortunately, I think webhooks won't be fixed by 2.6 GA. Updates from referenced repos won't go out of sync until the next reconciliation cycle.

**Comment by charandas** [comment]
Thanks @crenshaw-dev. Do you mean to say that webhooks are broken for multi source applications or across the board in 2.6 GA? I can live with it if it's just multi source ones.

**Comment by crenshaw-dev** [comment]
Not broken across the board, just for multi-source apps. And _I believe_ the webhook will only be missed if it's for a _referenced_ source. Top-level sources should be fine.

**Comment by zenitraM** [comment]
@crenshaw-dev I believe I've hit the same issue @endersonmaia did, which does not seem to be fixed by #12217 (or at least it was not fixed by the commit I built earlier today from it). I've opened https://github.com/argoproj/argo-cd/issues/12301 about it with a reproducer.

**Comment by lsoica** [comment]
@crenshaw-dev  I'm on v2.6.1+3f143c9 but this issue is still reproducible. Updating the values.yaml in GIT does not trigger a resync.

**Comment by crenshaw-dev** [comment]
@lsoica is this a case of a missed webhook, or does the 3min reconciliation also miss the change?

**Comment by lsoica** [comment]
@crenshaw-dev I think my comment was before this merge https://github.com/argoproj/argo-cd/pull/12576

With that merge included, it does not reproduce anymore on my current use cases.

**Comment by nickyfoster** [comment]
I'm experiencing this issue on `v2.7.2+cbee7e6.dirty`.

Here is the Application manifest:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multi-source-test
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: multi-source-test
  sources:
    - repoURL: ******.dkr.ecr.us-west-1.amazonaws.com
      chart: my-chart
      targetRevision: 1.0.0
      helm:
        valueFiles:
          - $values/configs/values.yaml
    - repoURL: git@github.com:private/gitops-configs.git
      targetRevision: main
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false

```

**Comment by lerminou** [comment]
I'm facing the same issue right now with argocd v2.10.2
