### ISSUE TITLE
Health probe on applicationset controller not working

### ISSUE THREAD

**Issue by tossmilestone** [argoproj/argo-cd#15304]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The health probe on applicationset controller is not working, it returns 404 when visit `{applicationset-controller pod ip}:8081/healthz`.

**To Reproduce**

Visit `{applicationset-controller pod ip}:8081/healthz`

**Expected behavior**

The health probe address should return ok.

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
v2.6.14
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by shuker85** [comment]
I do not see a health probe section in [kustomize install manifests](https://github.com/argoproj/argo-cd/blob/master/manifests/base/applicationset-controller/argocd-applicationset-controller-deployment.yaml#L9C1-L28C28) or in the output from helm chart which i've deployed:

```
Labels:           app.kubernetes.io/component=applicationset-controller
                  app.kubernetes.io/instance=argo-cd
                  app.kubernetes.io/managed-by=Helm
                  app.kubernetes.io/name=argocd-applicationset-controller
                  app.kubernetes.io/part-of=argocd
                  app.kubernetes.io/version=v2.8.2
                  helm.sh/chart=argo-cd-5.43.8
Status:           Running
IP:               172.16.0.44
IPs:
  IP:           172.16.0.44
Controlled By:  ReplicaSet/argocd-applicationset-controller-7cd55fb47
Containers:
  applicationset-controller:
    Image:        argo-cd:v2.8.2
    Ports:         8080/TCP, 8081/TCP, 7000/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP
    Args:
      /usr/local/bin/argocd-applicationset-controller
      --metrics-addr=:8080
      --probe-addr=:8081
      --webhook-addr=:7000
```

In case of the kustomize install port 8081 is not exposed. If it's still valid i think the probe should go in the kustomize manifests.

**Comment by tossmilestone** [comment]
@shuker85, the manifests don't have the health probe, I add it manually.

**Comment by madianas21** [comment]
Even after adding the `8081` port, `/healthz` endpoint is still not working. It is not working on any of the ports either.
Adding `--webhook-addr=:7000` arg did help to enable webhooks to work though, so thank you for that!

**Comment by jgwest** [comment]
Closing as applicationset controller does not currently expose/support the health endpoint via manifests.

**Comment by WoahitsJoe** [comment]
Workaround for GKE Gateway API

The root cause is that GKE health checks require HTTP 200 responses, but the ApplicationSet webhook endpoint returns HTTP 400 for health check requests.

Solution: Use the ApplicationSet metrics endpoint for health checks instead.

Enable the ApplicationSet metrics service in your Helm values (applicationSet.metrics.enabled: true)
Create a HealthCheckPolicy that targets the argocd-applicationset-controller service (not the metrics service) and configures health checks to use port 8080 path /metrics (which returns HTTP 200)
The metrics service and webhook service both select the same pods. GKE health checks go directly to pod IPs via NEGs, so even though the webhook service doesn't expose port 8080, the healthcheck can still reach it on the pods. Once the health checks pass, webhook traffic flows normally.

This allows webhooks to work with GKE Gateway API without requiring code changes to the ApplicationSet controller.
