### ISSUE TITLE
Post-Delete Hook support mutate Application object

### ISSUE THREAD

**Issue by llavaud** [argoproj/argo-cd#17433]
**Describe the bug**

The recent [Post-Delete hook support PR](https://github.com/argoproj/argo-cd/pull/16595), mutate the Application object when refreshing by [adding two finalizers](https://github.com/argoproj/argo-cd/blob/fcf5d8c2381b68ab1621b90be63913b12cca2eb7/controller/appcontroller.go#L1630-L1643) if a resource have a `"helm.sh/hook": post-delete` annotation.
In an apps of apps context it causes unnecesssary reconciliations due to object updated:

`{"api-version":"argoproj.io/v1alpha1","application":"myRootApp","cluster-name":"myCluster","fields.level":0,"kind":"Application","level":"debug","msg":"Requesting app refresh caused by object update","name":"myApp","namespace":"argo-cd","server":"myServer","time":"2024-03-07T08:14:40Z"}`

**To Reproduce**

Create an Application that deploy another Application, in the nested Application deploy a resource that have a `"helm.sh/hook": post-delete` annotation. Wait for the 3m default refresh interval and search for the `Requesting app refresh caused by object update` debug log line.

**Expected behavior**

Do not mutate the Application object or at least maybe automaticaly ignore thoses finalizers like it is currently done for the metadata fields `generation` and `resourceVersion`

**Version**

```shell
argocd: v2.10.2+fcf5d8c
  BuildDate: 2024-03-01T21:24:51Z
  GitCommit: fcf5d8c2381b68ab1621b90be63913b12cca2eb7
  GitTreeState: clean
  GoVersion: go1.21.3
  Compiler: gc
  Platform: linux/amd64
```

**Comment by llavaud** [comment]
A possible workaround (not tested yet):

```yaml
resource.customizations.ignoreDifferences.argoproj.io_Application: |
  jqPathExpressions:
    - .metadata.finalizers | map(select(. == "post-delete-finalizer.argocd.argoproj.io" or . == "post-delete-finalizer.argocd.argoproj.io/cleanup"))
    - if (.metadata.finalizers | length) == 0 then .metadata.finalizers else empty end
```

**Comment by llavaud** [comment]
@alexmt Hello, can I have your opinion on this please ? do you consider it as a bug or normal behavior ?

**Comment by msvechla** [comment]
we are experiencing the same issue. The workaround above works, but it looks like this should be handled on argocd side

**Comment by didlawowo** [comment]
> A possible workaround:
> 
> ```yaml
> resource.customizations.ignoreDifferences.argoproj.io_Application: |
>   jqPathExpressions:
>     - .metadata.finalizers[]? | select(. == "post-delete-finalizer.argocd.argoproj.io" or . == "post-delete-finalizer.argocd.argoproj.io/cleanup")
>     - if (.metadata.finalizers | length) == 0 then .metadata.finalizers else empty end
> ```

how can i make that in config map ?

**Comment by llavaud** [comment]
> > A possible workaround:
> > ```yaml
> > resource.customizations.ignoreDifferences.argoproj.io_Application: |
> >   jqPathExpressions:
> >     - .metadata.finalizers[]? | select(. == "post-delete-finalizer.argocd.argoproj.io" or . == "post-delete-finalizer.argocd.argoproj.io/cleanup")
> >     - if (.metadata.finalizers | length) == 0 then .metadata.finalizers else empty end
> > ```
> 
> how can i make that in config map ?

not sure to understand your question, the example is what you must add to the `argocd-cm` ConfigMap

**Comment by nbarrientos** [comment]
In case this was useful somehow, here it is a good example of a "real world" chart triggering this: 

https://github.com/kubernetes-sigs/node-feature-discovery/blob/6030c974d38ed9a1e4592f0f133d64e27d3c50a7/deployment/helm/node-feature-discovery/templates/post-delete-job.yaml#L8-L10

which is used in NVIDIA's gpu operator:

https://github.com/NVIDIA/gpu-operator/blob/main/deployments/gpu-operator/Chart.yaml#L21

**Comment by andrii-korotkov-verkada** [comment]
@nbarrientos, which ArgoCD version are you using when reproducing?

**Comment by cmontemuino** [comment]
We're also experiencing the same as @nbarrientos, NVIDIA GPU Operator including NFD.

Argo CD v2.12.3+6b9cd82

**Comment by Farfaday** [comment]
Experiencing the same with the current latest kyverno helm chart :)
Using argo-cd v2.12.3+6b9cd82

**Comment by diranged** [comment]
> Experiencing the same with the current latest kyverno helm chart :) Using argo-cd v2.12.3+6b9cd82

Agreed - we just ran into this with the latest Kyverno chart as well due to https://github.com/kyverno/kyverno/pull/11504.

**Comment by andrii-korotkov-verkada** [comment]
Why are extra refreshes an issue? They are normal to happen a lot, e.g. when some pods are updated and watches identify there's an update. If they are slow, try 2.13.1, there's been some major perf improvements for when it comes to reconciliation.

**Comment by diranged** [comment]
@andrii-korotkov-verkada No the issue we have is that our app-of-apps applications show up with a `diff`:

![image](https://github.com/user-attachments/assets/a5fe505b-f9ce-45fe-a81b-b1f2aca40a1e)

**Comment by andrii-korotkov-verkada** [comment]
Which diffing strategy are you using? Is it default or server side diff?

**Comment by andrii-korotkov-verkada** [comment]
Server side diff can be enabled on the controller level as well as application level and has some logic to remove webhook mutations when diffing. If you use server side diff and don't explicitly add webhook mutations and see this, let me know, as it could be a bug in that logic.

**Comment by diranged** [comment]
For now - the ignoredifferences fix works for us.. Going into the holidays, I'm hesitant to change the apply method (we have thousands of applications across dozens of argocd installations... it would be risky!). Either way, just reporting here that this is definitely a bug that should be fixed (regardless of the apply-policy).

**Comment by cmontemuino** [comment]
btw, I think this comment is relevant, especially for Kyverno users: https://github.com/kyverno/kyverno/issues/9451#issuecomment-2134984772

**Comment by ChanduReddy123** [comment]
We are using kyverno (helm chart version: 3.3.4) and our argocd is v2.13.2

we are still getting the same error even after adding the annotation 
![image](https://github.com/user-attachments/assets/2dbc5064-27ae-45d0-b54a-ebdf409ad01a)
![image](https://github.com/user-attachments/assets/77472f0a-6119-485c-aa0a-d568c680f230)

this is when we are doing apps of apps

**Comment by pandvan** [comment]
We're facing the same issue with `teleport-kube-agent` Helm chart
ArgoCD version is v2.12.6+4dab5bd
No server-side diff enabled on controller nor app-of-apps Applcation

**Comment by eric-engberg** [comment]
Also still in 2.14.1

**Comment by nbarrientos** [comment]
@gdsoumya, @llavaud  [asked for comments](https://github.com/argoproj/argo-cd/issues/17433#issuecomment-1984413432) about the described behavior from the feature developer but there hasn't been any reply, unfortunately. Could you please give your opinion on this issue as change reviewer?

**Comment by nicanor-asana** [comment]
Actually, it still happens.... but it seems to sync much faster than before, so the App does not stay outofsync for more than an instant... not sure this will be fine for everyone.

**Comment by Thakurvaibhav** [comment]
> A possible workaround:
> 
> resource.customizations.ignoreDifferences.argoproj.io_Application: |
>   jqPathExpressions:
>     - .metadata.finalizers[]? | select(. == "post-delete-finalizer.argocd.argoproj.io" or . == "post-delete-finalizer.argocd.argoproj.io/cleanup")
>     - if (.metadata.finalizers | length) == 0 then .metadata.finalizers else empty end

I tried using this. It fixed the app out-of-sync issue, but blocks the deletion of the application.

**Comment by llavaud** [comment]
> > A possible workaround:
> > resource.customizations.ignoreDifferences.argoproj.io_Application: |
> > jqPathExpressions:
> > - .metadata.finalizers[]? | select(. == "post-delete-finalizer.argocd.argoproj.io" or . == "post-delete-finalizer.argocd.argoproj.io/cleanup")
> > - if (.metadata.finalizers | length) == 0 then .metadata.finalizers else empty end
> 
> I tried using this. It fixed the app out-of-sync issue, but blocks the deletion of the application.

that is weird, this rule just ignore these fields for reconciliation but don't prevent the controller to add or remove the finalizers

**Comment by Thakurvaibhav** [comment]
> > > A possible workaround:
> > > resource.customizations.ignoreDifferences.argoproj.io_Application: |
> > > jqPathExpressions:
> > > - .metadata.finalizers[]? | select(. == "post-delete-finalizer.argocd.argoproj.io" or . == "post-delete-finalizer.argocd.argoproj.io/cleanup")
> > > - if (.metadata.finalizers | length) == 0 then .metadata.finalizers else empty end
> > 
> > I tried using this. It fixed the app out-of-sync issue, but blocks the deletion of the application.
> 
> that is weird, this rule just ignore these fields for reconciliation but don't prevent the controller to add or remove the finalizers

@llavaud I was wrong. 
The patch works correctly but the deletion of Kyverno Argo app is stuck with the following error:

"Forbidden: no new finalizers can be added if the object is being deleted"

This happens when I delete the parent argo app.

**Comment by Thakurvaibhav** [comment]
For anyone following the thread:

I started running into this issue after upgrading to Kyverno 1.13. It was due to a post-delete hook which got introduced in the chart. The post-delete helm hook was also causing problems with the argo app cleanup. 
I got around it by setting `config.preserve: false` in the Kyverno chart. This setting disables the post-delete hook. It is anyways, not relevant for a ArgoCD based install.

**Comment by reggie-k** [comment]
I'd like to make a quick summary so that we can work towards closing this issue.
- Argo CD supports post-delete hooks (Helm hooks and regular resource hooks as an annotation)
- The current implementation adds 2 finalizers on the Application CR in the case when a post-delete hook was identified (`post-delete-finalizer.argocd.argoproj.io` and `post-delete-finalizer.argocd.argoproj.io/cleanup`)
- For Apps managed with Git, setting those finalizers results in a contradiction with Git's source of truth
- A known workaround is setting a `resource.customizations.ignoreDifferences.argoproj.io_Application` globally or per App
- Since the drift is introduced by an internal Argo CD behavior, and not by user behavior, it seems beneficial to make Argo CD ignore this diff OOTB, without requiring additional user actions 

**Action items:**
- Make sure the problem still exists (deploy a Helm chart with a post-delete hook or deploy an App with a manifest annotated as PostDelete and see whether a diff is produced)
- If so, one proposed solution is to enable a default ignore differences configuration for those 2 finalizers

**Comment by jkleinlercher** [comment]
The problem still exists with the current kyverno helm-chart

ArgoCD version: 3.0.5
Kyverno Helm-Chart version: 3.4.4
Link to our Umbrella-Chart: https://github.com/suxess-it/kubriX/tree/main/platform-apps/charts/kyverno
App Definition:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: >-
      sx-wkr--cl001-spoke-applications:argoproj.io/Application:argocd/sx-wkr--cl001-kyverno
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: sx-wkr--cl001-kyverno
  namespace: argocd
spec:
  destination:
    namespace: kyverno
    server: https://api.xxxx.yyyy
  project: default
  source:
    helm:
      ignoreMissingValueFiles: true
      releaseName: sx-kyverno
    path: platform-apps/charts/kyverno
    repoURL: https://github.com/suxess-it/kubriX.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      annotations:
        argocd.argoproj.io/tracking-id: sx-wkr--cl001-kyverno:app/Namespace:kyverno/kyverno
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
```

<img width="1168" height="106" alt="Image" src="https://github.com/user-attachments/assets/932976eb-1a19-4785-882f-fcd65630968a" />

**Comment by Thakurvaibhav** [comment]
> The problem still exists with the current kyverno helm-chart
> 
> ArgoCD version: 3.0.5 Kyverno Helm-Chart version: 3.4.4 Link to our Umbrella-Chart: https://github.com/suxess-it/kubriX/tree/main/platform-apps/charts/kyverno App Definition:
> 
> ```
> apiVersion: argoproj.io/v1alpha1
> kind: Application
> metadata:
>   annotations:
>     argocd.argoproj.io/tracking-id: >-
>       sx-wkr--cl001-spoke-applications:argoproj.io/Application:argocd/sx-wkr--cl001-kyverno
>   finalizers:
>     - resources-finalizer.argocd.argoproj.io
>   name: sx-wkr--cl001-kyverno
>   namespace: argocd
> spec:
>   destination:
>     namespace: kyverno
>     server: https://api.xxxx.yyyy
>   project: default
>   source:
>     helm:
>       ignoreMissingValueFiles: true
>       releaseName: sx-kyverno
>     path: platform-apps/charts/kyverno
>     repoURL: https://github.com/suxess-it/kubriX.git
>     targetRevision: main
>   syncPolicy:
>     automated:
>       prune: true
>       selfHeal: true
>     managedNamespaceMetadata:
>       annotations:
>         argocd.argoproj.io/tracking-id: sx-wkr--cl001-kyverno:app/Namespace:kyverno/kyverno
>     syncOptions:
>       - CreateNamespace=true
>       - ServerSideApply=true
> ```
> 
> <img alt="Image" width="1168" height="106" src="https://private-user-images.githubusercontent.com/11465610/472351047-932976eb-1a19-4785-882f-fcd65630968a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTM4OTc5OTYsIm5iZiI6MTc1Mzg5NzY5NiwicGF0aCI6Ii8xMTQ2NTYxMC80NzIzNTEwNDctOTMyOTc2ZWItMWExOS00Nzg1LTg4MmYtZmNkNjU2MzA5NjhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzMwVDE3NDgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3ZTZmM2IxZTFjZDM1MjBiNzNiYzEyYzVhNTljNGEzNzJmMzY4YjkxMjcyNDg3ZmRjNjliY2NlMWQ3NjQ5NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MulIlSTdFqoGzF_yLXTUQSuLx0IN6dl62e2la33eCjM">

Could you try setting `config.preserve=false` in Kyverno and see if that helps?
Reference: https://kyverno.io/docs/installation/platform-notes/#configuration-best-practices

**Comment by ppapapetrou76** [comment]
I'll work on the issue

**Comment by agaudreault** [comment]
The finalizers managed internally by argo will be owned by "argocd-application-controller" instead of  "argocd-controller" (when using server-side-apply) or "kubectl-client-side-apply" (for legacy client side apply).

So if you enable Server-side diff and add the following configs on your parent application, you will not have the diffs anymore.
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
spec:
  syncPolicy:
    syncOptions:
      - RespectIgnoreDifferences=true # Very important, or the finalizers would be removed on every Sync.
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      managedFieldsManagers:
        - argocd-application-controller
```

Another option is to just use server-side diff and server-side apply
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
spec:
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
```

Setting a default ignoreDifferences for the finalizers would not work since RespectIgnoreDifferences needs to be set and setting it by default is too impactful. 

I think the better defaults are to use server-side-diff and server-side apply. 

However, I think this problem should be fixed, by **always** removing all changes from argocd-application-controller manager in both the diff, and the sync process.

**Comment by nbarrientos** [comment]
FWIW, ArgoCD v3.3.x introduced support for pre deletion hooks (see https://github.com/argoproj/argo-cd/pull/22288) so, similarly to post-delete hooks, pre-delete finalizers might pop up in Applications' diffs:

<img width="768" height="242" alt="Image" src="https://github.com/user-attachments/assets/e40c6368-58ef-43d7-b280-829cd7a21dd8" />

Ignoring those as well might help, depending on your setup:

```yaml
configs:
  cm:
    [...]
    resource.customizations.ignoreDifferences.argoproj.io_Application: |
      jqPathExpressions:
        - .metadata.finalizers[]? | select(. == "post-delete-finalizer.argocd.argoproj.io" or . == "post-delete-finalizer.argocd.argoproj.io/cleanup" or . == "pre-delete-finalizer.argocd.argoproj.io" or . == "pre-delete-finalizer.argocd.argoproj.io/cleanup")
```
