### ISSUE TITLE
Upgrade from v2.11 to 2.12 Breaks Git Secret

### ISSUE THREAD

**Issue by IdoOzeri** [argoproj/argo-cd#19881]
I've upgraded my Argocd installation via the official chart. 
From chart version `7.3.11` (app version `v2.11.7`) to `7.4.0` (app version `v2.12.0`). 

I have a `Secret` resource in my cluster with the following label:
```
argocd.argoproj.io/secret-type: repository
```

Once I upgraded to `v2.12.0`, this repository connection still appears as "Successful" in the user interface, but my applications can no longer sync, complaining of the following error:

```
SSH agent requested but SSH_AUTH_SOCK not-specified
```

I've done some digging and found [this issue](https://github.com/argoproj/argo-cd/issues/8084), which suggested modifying the `secret-type` label to `repo-creds`. Once I did that, the problem was gone. 

My question is, is this label deprecated in > `v2.12.0`?
I haven't seen any deprecation notice in the docs.

**Comment by rickardk-se** [comment]
Are you using the same secret across projects?

**Comment by rhaex** [comment]
I experienced the same issue when upgrading from v2.11.2 to v.2.11.8 using the manifest https://raw.githubusercontent.com/argoproj/argo-cd/v2.12.3/manifests/install.yaml.

Everything upgrades fine, but after the upgrade the SSH connection to the repo is broken and gives the errors as seen above and in the linked issue.

And yes, we use the same repo & secret for several projects.

**Comment by IdoOzeri** [comment]
> Are you using the same secret across projects?

Yes, I only have 1 project and 1 secret. Nothing changed but the Argo version.

**Comment by rickardk-se** [comment]
Sharing secrets across projects stopped working in 2.12.

**Comment by rhaex** [comment]
> Sharing secrets across projects stopped working in 2.12.

Yeah I know, but our secret is not bound to any project. So all projects use the same repo secret, but the secret itself is not bound to a project (so without project field as described here https://argo-cd.readthedocs.io/en/latest/operator-manual/upgrading/2.11-2.12/).

The upgrade breaks the repo connection, until you change `secret-type: repository` into `secret-type: repo-creds`, after everything works fine again.

**Comment by blakepettersson** [comment]
> Sharing secrets across projects stopped working in 2.12.

That is not the case.

> And that breaking change is not mentioned anywhere (was it even intentional?).

`secret-type: repository` definitely works. What did change in 2.12 was that if a secret had a `project` value set, it can only be used by applications within that same project.

**Comment by CubicFeat** [comment]
We also ran into this issue.

Changing the label to repo-creds did solve the issue, but I noticed afterward that the k8s secret does contain a project field, and it was set to `default`, which is exactly what the upgrade notes say will be an issue.  We may have created it this way years ago, I'm not sure, but from what I can see there is no way to see or set that via the UI.

I've since changed the label back to just `repository` and completely removed the project field from the k8s secret, and things still work.

@blakepettersson any chance there is a feature coming where a person can see what projects a repository is scoped to?  There are no "view" or "edit" options under Settings->repositories, just a list.

**Comment by blakepettersson** [comment]
@CubicFeat do you mean in the UI? Since 2.12 there is a `PROJECT` column to see which project a repository can be scoped to. If it is empty it's globally scoped (it can be used by any project).

<img width="1057" alt="Screenshot 2024-09-16 at 19 42 26" src="https://github.com/user-attachments/assets/6ab06c18-5711-4997-9aba-028273a82f7a">

**Comment by Dutchy-** [comment]
Which upgrade notes mention the `default` project? Because it is not on https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/2.11-2.12/ and I think it should be.

**Comment by blakepettersson** [comment]
Hmm I guess the upgrade notes have not been propagated to readthedocs: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/upgrading/2.11-2.12.md

**Comment by andrii-korotkov-verkada** [comment]
Can you share the secret yaml with masked data, please? Also, the code that references the secret.

**Comment by wyardley** [comment]
We are seeing these sync errors on one of our apps, since updating to 2.13.x via the latest helm chart. We don't have a `project` field set. The projects in question are syncing fine; and the specific app shows up as "synced" and "healthy" -- we just see (consistent) errors in the web UI.

I did note that there are `url` and `type` fields set (the `url` is set to a vendor's repo, so maybe something from the original setup), though don't think that is an issue? I did try adding the label  (`argocd.argoproj.io/secret-type: repo-creds`) which was **not** previously set, and restarting `argocd-server` and `argocd-repo-server` deployments, and it didn't resolve the issue. I'm not sure what the value in `type` is.

Here's the value of the `github-repo-secret` secret, if it helps.

```yaml
apiVersion: v1
data:
  sshPrivateKey: XXXXX
  type: XXXX
  url: XXXXXXXXXX
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: argocd
    meta.helm.sh/release-namespace: argocd
  creationTimestamp: "2024-02-21T16:43:59Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    argocd.argoproj.io/secret-type: repo-creds
  name: github-repo-secret
  namespace: argocd
  resourceVersion: "393638178"
  uid: daca6d32-636f-42f9-bf96-5ef5b2a388be
type: Opaque
```

```
Spec:
  Destination:
    Name:       in-cluster
    Namespace:  xxxx
  Project:      xxxx
  Source:
    Path:             xxxx
    Repo URL:         git@github.com:privaterepo/reponame.git
    Target Revision:  HEAD
```
Note: the repo, reponame, and path within the repo all exist and are correct.

**Comment by jgournet** [comment]
I may need help there:
- our secret is NOT scoped to any project (there is no project value at all) - see below
- things are working fine up to 2.14
- upgrading to 3.0, we're now getting the same issue as explained in this ticket.

I tried adding the label "argocd.argoproj.io/secret-type: repo-creds" which we did not have before, but no luck.

=> Question is: is there still a way to have 1 secret for all projects ?

Our secret:
```
apiVersion: v1
data:
  sshPrivateKey: XXXX
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repo-creds
  name: creds-github-ssh-key
  namespace: argocd
type: Opaque
```

1 application:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uat-eks
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ukuat
    repoURL: git@github.com:XXXXX.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

**Comment by booleanbetrayal** [comment]
We just upgraded to ArgoCD from 2.14.11 to v3.0.2 and are experiencing the same issue as @jgournet . We have an ExternalSecret that populates a repo secret for all projects, which appears to be breaking ArgoCD.

**Comment by booleanbetrayal** [comment]
> We just upgraded to ArgoCD from 2.14.11 to v3.0.2 and are experiencing the same issue as [@jgournet](https://github.com/jgournet) . We have an ExternalSecret that populates a repo secret for all projects, which appears to be breaking ArgoCD.

This was resolved by providing `data.name` and/or the `metadata.labels` value for `argocd.argoproj.io/secret-type: repository` where they were not provided, in our Secret.

**Comment by wyardley** [comment]
> This was resolved by providing data.name and/or the metadata.labels value for argocd.argoproj.io/secret-type: repository where they were not provided, in our Secret.

This is interesting. Can you give a little more detail on what you had to add to `data.name` / metadata.labels`?

**Comment by booleanbetrayal** [comment]
I am not sure which of the two ultimately resolved the issue, but setting the label `argocd.argoproj.io/secret-type: repository` and setting `data.name` to the same value as the resource name (`metadata.name`) resolved the broken repository.

**Comment by jgournet** [comment]
> I am not sure which of the two ultimately resolved the issue, but setting the label `argocd.argoproj.io/secret-type: repository` and setting `data.name` to the same value as the resource name (`metadata.name`) resolved the broken repository.

However, I tried with those 2 settings, but still getting the same error - but thank you @booleanbetrayal providing things to try

**Comment by umarizulkifli** [comment]
managed to get it fixed by changing the repoUrl
before
```project: system
source:
  repoURL: git@github.com:kfit-dev/app-defs.git
  path: aws-lb-controller/staging/main
  targetRevision: HEAD
destination:
  namespace: kube-system
  name: kind-kind
```
after
```project: system
source:
  repoURL: https://github.com/kfit-dev/app-defs.git
  path: aws-lb-controller/staging/main
  targetRevision: HEAD
destination:
  namespace: kube-system
  name: kind-kind
```
repo-creds
```
apiVersion: v1
data:
  name: <redacted>
  password:  <redacted>
  type: Z2l0
  url:  <redacted>
  username:  <redacted>
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  creationTimestamp: "2025-07-21T19:50:10Z"
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-2126760234
  namespace: argocd
  resourceVersion: "738471204"
  uid: adc837ec-14a4-40e4-b906-011e2c447f18
type: Opaque
```
Screenshots

<img width="1878" height="870" alt="Image" src="https://github.com/user-attachments/assets/f6d7329b-7c44-4908-b649-37bf638ae548" />

<img width="1878" height="870" alt="Image" src="https://github.com/user-attachments/assets/f9449d22-c94a-47cf-8c1a-d6512ccc2ebc" />
