### ISSUE TITLE
Automatic cleanup for stale issues

### ISSUE THREAD

**Issue by reggie-k** [argoproj/argo-cd#20011]
# Summary

I propose to outline criteria according to which issues would be decided on as "stale", and then to auto-close those issues.

# Motivation

We have ~3k open issues and having a more manageable number (at most 2k and ideally closer to 1k) can help us work more effectively.
Closing the issues manually does not seem feasible.

# Proposal

Possible criteria (the numbers were produced last week but they give an estimation of how much we could close based on the criteria):

1. updated > 1 year  and comments < 5 and reactions < 5 = 1081 issues
2. updated > 1 year  and comments < 5 = 1234 issues
3. updated > 1 year  and reactions < 5 = 1226 issues

The issues can be closed with a nice respectful comment, inviting the user to re-open the issue if still relevant.

## Things to consider:
- Maybe a GitHub bot can be used for that (can it be smart and have flexible configuration other than just the issue creation date?)
- Maybe we can use  https://probot.github.io/apps/repo-assistant-ai/ 
- Another option is to write an automation against the GitHub API and to make it as flexible/careful as we need
- We can also label the closed issues with a specific label for easy identification later

**Comment by crenshaw-dev** [comment]
I think I'm an outlier in this, but I really dislike auto-close bots.

First, I think it's a bad experience for issue authors. If an issue goes unanswered, I may think, "darn, no one has time to look at this, but such is life." If something auto-closes, I'm annoyed that I now have to either re-open the issue to keep it from slipping completely off the radar or accept that it's been moved to an even less-visible state. Even if the automated "we're closing this issue" message is nicely-phrased, I know it's still just a bot.

Second, it's a bad experience for readers (both end users and maintainers). If I click a link to an issue and see the purple "closed" label at the top, now I have to scroll to the bottom to answer "okay, was it auto-closed, or was it actually closed by a human?" The "closed by a human" and "closed by a bot" states have very different connotations for the reader.

Finally, I don't think auto-closing actually adds any value. The number of open issues would come to represent "recent/active open issues," but 1) I'm not sure anyone really needs that number and 2) if they do need that number, they can get it via issue search filters.

**Comment by christianh814** [comment]
I only 1/2 agree with Micheal. I really do think that we shouldn't outright close the issues, but mark/label them as "stale" first, then (after X amount of time of no activity) close them.

I do feel we need to close some issues that are old but I'm not a big fan of aggressively closing them.

**Comment by crenshaw-dev** [comment]
I'm 100% in favor of a stale label. It's purely additive and doesn't complicate any existing user or maintainer workflows.

**Comment by jannfis** [comment]
As for some history, we used to have a stale bot. It used to mark issues as stale, and IIRC it even closed issues after a while an issued marked stale didn't receive any further input. But, I don't know what actually happened to it. I think it just stopped working one day.

But I also am in favor of using a stale label. It's good for filtering, and we can decide later what to do with them.

> Second, it's a bad experience for readers (both end users and maintainers). If I click a link to an issue and see the purple "closed" label at the top, now I have to scroll to the bottom to answer "okay, was it auto-closed, or was it actually closed by a human?" The "closed by a human" and "closed by a bot" states have very different connotations for the reader.

I agree, happened to me too often too. I wished there would be a dedicated status for issues that go stale, something like hibernated or so.

**Comment by crenshaw-dev** [comment]
@todaywasawesome not really, not yet. I'd like more details on what "having a more manageable number" means, concretely. In other words, what's the actual benefit to maintainers and to users of closing these issues? I'm sure there are benefits, but I think we need to describe them in order to weigh them against the downsides I listed above.

> updated > 1 year and reactions < 5

I like the reactions rule. Can you describe what "updated" means here? Does that mean "no one has commented in a year"?

**Comment by crenshaw-dev** [comment]
Additional question about your proposed cleanup: would you be able to add a "we're closing this because of stale-ness" message to each closed issue, or is that only available for bot closures?

Another downside to consider is the loss of relevant statistics. Today various tools (LFX Insights, devstats, OSS Insights) collect information about opened/closed issues on a weekly/monthly/etc. basis. Those stats let us estimate how we're doing in terms of managing the issue workload. Automated closures, and especially mass closures, pollute that data and make it unusable for estimating workload vs. capacity.

**Comment by reggie-k** [comment]
@crenshaw-dev @todaywasawesome Sharing the possible GiHub UI search queries for what is above in the description (the date is an example for GitHub UI filter and can be a rolling window using GitHub CLI):
`is:issue is:open updated:<2023-09-01 reactions:<5`
or:
`is:issue is:open updated:<2023-09-01 comments:<5`
or: 
`is:issue is:open updated:<2023-09-01 comments:<5 reactions:<5`

"updated", in my understanding of GitHub API, should reflect any change made to the issue (comment, reaction, status change), I can verify this on some issues with such recent activities.
Yes, the closing can be done with a comment "we're closing this because of stale-ness", without a bot.

I wonder how projects like K8S that use stale bots, deal with the closed issue stats, but I think that even if we decided as a group to dedicate a week and close many stale issues manually, this would also effect those stats, and I think this is normal. Maybe those K8S bots run weekly/daily and close an amount that does not hurt the human stats badly, and maybe the _first_ time such a bot was introduced, that bulk closure did effect the stats one-tme, but a one-time outstanding peek is probably normal and indicates massive cleanup.
And for internal presentation needs I think that the bulk-closed issues can be filtered out by dedicated labels, that can be put during the cleanup, along with the comment.

For me, the benefits of having only relevant issues in the repo are:

- Ability to identify the areas in ArgoCD that need the most attention more effectively, without the "noise" of issues that we know we are not gonna work on. Currently, the updated date filter (and if we wanna be precise, also the comments/reactions filter, as an "old" issue is still potentially interesting if there was a discussion on it) needs to be appended to many queries to get a representing picture.
- Psychological benefit of feeling less overwhelmed by the huge 3k number :)
- I think that closing stale issues is better than silently ignoring them, from user experience, not necessarily for the users that _opened_ those old issues, but for _new_ users that take a first glance at the repo and see 3k open issues (even K8S repo has less :))

**Comment by agilgur5** [comment]
100% agree with Crenshaw. Auto closing without any maintainer input has no real benefits yet has many downsides. The only "positives" I've seen are "number is smaller", which is a false positive (see below), and "prioritize newer issues", which is not necessarily a good thing in and of itself, and can be done with existing filters already.

> * Psychological benefit of feeling less overwhelmed by the huge 3k number

> *  [...] not necessarily for the users that _opened_ those old issues, but for _new_ users that take a first glance at the repo and see 3k open issues

Issues that are closed as stale but not resolved are all false positives and so all those supposed benefits are false positives, while still adding many downsides, frustrating users, making duplicate issues, making searching harder, unnecessary pings from bots, etc.
It also makes closed issues not very helpful for historical purposes either as the "closed" marker no longer holds meaning, as Jann and Crenshaw mentioned above.

Regarding "metrics", please keep in mind common fallacies about those such as [Goodhart's Law](https://en.m.wikipedia.org/wiki/Goodhart%27s_law); if a lower number is a target, that will be achieved despite the benefits or downsides of it.

**Comment by agilgur5** [comment]
Also this has been discussed and modified in other Argoproj repos. For instance, in Workflows see: https://github.com/argoproj/argo-workflows/issues/11802#issuecomment-1720117452 where I outline all scenarios for staleness and then address the few automatable scenarios with a more targeted action that requires a human label first: https://github.com/argoproj/argo-workflows/pull/12488

It's also implemented in Argo UI in the same way: https://github.com/argoproj/argo-ui/pull/549

I would suggest a similar approach if CD is considering it.

I also listed some simple counter-examples to auto-closure in https://github.com/argoproj/argo-workflows/pull/11836#issuecomment-1766661155 -- it's pretty common to have popular issues closed by a stalebot, as age is not necessarily correlated to correctness nor importance.

**Comment by agaudreault** [comment]
+1 on adding "stale" label automatically, but manually closing stale issues for all the reasons above. There's also a need to label an issue to be non-stalable, so the stale bot does not pick it up. For instance, "feature request x" is stale, but a valid low priority request that someone might decide to implement one day.

**Comment by andrii-korotkov-verkada** [comment]
Started a thread here https://cloud-native.slack.com/archives/C020XM04CUW/p1731181366112119 which got me pointed to this discussion.

I propose to auto-close, but be more specific than just by staleness. One idea is to tag issues by a major + minor version where they were observed (use current version + 1 for custom builds from master). Then, close issues which have tags from unsupported versions. This can be reasonable due to issues might be getting fixed in next versions and often it'd be hard to tell after months or years. If the issue is still observed, new tags can be added and the issue won't be closed. There can also be a comment tagging user asking to confirm if the issue is still present once all tagged versions become unsupported. If there are no version tags, it should do nothing.

**Comment by andrii-korotkov-verkada** [comment]
I don't like the idea of filtering by the number of comments or likes though, since they don't fully reflect how important the issue is, i.e. there can be some false positives with this approach.

**Comment by crenshaw-dev** [comment]
> One idea is to tag issues by a major + minor version where they were observed (use current version + 1 for custom builds from master). Then, eventually close issues which have tags from unsupported versions only.

If we have a bot auto-close on an `observed-in/2.0.2` label (or similar), the bot could miss comments saying things like "I saw this in 2.3.5," "still a problem in 2.7.9," etc. If we fail to keep the label up-to-date with the comments, we'll close issues that should still be active.

And all the reasons above still apply regarding why auto-closing issues does not benefit either maintainers nor users.

**Comment by andrii-korotkov-verkada** [comment]
I think we can just close them manually if no new tags are added. Though we'd still have to be active in adding the tags.

**Comment by andrii-korotkov-verkada** [comment]
That's fine, over a few months we can go through all open issues manually and tag/close/ping them. I'm willing to help and already going through a lot of issues commenting on a big part of them (though actually trying to help).
