### ISSUE TITLE
Base path KO during login phase

### ISSUE THREAD

**Issue by lucaspouzac** [argoproj/argo-cd#20790]
Hi,

Since 2.13.0 version, the login phase is KO because the root path is duplicated if login is correct. 

```
server:
  extraArgs:
    - --insecure
    - --rootpath
    - /argocd

  ingress:
    enabled: true
    ingressClassName: "nginx"
    path: /argocd

configs:
  cm:
    url: https://test.com/argocd

notifications:
  enabled: true
  argocdUrl: https://test.com/argocd
```

When login is correct, browser try to load  https://test.com/argocd/argocd/applications

In 2.12.6, it's correct.

Maybe because of this  ?
- https://github.com/argoproj/argo-cd/pull/20004
- https://github.com/argoproj/argo-cd/pull/20571

**Comment by andrii-korotkov-verkada** [comment]
Sorry, what's KO?

**Comment by lucaspouzac** [comment]
After login, the root path is duplicated in url : https://test.com/**argocd/argocd**/applications

**Comment by lsq645599166** [comment]
Hi @lucaspouzac , can you paste you URL of the login page. I wonder whether the redirectUrl is wrong

**Comment by lucaspouzac** [comment]
Reidrect url is correct : https://test.com/argocd/login?return_url=https%3A%2F%2test.com%2Fargocd%2Fapplications

**Comment by lsq645599166** [comment]
> Reidrect url is correct : https://test.com/argocd/login?return_url=https%3A%2F%2test.com%2Fargocd%2Fapplications

It seems ok, can you take a screenshot of the `base` of HTML, like this
![image](https://github.com/user-attachments/assets/e18c6841-326e-4baa-9fb7-589a175914ec)

**Comment by Dutchy-** [comment]
I've noticed the same problem. We run argocd like this:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
  name: argocd-server
spec:
  template:
    spec:
      containers:
      - name: argocd-server
        args:
        - /usr/local/bin/argocd-server
        - --rootpath
        - /argocd
        - --basehref
        - /argocd
```

I've also noticed the same behaviour: the return URL is correct, but it still ends up with a double path after login.
This does not happen with Oauth login, only with a username/password login. This first started on version 2.13.0 after upgrading from version 2.12.6.

**Comment by Dutchy-** [comment]
@lsq645599166 
Looks the same as in your screenshot

<img width="819" alt="image" src="https://github.com/user-attachments/assets/0d2812b3-c2e9-4779-b80f-ad22101a2361">

I haven't included the full URL because it's an internal URL I don't want to share, I hope that's ok

**Comment by lsq645599166** [comment]
There were always issues here, but it unexpectedly worked correctly—until https://github.com/argoproj/argo-cd/pull/19612 was merged. I fix it in the https://github.com/argoproj/argo-cd/pull/20907.

**Comment by HummingMind** [comment]
Can the linked PR fix please be included in the next minor?

Thank you.

**Comment by Kotys** [comment]
I'm running v2.13.2+dc43124 and this issue is still present, looking forward to upgrade where patch is already merged.

**Comment by HummingMind** [comment]
Doesn't look like this made it into 2.14 either?

**Comment by tbernacchi** [comment]
Same here running `v2.14.2+ad27246`

**Comment by tbernacchi** [comment]
@lsq645599166 What is the workaround?

**Comment by HummingMind** [comment]
https://github.com/argoproj/argo-cd/pull/21588 was merged, but it doesn't seem to be in 2.13 or 2.14? Or am I missing something?

**Comment by HummingMind** [comment]
Does anyone know which maintainer to tag on this one? Doesn't seem like they are aware this is still an issue. 😢

**Comment by blakepettersson** [comment]
@HummingMind It looks like it's a part of >= 2.13.4, see 2618ccca2d3b006d0efae31cf94c74f84fb992cd

**Comment by alexmt** [comment]
Ah, looking at it . thank you for letting me know that it is still broken.

**Comment by HummingMind** [comment]
> Ah, looking at it . thank you for letting me know that it is still broken.

Awesome! Please let me know if you need any additional information from me (unless you were able to reproduce already).
🍻

**Comment by matodrobec** [comment]
Hi,

I have same problem. I am using helmchart deploy

Deployed Chart version: `7.8.7` 
Deployed App version: `v2.14.3`

helmchart values are:
```
global:
  domain: test.loc

## Argo Configs
configs:
  params:
    # -- Value for base href in index.html. Used if Argo CD is running behind reverse proxy under subpath different from /
    # server.basehref: /argocd
    # -- Used if Argo CD is running behind reverse proxy under subpath different from /
    server.rootpath: /argocd

## Server
server:
  ingress:
    enabled: true

    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

    path: /argocd
    pathType: Prefix
```

Login url is:
https://test.loc/argocd/login?return_url=https%3A%2F%2Ftest.loc%2Fargocd%2Fapplications

I am redirected to not existed url  after login:
https://test.loc/argocd/argocd/applications

But the correct one is:
https://test.loc/argocd/applications

**Comment by esmithaas** [comment]
Hi, everyone. I'm also seeing this behavior in version **_v2.14.2+ad27246_** upon login of a duplicate "rootpath"


```json
{
    "Version": "v2.14.2+ad27246",
    "BuildDate": "2025-02-05T23:44:17Z",
    "GitCommit": "ad2724661b66ede607db9b5bd4c3c26491f5be67",
    "GitTreeState": "clean",
    "GoVersion": "go1.23.3",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.4.3 2024-07-19T16:40:33Z",
    "HelmVersion": "v3.16.3+gcfd0749",
    "KubectlVersion": "v0.31.0",
    "JsonnetVersion": "v0.20.0"
}
```

**Comment by cvila84** [comment]
hi everyone, I don't know if it deserves another issue but conversely, the logout has the opposite problem...

Logout url is:
<https://test.loc/argocd/auth/logout>

Which redirects (303) to:
<https://test.loc>

**Comment by han-steve** [comment]
Still see the login duplicate problem in 2.14.5

**Comment by cvila84** [comment]
Taking a look to the source code, I finally see it is fixed in 3.0 but not backported in 2.x

See [here](https://github.com/argoproj/argo-cd/blob/v3.0.0-rc1/ui/src/app/login/components/login.tsx#L141)

**Comment by pramodasahoo** [comment]
Hi,
I have same problem. I am using helmchart deploy

Deployed Chart version: 7.8.22
Deployed App version: v2.14.9

in 2.14.9 version, Since the login phase is ok, after that the root path is duplicated.

server.basehref: /argocd
server.rootpath: '/argocd'

but it's redirecting after login https://localhost/argocd/argocd/applications

**Comment by HummingMind** [comment]
This is now working correctly for me in version 2.14.10.

Thank you!

**Comment by tbernacchi** [comment]
Hi @HummingMind how did you upgrade yours?

**Comment by tbernacchi** [comment]
I've just followed these steps:

```
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/v2.14.10/manifests/install.yaml
```

```
kubectl patch deployment argocd-server -n argocd --type='json' -p='[
  {
    "op": "replace",
    "path": "/spec/template/spec/containers/0/args",
    "value": [
      "/usr/local/bin/argocd-server",
      "--insecure",
      "--basehref=/argocd",
      "--rootpath=/argocd"
    ]
  }
]'
```

I'm still facing the issue, looking at the version installed it says it's the `v2.14.9` 

```
root@raspberrypi4-5:~~#  kubectl -n argocd get deployment argocd-server -o=jsonpath='{.spec.template.spec.containers[0].image}' | cut -d ":" -f2
v2.14.9
```

Looking at the `install.yml` file I've found the image it's still in `v2.14.9`. (v2.14.9)[https://raw.githubusercontent.com/argoproj/argo-cd/v2.14.10/manifests/install.yaml#:~:text=cm%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20optional%3A%20true-,image%3A%20quay.io/argoproj/argocd%3Av2.14.9,-imagePullPolicy%3A%20Always%0A%20%20%20%20%20%20%20%20name]

**Comment by HummingMind** [comment]
> Hi [@HummingMind](https://github.com/HummingMind) how did you upgrade yours?

I am using one of their helm charts, so I just used the newer chart.

**Comment by tbernacchi** [comment]
[UPDATE] - All good here. Thanks @alexmt

**Comment by alexmt** [comment]
thank you for verifying it @tbernacchi ! Let me know please if issue needs to be re-open
