### ISSUE TITLE
2.14.3 application-controller sync loop on server-side apply helm chart

### ISSUE THREAD

**Issue by cterence** [argoproj/argo-cd#22142]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

In version 2.14.3, the application-controller enters a sync loop burning CPU while trying to sync an app deploying kube-prometheus-stack using server-side apply.

Reverting to 2.14.2 solved the issue for me.

I'm not sure if server-side apply triggers this bug.

**To Reproduce**

- Deploy kube-prometheus-stack helm chart in version 69.7.2 with server-side apply enabled
- Launch a sync:
  - Sync status stays at `waiting for deletion of batch/Job/kube-prometheus-stack-admission-patch`
  - `kube-prometheus-stack-admission-patch` job is never deleted
  - Deleting the `argocd.argoproj.io/hook-finalizer` finalizer removes the job and stops the sync loop until another sync is triggered on the app

Code from my gitops repo for context:
- [argocd helm chart](https://github.com/cterence/homelab-gitops/tree/eae5a5c839dc1b2df78de6c827fa462de41d57c3/k8s-apps/argocd)
- [kube-prometheus-stack helm chart](https://github.com/cterence/homelab-gitops/tree/eae5a5c839dc1b2df78de6c827fa462de41d57c3/k8s-apps/kube-prometheus-stack)
- [applicationset deploying both charts](https://github.com/cterence/homelab-gitops/blob/eae5a5c839dc1b2df78de6c827fa462de41d57c3/argocd-apps/applicationset.yaml)

**Expected behavior**

- Launch a sync
- Application syncs and goes back to Sync OK status

**Screenshots**

![Image](https://github.com/user-attachments/assets/64aec5c1-6a74-4f4e-9879-30a91cf13343)

![Image](https://github.com/user-attachments/assets/fbfb4dba-2f5e-4326-8601-07c3a1afdf9c)

**Version**

```shell
argocd: v2.14.3+71fd4e5
  BuildDate: 2025-02-28T18:56:13Z
  GitCommit: 71fd4e501d0d688ab0d70cd649fbf5f909cff12b
  GitTreeState: clean
  GoVersion: go1.23.3
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

While the sync loop is occuring, the application-controller logs this sequence indefinitely:

```
time="2025-03-03T22:21:12Z" level=info msg="Updating operation state. phase: Running -> Running, message: 'waiting for deletion of batch/Job/kube-prometheus-stack-admission-patch' -> 'one or more tasks are running'" application=argocd/kube-prometheus-stack syncId=00265-zsvKO
time="2025-03-03T22:21:12Z" level=info msg="Updating operation state. phase: Running -> Running, message: 'one or more tasks are running' -> 'waiting for deletion of batch/Job/kube-prometheus-stack-admission-patch'" application=argocd/kube-prometheus-stack syncId=00265-zsvKO
time="2025-03-03T22:21:12Z" level=info msg="sync/terminate complete" application=argocd/kube-prometheus-stack duration=41.428151ms syncId=00265-zsvKO
time="2025-03-03T22:21:12Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" app-namespace=argocd app-qualified-name=argocd/kube-prometheus-stack application=kube-prometheus-stack project=default
time="2025-03-03T22:21:12Z" level=info msg="Ignore status for all objects"
time="2025-03-03T22:21:12Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: monitoring)" application=argocd/kube-prometheus-stack
time="2025-03-03T22:21:12Z" level=info msg="No operation updates necessary to 'argocd/kube-prometheus-stack'. Skipping patch" app-namespace=argocd app-qualified-name=argocd/kube-prometheus-stack application=kube-prometheus-stack project=default
time="2025-03-03T22:21:12Z" level=info msg="Resuming in-progress operation. phase: Running, message: waiting for deletion of batch/Job/kube-prometheus-stack-admission-patch" app-namespace=argocd app-qualified-name=argocd/kube-prometheus-stack application=kube-prometheus-stack project=default
time="2025-03-03T22:21:12Z" level=info msg="Ignore status for all objects"
time="2025-03-03T22:21:12Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: monitoring)" application=argocd/kube-prometheus-stack
time="2025-03-03T22:21:12Z" level=info msg="GetRepoObjs stats" application=argocd/kube-prometheus-stack build_options_ms=0 manifests_ms=156 plugins_ms=0 repo_ms=0 time_ms=156
time="2025-03-03T22:21:12Z" level=info msg="GetRepoObjs stats" application=argocd/kube-prometheus-stack build_options_ms=0 manifests_ms=150 plugins_ms=0 repo_ms=0 time_ms=150
time="2025-03-03T22:21:12Z" level=info msg="Ignore status for all objects"
time="2025-03-03T22:21:12Z" level=info msg="Ignore status for all objects"
time="2025-03-03T22:21:12Z" level=info msg="Ignore status for all objects"
time="2025-03-03T22:21:13Z" level=info msg="Skipping auto-sync: another operation is in progress" app-namespace=argocd app-qualified-name=argocd/kube-prometheus-stack application=kube-prometheus-stack project=default
time="2025-03-03T22:21:13Z" level=info msg="No status changes. Skipping patch" app-namespace=argocd app-qualified-name=argocd/kube-prometheus-stack application=kube-prometheus-stack project=default
time="2025-03-03T22:21:13Z" level=info msg="Reconciliation completed" app-namespace=argocd app-qualified-name=argocd/kube-prometheus-stack app_status_update_ms=0 application=kube-prometheus-stack auto_sync_ms=0 compare_app_state_ms=187 comparison-level=1 comparison_with_nothing_ms=0 dedup_ms=1 dest-name=in-cluster dest-namespace=monitoring dest-server="https://kubernetes.default.svc" diff_ms=22 git_ms=156 health_ms=2 live_ms=3 normalize_application_ms=2 patch_ms=0 persist_app_status_ms=1 process_finalizers_ms=0 project=default refresh_app_conditions_ms=0 set_app_managed_resources_ms=342 setop_ms=0 settings_ms=0 sync_ms=0 time_ms=533
time="2025-03-03T22:21:13Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" app-namespace=argocd app-qualified-name=argocd/kube-prometheus-stack application=kube-prometheus-stack project=default
time="2025-03-03T22:21:13Z" level=info msg="Ignore status for all objects"
time="2025-03-03T22:21:13Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: monitoring)" application=argocd/kube-prometheus-stack
time="2025-03-03T22:21:13Z" level=info msg="GetRepoObjs stats" application=argocd/kube-prometheus-stack build_options_ms=0 manifests_ms=137 plugins_ms=0 repo_ms=0 time_ms=137
time="2025-03-03T22:21:13Z" level=info msg=Syncing application=argocd/kube-prometheus-stack skipHooks=false started=true syncId=00266-slUso
time="2025-03-03T22:21:13Z" level=info msg="Namespace already exists" application=argocd/kube-prometheus-stack namespace=monitoring syncId=00266-slUso
time="2025-03-03T22:21:13Z" level=info msg=Tasks application=argocd/kube-prometheus-stack syncId=00266-slUso tasks="[PreSync/0 hook /ServiceAccount:monitoring/kube-prometheus-stack-admission nil->obj (,Succeeded,kube-prometheus-stack-admission created), PreSync/0 hook rbac.authorization.k8s.io/ClusterRole:monitoring/kube-prometheus-stack-admission nil->obj (,Succeeded,kube-prometheus-stack-admission created), PreSync/0 hook rbac.authorization.k8s.io/ClusterRoleBinding:monitoring/kube-prometheus-stack-admission nil->obj (,Succeeded,kube-prometheus-stack-admission created), PreSync/0 hook rbac.authorization.k8s.io/Role:monitoring/kube-prometheus-stack-admission nil->obj (,Succeeded,kube-prometheus-stack-admission created), PreSync/0 hook rbac.authorization.k8s.io/RoleBinding:monitoring/kube-prometheus-stack-admission nil->obj [truncated for brevity]
```

**Comment by uluzox** [comment]
I second that using the same ArgoCD and kube-prometheus-stack helm chart version, kube-prometheus-stack-admission-patch job is never deleted.

**Comment by KonstantinNosov** [comment]
same here. Reverted to v2.14.2

**Comment by kuznero** [comment]
Same

**Comment by jemand771** [comment]
linking some recent issues with similar symptoms and _maybe_ the same cause for completeness:
* https://github.com/argoproj/argo-cd/issues/22167
* https://github.com/argoproj/argo-cd/issues/22159

(not exactly duplicates, rather just more context)

**Comment by agaudreault** [comment]
There was an issue with that release due to https://github.com/argoproj/argo-cd/pull/22163. I will close this issue since it should be fixed in 2.14.4.

However, if you can test with master (3.0) and have the same issue with hook finalizers, you should create a new issue and link it so we can investigate deeper. The finalizer is intended to be present, until the hook object has successfully completed, meaning it has a healthy health or no health state.

**Comment by cterence** [comment]
Updating to 2.14.4 solved the problem I described in the issue. Is your setup different @kuznero ?

**Comment by e3b0c442** [comment]
I'm also still experiencing this on 2.14.4.

**Comment by andrey-parkhomets** [comment]
for me 2.14.4 solvs problem too, few days ago when I update from [2.14.3](https://cloud-native.slack.com/archives/C01TSERG0KZ/p1741106420616459?thread_ts=1741102221.354689&cid=C01TSERG0KZ).

I have ArgoCD setup where I'm able bootstrap ArgoCD from scratch many times as needed to check ability recover from a empty state.

Today and trigger re-installation of ArgoCD and I got that problem too !

**Comment by synthe102** [comment]
Got that issue too with a fresh Argo CD install version 2.14.4, upgrading to 2.14.5 did not fix the issue.

**Comment by crenshaw-dev** [comment]
Reopened because I see people are still impacted, but I suspect the problem is that you need to manually remove the finalizer. Starting with 2.14.4 it should no longer be erroneously _added_ to resources, but it also won't be automatically removed. We might have to add cleanup code to the 2.14 release series of a bunch of people are impacted. But please try manually clearing the finalizer and confirm whether that solves the problem for you.

**Comment by crenshaw-dev** [comment]
I was able to reproduce this in 2.14.3, but not in 2.14.6 or 3.0.0-rc1. 

If you're still encountering the issue in a recent version, please add details to reproduce it.
