### ISSUE TITLE
diff not showing item removed from list

### ISSUE THREAD

**Issue by PartlyFluked** [argoproj/argo-cd#22345]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

`argocd app diff` is not picking up on a removed item from a list, in this case from `Service.spec.ports[]`.

**To Reproduce**

I have written this minimal script to reproduce the bug. It requires k3d/helm/kubectl to already be installed. If you already have a cluster you can remove the first line:

```bash
k3d cluster create test-cluster --k3s-arg="--selinux@server:0"
helm repo add argo https://argoproj.github.io/argo-helm
cat <<EOF > argocd-vals.yaml
configs:
  params:
    server.insecure: true
    controller.diff.server.side: "true"
EOF
helm install argocd argo/argo-cd -n argocd --create-namespace --version 7.8.10 -f argocd-vals.yaml --wait
pw=$(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d)
kubectl port-forward svc/argocd-server -n argocd 8080:443 &
sleep 5
curl -sSL -o argocd http://localhost:8080/download/argocd-linux-amd64
chmod +x argocd
./argocd login 127.0.0.1:8080 --username admin --password $pw --plaintext
cat <<EOF > app.yml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-svc-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: IncludeMutationWebhook=true
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: default
    name: in-cluster
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
  source:
    path: "."
    repoURL: "file://`pwd`/test-svc"
    targetRevision: ""
EOF
kubectl apply -f app.yml
mkdir -p test-svc/templates
pushd test-svc
cat <<EOF > Chart.yaml
apiVersion: v2
name: test-svc
type: application
version: 0.1.0
appVersion: "1.0"
EOF
cat <<EOF > templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: test-svc
  namespace: default
spec:
  ports:
  - name: test1
    port: 1111
  - name: test2
    port: 2222
EOF
../argocd app sync test-svc-app --local . --server-side
cat <<EOF > templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: test-svc
  namespace: default
spec:
  ports:
  - name: test2
    port: 2222
EOF
../argocd app diff test-svc-app --local `pwd` --server-side-generate
```

**Expected behavior**

`argocd app diff` should show the removed port.

**Version**

```shell
argocd: v2.12.3+6b9cd82
  BuildDate: 2024-08-27T11:57:48Z
  GitCommit: 6b9cd828c6e9807398869ad5ac44efd2c28422d6
  GitTreeState: clean
  GoVersion: go1.22.4
  Compiler: gc
  Platform: linux/amd64
Handling connection for 8080
Handling connection for 8080
argocd-server: v2.12.3+6b9cd82
  BuildDate: 2024-08-27T11:57:48Z
  GitCommit: 6b9cd828c6e9807398869ad5ac44efd2c28422d6
  GitTreeState: clean
  GoVersion: go1.22.4
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.4.2 2024-05-22T15:19:38Z
  Helm Version: v3.15.2+g1a500d5
  Kubectl Version: v0.29.6
  Jsonnet Version: v0.20.0
```

**Logs**

```shell
$ test-argocd.sh 
INFO[0000] Prep: Network                                
INFO[0000] Created network 'k3d-test-cluster'           
INFO[0000] Created image volume k3d-test-cluster-images 
INFO[0000] Starting new tools node...                   
INFO[0000] Starting node 'k3d-test-cluster-tools'       
INFO[0001] Creating node 'k3d-test-cluster-server-0'    
INFO[0001] Creating LoadBalancer 'k3d-test-cluster-serverlb' 
INFO[0001] Using the k3d-tools node to gather environment information 
INFO[0001] HostIP: using network gateway 172.20.114.129 address 
INFO[0001] Starting cluster 'test-cluster'              
INFO[0001] Starting servers...                          
INFO[0001] Starting node 'k3d-test-cluster-server-0'    
INFO[0006] All agents already running.                  
INFO[0006] Starting helpers...                          
INFO[0006] Starting node 'k3d-test-cluster-serverlb'    
INFO[0013] Injecting records for hostAliases (incl. host.k3d.internal) and for 2 network members into CoreDNS configmap... 
INFO[0015] Cluster 'test-cluster' created successfully! 
INFO[0015] You can now use it like this:                
kubectl cluster-info
"argo" already exists with the same configuration, skipping
NAME: argocd
LAST DEPLOYED: Fri Mar 14 10:22:54 2025
NAMESPACE: argocd
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
In order to access the server UI you have the following options:

1. kubectl port-forward service/argocd-server -n argocd 8080:443

    and then open the browser on http://localhost:8080 and accept the certificate

2. enable ingress in the values file `server.ingress.enabled` and either
      - Add the annotation for ssl passthrough: https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#option-1-ssl-passthrough
      - Set the `configs.params."server.insecure"` in the values file and terminate SSL at your ingress: https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#option-2-multiple-ingress-objects-and-hosts


After reaching the UI the first time you can login with username: admin and the random password generated during the installation. You can find the password by running:

kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d

(You should delete the initial secret afterwards as suggested by the Getting Started Guide: https://argo-cd.readthedocs.io/en/stable/getting_started/#4-login-using-the-cli)
Forwarding from 127.0.0.1:8080 -> 8080
Forwarding from [::1]:8080 -> 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
'admin:login' logged in successfully
Context '127.0.0.1:8080' updated
Warning: metadata.finalizers: "resources-finalizer.argocd.argoproj.io": prefer a domain-qualified finalizer name to avoid accidental conflicts with other finalizer writers
application.argoproj.io/test-svc-app created
~/test-svc ~
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
INFO[0000] helm template . --name-template test-svc-app --namespace default --include-crds  dir=. execID=98517
INFO[0000] Trace                                         args="[helm template . --name-template test-svc-app --namespace default --include-crds]" dir=. operation_name="exec helm" time_ms=77.781244
Handling connection for 8080
Handling connection for 8080
TIMESTAMP  GROUP        KIND   NAMESPACE                  NAME    STATUS   HEALTH        HOOK  MESSAGE
2025-03-14T10:23:55+08:00            Service     default              test-svc   Running   Synced              service/test-svc serverside-applied
2025-03-14T10:23:55+08:00            Service     default              test-svc    Synced  Healthy              service/test-svc serverside-applied
Handling connection for 8080

Handling connection for 8080
Name:               argocd/test-svc-app
Project:            default
Server:             in-cluster
Namespace:          default
URL:                https://argocd.example.com/applications/test-svc-app
Source:
- Repo:             file:///root/test-svc
  Target:           
  Path:             .
SyncWindow:         Sync Allowed
Sync Policy:        Manual
Sync Status:        Synced to 
Health Status:      Healthy

Operation:          Sync
Sync Revision:      
Phase:              Succeeded
Start:              2025-03-14 10:23:55 +0800 AWST
Finished:           2025-03-14 10:23:55 +0800 AWST
Duration:           0s
Message:            successfully synced (all tasks run)

GROUP  KIND     NAMESPACE  NAME      STATUS  HEALTH   HOOK  MESSAGE
       Service  default    test-svc  Synced  Healthy        service/test-svc serverside-applied
WARN[0001] failed to close &{0x3062660}: rpc error: code = Canceled desc = grpc: the client connection is closing 
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
```

**Comment by todaywasawesome** [comment]
@PartlyFluked I'm pretty sure this is related to the use of serverside diff here. My guess is that when you do a server-side apply and remove an object from an array like that, SSA doesn't remove the other list objects because they are owned by the previous change and it's viewed as a potential accidental deletion. Instead, you could set the value to null. I don't have the best grasp on SSA to be honest but if you wouldn't mind trying this again but remove the SSA option from your application I suspect we'll get different results. 

If that's the case, this is a good candidate for documentation updates.

**Comment by pjiang-dev** [comment]
Could you also try upgrading to 2.14? I think this should have been fixed in https://github.com/argoproj/gitops-engine/pull/688

**Comment by PartlyFluked** [comment]
Same issue is occuring with chart 7.8.13:
```
argocd: v2.14.7+d107d4e
  BuildDate: 2025-03-19T17:07:48Z
  GitCommit: d107d4e41a9b8fa792ed6955beca43d2642bad26
  GitTreeState: clean
  GoVersion: go1.23.3
  Compiler: gc
  Platform: linux/amd64
Handling connection for 8080
Handling connection for 8080
argocd-server: v2.14.7+d107d4e
  BuildDate: 2025-03-19T17:07:48Z
  GitCommit: d107d4e41a9b8fa792ed6955beca43d2642bad26
  GitTreeState: clean
  GoVersion: go1.23.3
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.4.3 2024-07-19T16:40:33Z
  Helm Version: v3.16.3+gcfd0749
  Kubectl Version: v0.31.0
  Jsonnet Version: v0.20.0
```

**Comment by PartlyFluked** [comment]
Turning off server-side apply does fix this! Though this is quite annoying as some of my resources are too big to fit in the allowed annotation size, so I do have to use server-side apply for some things...

**Comment by pjiang-dev** [comment]
Cherry picked the fix to 2.14.8.

**Comment by PartlyFluked** [comment]
Unfortunately still not showing the removed diff. I've updated the original Issue with the new output and `argocd version`.

**Comment by pjiang-dev** [comment]
@PartlyFluked Also noticing in the reproducing steps you are generating the diff locally. Does this happen if you use Git only?

**Comment by pjiang-dev** [comment]
Looks like Server Side Diff does not support CLI
