### ISSUE TITLE
ArgoCD UI can not show the clusters details

### ISSUE THREAD

**Issue by maodahua** [argoproj/argo-cd#24229]
Checklist:

* [ x ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ x ] I've included steps to reproduce the bug.
* [ x ] I've pasted the output of `argocd version`.

**Describe the bug**

After upgrade to ArgoCD v3.1.0, when I check the settings, found the UI `Clusters` can list the clusters we set before. But when I click the cluster to see the detials, error occur. 
I search the logs of application-controller and server, can not see any error. And also try to use the CLI to get the details, it works. 
BTW, the clusters are both works, just can not show the details in UI.
Also try to downgrade to 3.0.6 and 3.0.12, same error.

PS: I upgrade from the 2.14 to 3.1

**To Reproduce**

- Click the `Settings`
- Click `Clusters`
- Click one of the cluster

**Expected behavior**

It will show the details of the cluster, like labels, namespaces etc.

**Screenshots**
<img width="2509" height="1257" alt="Image" src="https://github.com/user-attachments/assets/b2c79cee-7132-4821-9720-612c83238e40" />

**Version**

```shell
argocd: v3.1.0+03c4ad8
  BuildDate: 2025-08-13T22:59:30Z
  GitCommit: 03c4ad854c1e6d922a121cd40f505d9bc6e402da
  GitTreeState: clean
  GoVersion: go1.25.0
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v3.1.0+03c4ad8
  BuildDate: 2025-08-13T20:38:38Z
  GitCommit: 03c4ad854c1e6d922a121cd40f505d9bc6e402da
  GitTreeState: clean
  GoVersion: go1.24.6
  Compiler: gc
  Platform: linux/arm64
  Kustomize Version: v5.7.0 2025-06-28T07:00:07Z
  Helm Version: v3.18.4+gd80839c
  Kubectl Version: v0.33.1
  Jsonnet Version: v0.21.0
```

**Logs**

Can not find any error logs.

**Comment by surajyadav1108** [comment]
I think this is specific to argocd: v3.1.0+03c4ad8
cluster details works fine on current master branch build 

https://github.com/user-attachments/assets/a3945ca5-b590-46e4-93dd-153f6e0cf0f2

**Comment by maodahua** [comment]
> I think this is specific to argocd: v3.1.0+03c4ad8
> cluster details works fine on current master branch build

I try to downgrade to 3.0.12 and 3.0.6, still can not see the clusert details. But as I mentioned, the CLI can show, so I reckon it's a UI bug.

**Comment by lsq645599166** [comment]
> > I think this is specific to argocd: v3.1.0+03c4ad8
> > cluster details works fine on current master branch build
> 
> I try to downgrade to 3.0.12 and 3.0.6, still can not see the clusert details. But as I mentioned, the CLI can show, so I reckon it's a UI bug.

Can you paste the response of application detail api, like this

<img width="1645" height="999" alt="Image" src="https://github.com/user-attachments/assets/bd7578af-4f01-4e38-a94a-6a6d591f11c2" />

**Comment by maodahua** [comment]
> Can you paste the response of application detail api, like this

We use an application to create the secret to store the cluster information.

```
{
    "metadata": {
        "name": "argocd-settings",
        "namespace": "argocd",
        "uid": "eb5c59d3-d437-48c0-9bb6-9ceb524749b8",
        "resourceVersion": "762874096",
        "generation": 184548,
        "creationTimestamp": "2024-08-08T05:15:33Z",
        "labels": {
            "argocd.argoproj.io/instance": "bootstrap"
        },
        "annotations": {
            "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"argoproj.io/v1alpha1\",\"kind\":\"Application\",\"metadata\":{\"annotations\":{},\"labels\":{\"argocd.argoproj.io/instance\":\"bootstrap\"},\"name\":\"argocd-settings\",\"namespace\":\"argocd\"},\"spec\":{\"destination\":{\"namespace\":\"argocd\",\"server\":\"https://kubernetes.default.svc\"},\"project\":\"default\",\"source\":{\"path\":\"platform/argocd-settings\",\"repoURL\":\"https://git.tw.com.au/consumer-experience/cx-ee-gitops\",\"targetRevision\":\"HEAD\"},\"syncPolicy\":{\"automated\":{\"prune\":true}}}}\n"
        },
        "managedFields": [
            {
                "manager": "kubectl-client-side-apply",
                "operation": "Update",
                "apiVersion": "argoproj.io/v1alpha1",
                "time": "2025-05-12T10:00:26Z",
                "fieldsType": "FieldsV1",
                "fieldsV1": {
                    "f:spec": {
                        "f:source": {
                            "f:targetRevision": {}
                        }
                    }
                }
            },
            {
                "manager": "argocd-controller",
                "operation": "Update",
                "apiVersion": "argoproj.io/v1alpha1",
                "time": "2025-05-13T03:08:25Z",
                "fieldsType": "FieldsV1",
                "fieldsV1": {
                    "f:metadata": {
                        "f:annotations": {
                            ".": {},
                            "f:kubectl.kubernetes.io/last-applied-configuration": {}
                        },
                        "f:labels": {
                            ".": {},
                            "f:argocd.argoproj.io/instance": {}
                        }
                    },
                    "f:spec": {
                        ".": {},
                        "f:destination": {
                            ".": {},
                            "f:namespace": {},
                            "f:server": {}
                        },
                        "f:project": {},
                        "f:source": {
                            ".": {},
                            "f:path": {},
                            "f:repoURL": {}
                        },
                        "f:syncPolicy": {
                            ".": {},
                            "f:automated": {
                                ".": {},
                                "f:prune": {}
                            }
                        }
                    }
                }
            },
            {
                "manager": "argocd-application-controller",
                "operation": "Update",
                "apiVersion": "argoproj.io/v1alpha1",
                "time": "2025-09-01T02:53:04Z",
                "fieldsType": "FieldsV1",
                "fieldsV1": {
                    "f:status": {
                        ".": {},
                        "f:controllerNamespace": {},
                        "f:health": {
                            ".": {},
                            "f:lastTransitionTime": {},
                            "f:status": {}
                        },
                        "f:history": {},
                        "f:operationState": {
                            ".": {},
                            "f:finishedAt": {},
                            "f:message": {},
                            "f:operation": {
                                ".": {},
                                "f:initiatedBy": {
                                    ".": {},
                                    "f:automated": {}
                                },
                                "f:retry": {
                                    ".": {},
                                    "f:limit": {}
                                },
                                "f:sync": {
                                    ".": {},
                                    "f:prune": {},
                                    "f:revision": {}
                                }
                            },
                            "f:phase": {},
                            "f:startedAt": {},
                            "f:syncResult": {
                                ".": {},
                                "f:resources": {},
                                "f:revision": {},
                                "f:source": {
                                    ".": {},
                                    "f:path": {},
                                    "f:repoURL": {},
                                    "f:targetRevision": {}
                                }
                            }
                        },
                        "f:reconciledAt": {},
                        "f:resourceHealthSource": {},
                        "f:resources": {},
                        "f:sourceHydrator": {},
                        "f:sourceType": {},
                        "f:summary": {},
                        "f:sync": {
                            ".": {},
                            "f:comparedTo": {
                                ".": {},
                                "f:destination": {
                                    ".": {},
                                    "f:namespace": {},
                                    "f:server": {}
                                },
                                "f:source": {
                                    ".": {},
                                    "f:path": {},
                                    "f:repoURL": {},
                                    "f:targetRevision": {}
                                }
                            },
                            "f:revision": {},
                            "f:status": {}
                        }
                    }
                }
            }
        ]
    },
    "spec": {
        "source": {
            "repoURL": "https://git.tw.com.au/consumer-experience/cx-ee-gitops",
            "path": "platform/argocd-settings",
            "targetRevision": "HEAD"
        },
        "destination": {
            "server": "https://kubernetes.default.svc",
            "namespace": "argocd"
        },
        "project": "default",
        "syncPolicy": {
            "automated": {
                "prune": true
            }
        }
    },
    "status": {
        "resources": [
            {
                "version": "v1",
                "kind": "Secret",
                "namespace": "argocd",
                "name": "cluster-mgmt",
                "status": "Synced"
            },
            {
                "group": "external-secrets.io",
                "version": "v1",
                "kind": "ExternalSecret",
                "namespace": "argocd",
                "name": "cluster-dev",
                "status": "Synced",
                "health": {
                    "status": "Healthy",
                    "message": "secret synced"
                }
            },
            {
                "group": "external-secrets.io",
                "version": "v1",
                "kind": "ExternalSecret",
                "namespace": "argocd",
                "name": "cluster-prod",
                "status": "Synced",
                "health": {
                    "status": "Healthy",
                    "message": "secret synced"
                }
            },
            {
                "group": "external-secrets.io",
                "version": "v1",
                "kind": "ExternalSecret",
                "namespace": "argocd",
                "name": "cx-ai-repo-creds",
                "status": "Synced",
                "health": {
                    "status": "Healthy",
                    "message": "secret synced"
                }
            },
            {
                "group": "external-secrets.io",
                "version": "v1",
                "kind": "ExternalSecret",
                "namespace": "argocd",
                "name": "helm-dockerhub-credential",
                "status": "Synced",
                "health": {
                    "status": "Healthy",
                    "message": "secret synced"
                }
            },
            {
                "group": "external-secrets.io",
                "version": "v1",
                "kind": "ExternalSecret",
                "namespace": "argocd",
                "name": "repository-ecr",
                "status": "Synced",
                "health": {
                    "status": "Healthy",
                    "message": "secret synced"
                }
            },
            {
                "group": "gateway.networking.k8s.io",
                "version": "v1",
                "kind": "HTTPRoute",
                "namespace": "argocd",
                "name": "argocd-applicationset-controller",
                "status": "Synced",
                "health": {
                    "status": "Healthy",
                    "message": "HTTPRoute is healthy"
                }
            },
            {
                "group": "gateway.networking.k8s.io",
                "version": "v1",
                "kind": "HTTPRoute",
                "namespace": "argocd",
                "name": "argocd-server",
                "status": "Synced",
                "health": {
                    "status": "Healthy",
                    "message": "HTTPRoute is healthy"
                }
            },
            {
                "group": "generators.external-secrets.io",
                "version": "v1alpha1",
                "kind": "ECRAuthorizationToken",
                "namespace": "argocd",
                "name": "ecr-auth-token",
                "status": "Synced"
            }
        ],
        "sync": {
            "status": "Synced",
            "comparedTo": {
                "source": {
                    "repoURL": "https://git.tw.com.au/consumer-experience/cx-ee-gitops",
                    "path": "platform/argocd-settings",
                    "targetRevision": "HEAD"
                },
                "destination": {
                    "server": "https://kubernetes.default.svc",
                    "namespace": "argocd"
                }
            },
            "revision": "9f2a6c5fc87746fdeabd092d9f4dc26d2461a655"
        },
        "health": {
            "status": "Healthy",
            "lastTransitionTime": "2025-08-03T17:53:42Z"
        },
        "history": [
            {
                "revision": "c9ef739ad0c789e1c279460c6965947aa5ebc401",
                "deployedAt": "2024-12-16T09:33:35Z",
                "id": 9,
                "source": {
                    "repoURL": "https://git.tw.com.au/consumer-experience/cx-ee-gitops",
                    "path": "platform/argocd-settings",
                    "targetRevision": "HEAD"
                },
                "deployStartedAt": "2024-12-16T09:33:34Z",
                "initiatedBy": {
                    "username": "admin"
                }
            },
            {
                "revision": "ff59719eef21449a4f1a5f67dd1dcfb608098c00",
                "deployedAt": "2025-01-09T04:57:33Z",
                "id": 10,
                "source": {
                    "repoURL": "https://git.tw.com.au/consumer-experience/cx-ee-gitops",
                    "path": "platform/argocd-settings",
                    "targetRevision": "HEAD"
                },
                "deployStartedAt": "2025-01-09T04:57:33Z",
                "initiatedBy": {
                    "automated": true
                }
            },
            {
                "revision": "307b7d2708dc23bc11a59403c6bc560a80723dd0",
                "deployedAt": "2025-05-12T09:51:08Z",
                "id": 11,
                "source": {
                    "repoURL": "https://git.tw.com.au/consumer-experience/cx-ee-gitops",
                    "path": "platform/argocd-settings",
                    "targetRevision": "imagepullsecret"
                },
                "deployStartedAt": "2025-05-12T09:51:07Z",
                "initiatedBy": {
                    "automated": true
                }
            },
            {
                "revision": "d9ec11ff3edbe61eed54e35d2ea61c83c3225297",
                "deployedAt": "2025-05-12T10:00:27Z",
                "id": 12,
                "source": {
                    "repoURL": "https://git.tw.com.au/consumer-experience/cx-ee-gitops",
                    "path": "platform/argocd-settings",
                    "targetRevision": "HEAD"
                },
                "deployStartedAt": "2025-05-12T10:00:26Z",
                "initiatedBy": {
                    "automated": true
                }
            },
            {
                "revision": "ecd5a84042f19f2854a228c94637277fad966f88",
                "deployedAt": "2025-05-13T07:05:28Z",
                "id": 13,
                "source": {
                    "repoURL": "https://git.tw.com.au/consumer-experience/cx-ee-gitops",
                    "path": "platform/argocd-settings",
                    "targetRevision": "HEAD"
                },
                "deployStartedAt": "2025-05-13T07:05:24Z",
                "initiatedBy": {
                    "automated": true
                }
            },
            {
                "revision": "ecd5a84042f19f2854a228c94637277fad966f88",
                "deployedAt": "2025-05-13T07:32:17Z",
                "id": 14,
                "source": {
                    "repoURL": "https://git.tw.com.au/consumer-experience/cx-ee-gitops",
                    "path": "platform/argocd-settings",
                    "targetRevision": "HEAD"
                },
                "deployStartedAt": "2025-05-13T07:32:14Z",
                "initiatedBy": {
                    "username": "admin"
                }
            },
            {
                "revision": "ecd5a84042f19f2854a228c94637277fad966f88",
                "deployedAt": "2025-05-13T07:42:49Z",
                "id": 15,
                "source": {
                    "repoURL": "https://git.tw.com.au/consumer-experience/cx-ee-gitops",
                    "path": "platform/argocd-settings",
                    "targetRevision": "HEAD"
                },
                "deployStartedAt": "2025-05-13T07:42:47Z",
                "initiatedBy": {
                    "username": "admin"
                }
            },
            {
                "revision": "11c512d94027e574129e8254fb8ad8bf3e291a24",
                "deployedAt": "2025-05-13T07:58:48Z",
                "id": 16,
                "source": {
                    "repoURL": "https://git.tw.com.au/consumer-experience/cx-ee-gitops",
                    "path": "platform/argocd-settings",
                    "targetRevision": "HEAD"
                },
                "deployStartedAt": "2025-05-13T07:58:44Z",
                "initiatedBy": {
                    "username": "admin"
                }
            },
            {
                "revision": "94b5b6a21c2f629965643e6217544659156bfa36",
                "deployedAt": "2025-05-16T07:35:40Z",
                "id": 17,
                "source": {
                    "repoURL": "https://git.tw.com.au/consumer-experience/cx-ee-gitops",
                    "path": "platform/argocd-settings",
                    "targetRevision": "HEAD"
                },
                "deployStartedAt": "2025-05-16T07:35:38Z",
                "initiatedBy": {
                    "automated": true
                }
            },
            {
                "revision": "30fa9398c34efe3d920931d24b77500281132e69",
                "deployedAt": "2025-06-06T03:12:06Z",
                "id": 18,
                "source": {
                    "repoURL": "https://git.tw.com.au/consumer-experience/cx-ee-gitops",
                    "path": "platform/argocd-settings",
                    "targetRevision": "HEAD"
                },
                "deployStartedAt": "2025-06-06T03:12:04Z",
                "initiatedBy": {
                    "automated": true
                }
            }
        ],
        "reconciledAt": "2025-09-01T02:53:04Z",
        "operationState": {
            "operation": {
                "sync": {
                    "revision": "30fa9398c34efe3d920931d24b77500281132e69",
                    "prune": true
                },
                "initiatedBy": {
                    "automated": true
                },
                "retry": {
                    "limit": 5
                }
            },
            "phase": "Succeeded",
            "message": "successfully synced (all tasks run)",
            "syncResult": {
                "resources": [
                    {
                        "group": "",
                        "version": "v1",
                        "kind": "Secret",
                        "namespace": "argocd",
                        "name": "cluster-mgmt",
                        "status": "Synced",
                        "message": "secret/cluster-mgmt unchanged",
                        "hookPhase": "Running",
                        "syncPhase": "Sync"
                    },
                    {
                        "group": "gateway.networking.k8s.io",
                        "version": "v1",
                        "kind": "HTTPRoute",
                        "namespace": "argocd",
                        "name": "argocd-applicationset-controller",
                        "status": "Synced",
                        "message": "httproute.gateway.networking.k8s.io/argocd-applicationset-controller configured",
                        "hookPhase": "Running",
                        "syncPhase": "Sync"
                    },
                    {
                        "group": "gateway.networking.k8s.io",
                        "version": "v1",
                        "kind": "HTTPRoute",
                        "namespace": "argocd",
                        "name": "argocd-server",
                        "status": "Synced",
                        "message": "httproute.gateway.networking.k8s.io/argocd-server configured",
                        "hookPhase": "Running",
                        "syncPhase": "Sync"
                    },
                    {
                        "group": "external-secrets.io",
                        "version": "v1",
                        "kind": "ExternalSecret",
                        "namespace": "argocd",
                        "name": "cluster-prod",
                        "status": "Synced",
                        "message": "externalsecret.external-secrets.io/cluster-prod configured",
                        "hookPhase": "Running",
                        "syncPhase": "Sync"
                    },
                    {
                        "group": "external-secrets.io",
                        "version": "v1",
                        "kind": "ExternalSecret",
                        "namespace": "argocd",
                        "name": "cluster-dev",
                        "status": "Synced",
                        "message": "externalsecret.external-secrets.io/cluster-dev configured",
                        "hookPhase": "Running",
                        "syncPhase": "Sync"
                    },
                    {
                        "group": "external-secrets.io",
                        "version": "v1",
                        "kind": "ExternalSecret",
                        "namespace": "argocd",
                        "name": "cx-ai-repo-creds",
                        "status": "Synced",
                        "message": "externalsecret.external-secrets.io/cx-ai-repo-creds configured",
                        "hookPhase": "Running",
                        "syncPhase": "Sync"
                    },
                    {
                        "group": "generators.external-secrets.io",
                        "version": "v1alpha1",
                        "kind": "ECRAuthorizationToken",
                        "namespace": "argocd",
                        "name": "ecr-auth-token",
                        "status": "Synced",
                        "message": "ecrauthorizationtoken.generators.external-secrets.io/ecr-auth-token unchanged",
                        "hookPhase": "Running",
                        "syncPhase": "Sync"
                    },
                    {
                        "group": "external-secrets.io",
                        "version": "v1",
                        "kind": "ExternalSecret",
                        "namespace": "argocd",
                        "name": "repository-ecr",
                        "status": "Synced",
                        "message": "externalsecret.external-secrets.io/repository-ecr unchanged",
                        "hookPhase": "Running",
                        "syncPhase": "Sync"
                    },
                    {
                        "group": "external-secrets.io",
                        "version": "v1",
                        "kind": "ExternalSecret",
                        "namespace": "argocd",
                        "name": "helm-dockerhub-credential",
                        "status": "Synced",
                        "message": "externalsecret.external-secrets.io/helm-dockerhub-credential configured",
                        "hookPhase": "Running",
                        "syncPhase": "Sync"
                    }
                ],
                "revision": "30fa9398c34efe3d920931d24b77500281132e69",
                "source": {
                    "repoURL": "https://git.tw.com.au/consumer-experience/cx-ee-gitops",
                    "path": "platform/argocd-settings",
                    "targetRevision": "HEAD"
                }
            },
            "startedAt": "2025-06-06T03:12:04Z",
            "finishedAt": "2025-06-06T03:12:07Z"
        },
        "sourceType": "Helm",
        "summary": {},
        "resourceHealthSource": "appTree",
        "controllerNamespace": "argocd",
        "sourceHydrator": {}
    }
}
```

**Comment by lsq645599166** [comment]
emm, I mean is it any error response of the the application detail api

**Comment by maodahua** [comment]
For the api in your screenshot, it is 200.

<img width="1547" height="691" alt="Image" src="https://github.com/user-attachments/assets/baaeb4ec-3e8f-43f2-b14c-35221a5e687f" />

**Comment by surajyadav1108** [comment]
@maodahua I think this was probably caused by an issue with External-secret objects in UI

 here [The ArgoCD ui throws an error when clicking on an "External-Secret" object.](https://github.com/argoproj/argo-cd/issues/23886#issuecomment-3246637069) 

which is fixed in 3.1.1 as the last comment suggests in issue discussion can you check if cluster details are accessible in 3.1.1 now?

**Comment by parthyp** [comment]
v3.1.8+becb020 fixed the issue for me

**Comment by maodahua** [comment]
> v3.1.8+becb020 fixed the issue for me

<img width="1665" height="168" alt="Image" src="https://github.com/user-attachments/assets/51c7fa09-1063-4750-9055-3e5f11104166" />
Still not works for me.

**Comment by O5ten** [comment]
Getting this error with argocd 3.3.6, cluster secrets are created by ESO so it seems to match the description of this problem. I'm also running envoy with Gateway API that does some kind of deduplication of forward slashes on the URL from what i have read about. 

<img width="1907" height="1028" alt="Image" src="https://github.com/user-attachments/assets/ef33d443-db3d-40cc-bdf3-0b30a72065b2" />

Here is the error in the console: 
<img width="958" height="282" alt="Image" src="https://github.com/user-attachments/assets/bc16f732-34b4-4446-9160-34982556e1cb" />


What my ESO-created secret looks like: 
```yaml
kind: Secret
apiVersion: v1
data: 
  ...
metadata:
  annotations:
    reconcile.external-secrets.io/data-hash: c3925372a59fa92c7683df9504d2e208f8a1e2850649dc43f1b47982
  creationTimestamp: "2026-04-17T20:06:37Z"
  labels:
    argocd.argoproj.io/secret-type: cluster
    managed-by: argocd.argoproj.io
    reconcile.external-secrets.io/created-by: 4fbf2361981e06fe7fa70bbce4ffd2f74407b66211a0576b40def334
    reconcile.external-secrets.io/managed: "true"
  name: eso-kv-cluster-i1se
  namespace: argocd
  ownerReferences:
  - apiVersion: external-secrets.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: ExternalSecret
    name: eso-kv-cluster-i1se
    uid: eb867cf8-f89d-4829-accb-0e34425471ec
  resourceVersion: "31339007"
  uid: b5c7c65b-1f45-4b9e-9e66-0c71c6859dc9
type: Opaque

```

It seems to happen irregardless of how i configure the ESO. Now that i tested again for creating this post i also noticed that if i add a manual cluster with CLI it will not work for that either. I'm leaning more and more on that it may be envoy.

**Comment by ashvarts** [comment]
@O5ten I had the same issue with the Envoy. Here is the fix that worked for me:
```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: argocd-keep-escaped-slashes
  namespace: envoy
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: default-external-envoygw
      sectionName: argocd                                      # scope it to just the argocd listener
  path:
    escapedSlashesAction: KeepUnchanged       <-------- This is what's needed
    disableMergeSlashes: true
```

**Comment by maodahua** [comment]
> [@O5ten](https://github.com/O5ten) I had the same issue with the Envoy. Here is the fix that worked for me:
> 
> ```
> apiVersion: gateway.envoyproxy.io/v1alpha1
> kind: ClientTrafficPolicy
> metadata:
>   name: argocd-keep-escaped-slashes
>   namespace: envoy
> spec:
>   targetRefs:
>     - group: gateway.networking.k8s.io
>       kind: Gateway
>       name: default-external-envoygw
>       sectionName: argocd                                      # scope it to just the argocd listener
>   path:
>     escapedSlashesAction: KeepUnchanged       <-------- This is what's needed
>     disableMergeSlashes: true
> ```

This one also works for us. Thanks @ashvarts
