### ISSUE TITLE
Excessive never-ending retry loop of `/api/v1/stream/applications` and `/api/v1/stream/applications/<app>/resource-tree` when OIDC token has expired

### ISSUE THREAD

**Issue by illrill** [argoproj/argo-cd#24807]
Checklist:

- [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
- [X] I've included steps to reproduce the bug.
- [X] I've pasted the output of `argocd version`.

**Describe the bug**

When browsing an Application in the UI, and then leaves the browser tab open / untouched for a while (so that the OIDC token expires), JS-triggered GRPC requests to the `/v1/stream` API's **continues** with a very aggressive retry cadence. We've observed the following requests coming in at a very high request rate:

- `GET /argocd/api/v1/stream/applications?name=<APPLICATION>&appNamespace=argocd` **(~1000 requests per minute)**
- `GET /argocd/api/v1/stream/applications/<APPLICATION>/resource-tree?appNamespace=argocd` **(~200 requests per minute)**

They are all getting 401 responses (rightfully since the token is expired), however this doesn't trigger the "main" browser page to refresh the token / log in again, so the GRPC requests just continue forever until the user clicks a button or refreshes the browser to get a fresh token. Only then does the excessive GRPC calls stop.

The response body is the following (for both requests)

```
{
    "error": {
        "grpc_code": 16,
        "http_code": 401,
        "message": "invalid session: failed to verify the token",
        "http_status": "Unauthorized"
    }
}
```

Browser console:

<img width="953" height="334" alt="Image" src="https://github.com/user-attachments/assets/2fbd04be-8f2b-4585-877f-bc2b444c5a23" />

Logs from `argocd-server`:

```
time="2025-10-01T11:20:26Z" level=info msg="finished call" grpc.code=Unauthenticated grpc.component=server grpc.error="rpc error: code = Unauthenticated desc = invalid session: failed to verify the token" grpc.method=WatchResourceTree grpc.method_type=server_stream grpc.service=application.ApplicationService grpc.start_time="2025-10-01T11:20:26Z" grpc.time_ms=0.507 peer.address="[::1]:55068" protocol=grpc
time="2025-10-01T11:20:26Z" level=warning msg="Failed to verify token: failed to verify token: oidc: token is expired (Token Expiry: 2025-10-01 09:11:14 +0000 UTC)"
time="2025-10-01T11:20:26Z" level=info msg="finished call" grpc.code=Unauthenticated grpc.component=server grpc.error="rpc error: code = Unauthenticated desc = invalid session: failed to verify the token" grpc.method=WatchResourceTree grpc.method_type=server_stream grpc.service=application.ApplicationService grpc.start_time="2025-10-01T11:20:26Z" grpc.time_ms=0.496 peer.address="[::1]:55068" protocol=grpc
time="2025-10-01T11:20:26Z" level=warning msg="Failed to verify token: failed to verify token: oidc: token is expired (Token Expiry: 2025-10-01 09:11:14 +0000 UTC)"
time="2025-10-01T11:20:26Z" level=info msg="finished call" grpc.code=Unauthenticated grpc.component=server grpc.error="rpc error: code = Unauthenticated desc = invalid session: failed to verify the token" grpc.method=Watch grpc.method_type=server_stream grpc.service=application.ApplicationService grpc.start_time="2025-10-01T11:20:26Z" grpc.time_ms=0.558 peer.address="[::1]:55068" protocol=grpc
time="2025-10-01T11:20:26Z" level=warning msg="Failed to verify token: failed to verify token: oidc: token is expired (Token Expiry: 2025-10-01 09:11:14 +0000 UTC)"
time="2025-10-01T11:20:26Z" level=info msg="finished call" grpc.code=Unauthenticated grpc.component=server grpc.error="rpc error: code = Unauthenticated desc = invalid session: failed to verify the token" grpc.method=Watch grpc.method_type=server_stream grpc.service=application.ApplicationService grpc.start_time="2025-10-01T11:20:26Z" grpc.time_ms=0.465 peer.address="[::1]:55068" protocol=grpc
time="2025-10-01T11:20:26Z" level=warning msg="Failed to verify token: failed to verify token: oidc: token is expired (Token Expiry: 2025-10-01 09:11:14 +0000 UTC)"
```

Request statistics:

- `GET /argocd/api/v1/stream/applications?name=<APPLICATION>&appNamespace=argocd`
- ~1000 requests per minute

<img width="3020" height="1700" alt="Image" src="https://github.com/user-attachments/assets/86cd034d-c845-42e0-972b-a3b22ba3f2e9" />

---

- `GET /argocd/api/v1/stream/applications/<APPLICATION>/resource-tree?appNamespace=argocd`
- ~200 requests per minute

<img width="3102" height="1668" alt="Image" src="https://github.com/user-attachments/assets/445dc753-e82f-4546-a1c9-ca6b91847496" />

**To Reproduce**

- Use my OIDC configuration below.
- Open any Application page in the UI.
- Leave it open / untouched until the token has expired.

```
configs:
  params:
    server.rootpath: /argocd
    server.basehref: /argocd
  cm:
    oidc.config: |
      name: Azure
      issuer: https://login.microsoftonline.com/**REDACTED**/v2.0
      clientID: **REDACTED**
      clientSecret: $oidc.azure.clientSecret
      requestedIDTokenClaims:
        groups:
          essential: true
      requestedScopes:
        - openid
        - profile
        - email
```

**Expected behavior**

The main page should be redirected to log in again if these GRPC requests are getting 401 responses. And/or the GRPC requests should stop retrying after X amount of failed requests.

**Version**

```shell
argocd: v3.1.1+fa342d1
  BuildDate: 2025-08-25T17:01:33Z
  GitCommit: fa342d153e0e7942938256aea491a68439a53c44
  GitTreeState: clean
  GoVersion: go1.25.0
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v3.0.12+ed1e239
  BuildDate: 2025-07-25T19:36:41Z
  GitCommit: ed1e2397ef9af6d23b284e39d504308cdda1957b
  GitTreeState: clean
  GoVersion: go1.24.4
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.6.0 2025-01-14T15:12:17Z
  Helm Version: v3.17.1+g980d8ac
  Kubectl Version: v0.32.2
  Jsonnet Version: v0.20.0
```

**Comment by illrill** [comment]
Same situation as discussed in https://github.com/argoproj/argo-cd/issues/10126 (but I believe that was specific for the container logs API). A hint may be that all three of these (my two + the container logs scenario) share the common demeanour of using `requests.loadEventSource`. Not a frontend programmer however so don't take my word for it!

---

`/stream/applications`

https://github.com/argoproj/argo-cd/blob/7396c1a9d2e9c53af2e874cb12516eca6e335b80/ui/src/app/shared/services/applications-service.ts#L183-L216

---

`/stream/applications/<APPLICATION>/resource-tree`

https://github.com/argoproj/argo-cd/blob/7396c1a9d2e9c53af2e874cb12516eca6e335b80/ui/src/app/shared/services/applications-service.ts#L98-L102

---

`/applications/<APPLICATION>/logs`

https://github.com/argoproj/argo-cd/blob/7396c1a9d2e9c53af2e874cb12516eca6e335b80/ui/src/app/shared/services/applications-service.ts#L264-L306

**Comment by illrill** [comment]
Just noticed that this is probably a duplicate of #20106

**Comment by FourFifthsCode** [comment]
> Just noticed that this is probably a duplicate of [#20106](https://github.com/argoproj/argo-cd/issues/20106)

Yeah, seems like it might be the case. You might try checking out this PR https://github.com/argoproj/argo-cd/pull/23727 locally and see if it resolves what you are seeing.

**Comment by illrill** [comment]
So in #23727, there will never be a expired token, so we'll never get 401 responses on these stream requests? Should solve it!

Although, some form of back-off mechanism or retry limit would still be good to have for these requests (in case it's not specifically 401's but some other 4xx or 5xx code)

**Comment by FourFifthsCode** [comment]
> Although, some form of back-off mechanism or retry limit would still be good to have for these requests (in case it's not specifically 401's but some other 4xx or 5xx code)

Agreed, backend fix will solve overall problem, but we should also add backoff/retry on UI as well

**Comment by snuggie12** [comment]
> So in [#23727](https://github.com/argoproj/argo-cd/pull/23727), there will never be a expired token, so we'll never get 401 responses on these stream requests? Should solve it!
> 
> Although, some form of back-off mechanism or retry limit would still be good to have for these requests (in case it's not specifically 401's but some other 4xx or 5xx code)

Yes, for some odd reason after our gloo edge was upgraded these flipped from 401 to 504 and the metrics started reporting it on the wrong gateway as well.

**Comment by vanchaxy** [comment]
Experienced the same problem today. Left an Argo CD (v3.3.3) tab open in the browser for 2 hours and came back to 1.56 million 401 responses (~13,000 requests per minute).

<img width="1538" height="858" alt="Image" src="https://github.com/user-attachments/assets/167ef07b-244d-4000-bec3-eb9d91d1ef4c" />

**Comment by rneuplanche** [comment]
**Still reproducing on v3.4.3 (which already includes the #26917 fix, cherry-picked via #27228) — please consider reopening.**

### Environment
- Argo CD **v3.4.3** (`quay.io/argoproj/argocd:v3.4.3`), 3 `argocd-server` replicas
- Direct OIDC against Okta (org auth server, fixed 60-min token), `enablePKCEAuthentication: true`, `offline_access` requested, `refreshTokenThreshold: 5m`
- Apps installed in other namespaces (`application.namespaces`), so the looping streams carry `appNamespace=…`

### This is *not* a token-refresh problem
Server-side background refresh works — over 12h of `argocd-server` logs:
- `refreshed token for subject`: **12**
- `error checking and refreshing token`: 1
- `invalid_grant` / `no refresh token`: **0**

The session refreshes fine while the tab is active. The loop is purely the UI's handling of a stream 401 once the id_token has fully expired (idle tab).

### What we observe
Same symptom as the original report — `Watch` + `WatchResourceTree` 401s (`invalid session: failed to verify the token`):
- 12h server logs: **4207 `Watch` + 561 `WatchResourceTree`** Unauthenticated, vs a handful on any other method.

A HAR of a stuck session shows the UI *does* now react to the 401 (so #26917 is working) — but re-auth never completes:
- 156 × `GET /auth/login` → 303 → Okta `/authorize`
- 123 × Okta `/authorize` — **all `status 0` (cancelled)**
- **0 × `/auth/callback`**
- only **1** top-level document load for the entire session

The page never actually navigates to the IdP; it just thrashes while the streams keep reconnecting.

### Likely residual cause (after #26917)
`subscribeUnauthorized` reacts to **every** `onError` 401 by assigning `window.location.href` (SSO branch), with no "redirect already in progress" guard:

https://github.com/argoproj/argo-cd/blob/v3.4.3/ui/src/app/app.tsx#L236-L256

```ts
requests.onError.subscribe(async err => {
  if (err.status === 401) {
    if (history.location.pathname.startsWith('/login')) return;
    const isSSO = await isExpiredSSO();
    if (history.location.pathname.startsWith('/login')) return;
    const basehref = ...;
    if (isSSO) {
      window.location.href = `${basehref}/auth/login?return_url=...`;
    } else {
      history.push(`/login?return_url=...`);
    }
  }
});
```

With multiple concurrent streams (`Watch` + `WatchResourceTree`, ×N with apps-in-any-namespace) all emitting 401s in a sub-second burst, each emission re-assigns `window.location.href`, and **each new assignment cancels the previous, still-pending navigation to `/auth/login` → Okta** — which is exactly why every `/authorize` is `status 0` and `/auth/callback` is never reached.
The two early `return`s only guard the SPA route `/login`; the SSO branch does a full-page navigation to the **server** route `/auth/login`, so `history.location.pathname` `/applications/…` during the (non-instant) navigation, the guard never trip the redirect. The `await isExpiredSSO()` widens the window for more 401sto pile in.                                                                                                                                                                 ### Suggested directionInitiate the SSO redirect **once** — e.g. a module-level `redirecting` guar the 401 error stream), and/or close the open `EventSource`s beforenavigating, so a burst of stream 401s results in a single `window.location.lete.

Happy to share the anonymized HAR and full log excerpts.

**Comment by trv-bmpage** [comment]
## Still reproducing on v3.4.3 — idle tabs trigger org-wide Okta `/authorize` rate limit exhaustion, blocking authentication for all users and applications sharing the same Okta org
 
### Environment
- Argo CD **v3.4.3**, 3 `argocd-server` replicas
- Direct OIDC against Okta (custom auth server), `enablePKCEAuthentication: true`, `offline_access` + `refreshTokenThreshold: 5m` configured
- Single application namespace
 
### What the HAR shows
 
We captured a HAR of a stuck session on an idle tab (60-min Okta token, fully expired). The loop ran for **28 seconds** and produced:
 
| Request | Count | Result |
|---|---|---|
| `GET /api/v1/stream/applications` → `401` | **128** | Token expired, triggers redirect |
| `GET /auth/login` → `303` | **63** | Correctly redirects to Okta |
| `GET /authorize` | **63** | 55 × status `0` (cancelled), 6 × `302` (Okta granted), **2 × `429`** (rate limited) |
| `GET /auth/callback` | **4** | All status `0` (cancelled) |
 
**Okta cooperated 6 times** — it returned a `302` to `/auth/callback` on 6 separate occasions. Every single one was cancelled within milliseconds by the next `window.location.href` assignment from the still-running stream retry loop:
 
```
[302]  /authorize          ← Okta grants auth code
[  0]  /auth/callback      ← callback fires, cancelled after 89ms
[303]  /auth/login         ← next stream 401 fires new redirect, killing the callback
 
[302]  /authorize          ← Okta grants again
[  0]  /auth/callback      ← cancelled after 24ms (54ms before next redirect)
 
[302]  /authorize          ← Okta grants again
[  0]  /auth/callback      ← cancelled after 15ms (47ms before next redirect)
 
[302]  /authorize          ← Okta grants again
[  0]  /auth/callback      ← cancelled after 15ms (45ms before next redirect)
```
 
The `/authorize` call rate was **~135 req/min**, which is what eventually triggers Okta 429s — but the primary failure mode is the callback cancellation, not the rate limit. Even when Okta responds instantly, the auth code exchange never completes because stream 401s keep overwriting `window.location.href` every ~200ms.
 
### This is the exact race described in the previous comment
 
The `subscribeUnauthorized` handler has no "redirect in progress" guard. With the stream retry loop firing at ~5 req/sec, each emitting a 401, each emission re-assigns `window.location.href` to `/auth/login` → Okta `/authorize`. The `await isExpiredSSO()` async gap widens the window. The two early `return` guards only catch the SPA `/login` route, not the full-page navigation to the server-side `/auth/login`.
 
Result: users with an idle tab **cannot log back in at all**, regardless of how many times Okta successfully issues an auth code.
 
### Impact
 
This is a **complete authentication failure** for any user who leaves an ArgoCD tab open past the OIDC token TTL. The only recovery is manually closing and reopening the tab. At scale (many engineers with persistent ArgoCD tabs), this generates sustained `/authorize` floods at **~135 req/min per idle tab** that exhaust the org-wide Okta rate limit bucket — a shared resource across all applications in the org — causing login failures for users of other applications that have nothing to do with ArgoCD.
 
### Ask
 
This is a regression introduced between 3.2.x and 3.4.x. The fix — a module-level `redirectInProgress` boolean guard set before the first `window.location.href` assignment and checked at the top of the `onError` handler — is minimal and low-risk. We would strongly request a patch fix.

**Comment by trv-bmpage** [comment]
We've been testing out 3.5.0-rc2, and were able to replicate 401 retries and okta 429 error.

**Comment by tylerauerbeck** [comment]
Confirming that this still seems to be present in 3.5.1.

**Comment by hellojun12** [comment]
Status update for anyone landing here: #28807 (guard the SSO redirect so concurrent 401s stop cancelling the re-auth navigation) was merged on 2026-09-06, but it went to `master` only, after v3.5.2 had been cut. So every released version still has the loop, 3.5.2 included.

@tylerauerbeck's report above holds for 3.5.2 as well. We upgraded a cluster from v3.1.9 to v3.5.2 specifically to fix this and saw no change:

- v3.1.9: peak ~300 401s/min
- v3.5.2: still ~15-25 401s/min from a single idle Pod-logs tab, sustained for 21+ hours and across two full `argocd-server` restarts
- all of them `grpc.method=PodLogs`, `invalid session: failed to verify the token`

In hindsight that is expected: v3.5.2 contains #26917, so the 401s do reach `requests.onError` now, but without #28807's guard each one reassigns `window.location.href` and cancels the previous in-flight navigation, so the browser never actually reaches the IdP.

I've asked about a cherry-pick on the PR itself (#28807). #26917 was backported to 3.2/3.3/3.4, so there is precedent for this issue. I also checked that the patch applies cleanly to `release-3.5`, `release-3.4` and `release-3.3` — the context around both hunks is unchanged on all three, and none of them has the guard yet. Happy to open the cherry-pick PRs if a maintainer can label or greenlight it.
