### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by wiliiwin** [argoproj/argo-cd#2953]
The following configuration was performed according to the official documentation(https://argoproj.github.io/argo-cd/getting_started/):

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: argocd-server-ingress
  annotations:
    kubernetes.io/ingress.class: crs-nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  rules:
  - host: argocd.gril.com
     http:
       paths:
       -  backend:
            serviceName: argocd-server
            servicePort: 443

now，encounter a redirect loop or are getting a 307 response code.So I added nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"  according to the official documentation to the configuration above.

The web page can be opened normally,But I got the following error during argocd login command

`FATA[0008] rpc error: code = Internal desc = transport: received the unexpected content-type "text/plain; charset=utf-8"`

I don't know how to configure it to open the page normally and the argocd login command can log in normally.

**Comment by boukandouramhamed** [comment]
Same problem, any workaround ?

**Comment by mkryva** [comment]
Same problem!

**Comment by leandro-manifesto** [comment]
After searching for a while I found a solution that works in my case.
I'm using Traefik instead of Nginx, but I believe this can be used with any ingress controller.

The problem is that by default Argo-CD handles TLS termination itself and always redirects HTTP requests to HTTPS. Combine that with an ingress controller that also handles TLS termination and always communicates with the backend service with HTTP and you get Argo-CD's server always responding with a redirects to HTTPS.

So one of the solutions would be to disable HTTPS on Argo-CD, which you can do by using the `--insecure` flag on `argocd-server`.

This is actually documented here:
https://argoproj.github.io/argo-cd/operator-manual/ingress/#option-2-multiple-ingress-objects-and-hosts
Its just not exactly obvious.

It would be nice if there was a page with command line flags for the server somewhere in the docs.

**Comment by georgepaoli** [comment]
Using NGINX ingress, send --insecure arg for container of argocd-server Deployment. It works for me.

`spec:
  containers:
  - command:
    - argocd-server
    - --staticassets
    - /shared/app
    - --insecure`

Help: https://argoproj.github.io/argo-cd/operator-manual/ingress/

**Comment by chrkaatz** [comment]
Somehow I ran into the same issue with a 308 redirect. I added the --insecure arg but no change so far. Any ideas?

**Comment by brianlmoon** [comment]
Nginx and other reverse proxies send the header [X-Forwarded-Proto](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto) to indicate that TLS is being handled by the proxy. This could be checked in addition to checking the secure setting in the [useSecure](https://github.com/argoproj/argo-cd/blob/89ee234634c10312d2fcb74c30e9d590fe01d4ff/server/server.go#L452) function. I have yet to venture into writing Go, so I am not sure of how that is done exactly. Maybe I will give it a shot.

**Comment by abdennour** [comment]
For my case, i have AWS ELB where the SSL is offloaded, then ingress receives on port 80, then forward to argocd-server service on insecure port (80).

I fixed the issue of too-many-redirects by implementing the above solution: 

```yaml
spec:
  containers:
  - command:
    - argocd-server
    - --staticassets
    - /shared/app
    - --insecure # <-- this thing needs to be added
```

**Comment by abhinavkhanna-sf** [comment]
> Using NGINX ingress, send --insecure arg for container of argocd-server Deployment. It works for me.
> 
> ```yaml
> spec:
>   containers:
>   - command:
>     - argocd-server
>     - --staticassets
>     - /shared/app
>     - --insecure
> ```
> 
> Help: https://argoproj.github.io/argo-cd/operator-manual/ingress/

is there a way to add it if I am deploying using Helm?

**Comment by delucca** [comment]
I was struggling with this issue for ours, and finally found this thread.

@georgepaoli suggesiton worked. Adding `--insecure` fixed the issue. I suggest adding this to [Argo's Traefik docs](https://argoproj.github.io/argo-cd/operator-manual/ingress/#ingressroute-crd) while the issue persists.

**Comment by corestackdev** [comment]
Spent half a day with ingress settings only to figure out this small piece of information missing. Thanks @leandro-manifesto

**Comment by ams0** [comment]
Thanks for this, I wrote a little patch [here](https://github.com/ams0/argocd-azure-k3s-traefik/blob/main/patch.yaml) and the IngressRoute CRD I use [here](https://github.com/ams0/argocd-azure-k3s-traefik). I wrote an article about all of this and more [here](https://medium.com/cooking-with-azure/managing-multiple-clusters-with-argocd-in-azure-k3s-secured-w-traefik-lets-encrypt-2de7daabbefa).

**Comment by nandeeshb09** [comment]
@leandro-manifesto ,

Is it safer to use in production also? --insecure?

**Comment by leandro-manifesto** [comment]
Its not ideal, but it works.
The Ingress resource already handles TLS termination before reaching ArgoCD and if the nodes aren't publicly accessible there _shouldn't_ be problems afaik.

**Comment by wlawton** [comment]
I was still getting a 308 response back from nginx-ingress-controller even after setting the argocd-server insecure flag. nginx logged:

W0608 15:05:42.385812       6 controller.go:1206] Unexpected error validating SSL certificate "argocd/argocd-secret" for server "argocd-ui.x.x.com": x509: certificate is valid for localhost, argocd-server, argocd-server.argocd, argocd-server.argocd.svc, argocd-server.argocd.svc.cluster.local, not argocd-ui.x.x.com 

...where argocd-ui.x.x.com (redacted) is the dns name i chose for the aws nlb in front of nginx.
I removed the tls section of the argocd ingress yaml i.e.
 # tls:
 # - hosts:
 #   - argocd-ui.x.x.com 
 #   secretName: argocd-secret # do not change, this is provided by Argo CD
And following this I could access the UI using argocd-ui.x.x.com with no apparent issues. Not sure if I was meant to set argocd-ui.x.x.com as the tls host nor not, but the argocd docs suggest this is what you are meant to do i.e. they use argocd.example.com as their example which isn't in compatible with their default tls.crt either.

**Comment by suharevA** [comment]
cluster rancher
added in container and works
 - command:
    - argocd-server
    - --staticassets
    - / shared / app
    - --insecure # <- this thing needs to be added

**Comment by Syntax3rror404** [comment]
i also have this problem

**Comment by atrakic** [comment]
This works for me: 
```
$ NS=argocd
$  kubectl -n "$NS" patch deployment argocd-server --type json \
    -p='[ { "op": "replace", "path":"/spec/template/spec/containers/0/command","value": ["argocd-server","--staticassets","/shared/app","--insecure"] }]
```

**Comment by kxw9298** [comment]
> This works for me:
> 
> ```
> $ NS=argocd
> $  kubectl -n "$NS" patch deployment argocd-server --type json \
>     -p='[ { "op": "replace", "path":"/spec/template/spec/containers/0/command","value": ["argocd-server","--staticassets","/shared/app","--insecure"] }]
> ```

also works with me

**Comment by chtime** [comment]
I encountered the same error and found that when installing ArgoCD, one can either add the `--insecure` flag (as written above) or you can update the ConfigMap to populate the environment variables used by `argo-server`  (only the `data` object is new): 

```
[snip]
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cmd-params-cm
data:
  server.insecure: "true"
---
[snip]
 ```

Unfortunately this is still a change in the original installation file, thus you need to download and change it before `kubectl apply`ing it. It doesn't seem to be possible to define the ConfigMap before applying the install file since kubectl will overwrite the ConfigMap - at least in my experiment and with my limited knowledge about k8s.

**Comment by penglei** [comment]
I use passthrough mode in my Ingress, but I forget the annotation `nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"` and it resulted in nginx-ingress-controller generating `proxy_pass http://upstream_balancer` in the nginx.conf. After I added this annotation, the server stopped responsing 307.

**Comment by kszpakowski** [comment]
Following configuration works without further modifications

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-http-ingress
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: argocd-server
            port: 
              name: https
    host: argocd.example.com
  tls:
  - hosts:
    - argocd.example.com
    secretName: argocd-secret
```

**Comment by gsthamu** [comment]
> I encountered the same error and found that when installing ArgoCD, one can either add the `--insecure` flag (as written above) or you can update the ConfigMap to populate the environment variables used by `argo-server` (only the `data` object is new):
> 
> ```yaml
> # [snip]
> ---
> apiVersion: v1
> kind: ConfigMap
> metadata:
>   labels:
>     app.kubernetes.io/name: argocd-cmd-params-cm
>     app.kubernetes.io/part-of: argocd
>   name: argocd-cmd-params-cm
> data:
>   server.insecure: "true"
> ---
> # [snip]
> ```
> 
> Unfortunately you can't apply this after running the installer since it will have no effect on the already deployed service, and applying it before the install will have the install overwrite it.
> 
> -- edit: While the install yaml file will overwrite this definition, you can put this in a separate file and apply it after the install yaml and _then_ force a restart of the argocd-server deployment, like so:
> 
>     0. Put the contents shown above in a file called e.g. argocd-config.yaml
> 
>     1. `kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml`
> 
>     2. `kubectl apply -n argocd -f argocd-config.yaml`
> 
>     3. `kubectl scale -n argocd deployment/argocd-server --replicas=0 && kubectl scale -n argocd deployment/argocd-server --replicas=1`

> ```yaml
> apiVersion: networking.k8s.io/v1
> kind: Ingress
> metadata:
>   name: argocd-server-http-ingress
>   namespace: argocd
>   annotations:
>     kubernetes.io/ingress.class: "nginx"
>     nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
>     nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
> spec:
>   rules:
>   - http:
>       paths:
>       - pathType: Prefix
>         path: /
>         backend:
>           service:
>             name: argocd-server
>             port: 
>               name: http
>     host: argocd.example.com
>   tls:
>   - hosts:
>     - argocd.example.com
>     secretName: argocd-secret
> `
> I have changed the above ingress setting. Now, no looping for me

**Comment by dadav** [comment]
This fixed my redirection issue on openshift: https://github.com/redhat-developer/gitops-operator/issues/277#issuecomment-1044881417

**Comment by wadexu007** [comment]
Fixed via this 

`apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx

    # If you encounter a redirect loop or are getting a 307 response code 
    # then you need to force the nginx ingress to connect to the backend using HTTPS.
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS" # argocd backend using HTTPS`

**Comment by begemotik** [comment]
> Nginx and other reverse proxies send the header [X-Forwarded-Proto](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto) to indicate that TLS is being handled by the proxy. This could be checked in addition to checking the secure setting in the [useSecure](https://github.com/argoproj/argo-cd/blob/89ee234634c10312d2fcb74c30e9d590fe01d4ff/server/server.go#L452) function. I have yet to venture into writing Go, so I am not sure of how that is done exactly. Maybe I will give it a shot.

Did you have a possibility to implement it?

**Comment by robozb** [comment]
> Following configuration works without further modifications
> 
> ```yaml
> apiVersion: networking.k8s.io/v1
> kind: Ingress
> metadata:
>   name: argocd-server-http-ingress
>   namespace: argocd
>   annotations:
>     kubernetes.io/ingress.class: "nginx"
>     nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
>     nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
> spec:
>   rules:
>   - http:
>       paths:
>       - pathType: Prefix
>         path: /
>         backend:
>           service:
>             name: argocd-server
>             port: 
>               name: https
>     host: argocd.example.com
>   tls:
>   - hosts:
>     - argocd.example.com
>     secretName: argocd-secret
> ```

Beautiful, this is worked at me, the main rows:

nginx.ingress.kubernetes.io/backend-protocol: HTTPS
name: https

**Comment by ramdisk-ott** [comment]
> Thank you @kszpakowski
> 
> > Following configuration works without further modifications
> > ```yaml
> > apiVersion: networking.k8s.io/v1
> > kind: Ingress
> > metadata:
> >   name: argocd-server-http-ingress
> >   namespace: argocd
> >   annotations:
> >     kubernetes.io/ingress.class: "nginx"
> >     nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
> >     nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
> > spec:
> >   rules:
> >   - http:
> >       paths:
> >       - pathType: Prefix
> >         path: /
> >         backend:
> >           service:
> >             name: argocd-server
> >             port: 
> >               name: https
> >     host: argocd.example.com
> >   tls:
> >   - hosts:
> >     - argocd.example.com
> >     secretName: argocd-secret
> > ```
> 
> Beautiful, this worked for me too, the main lines:
> 
> nginx.ingress.kubernetes.io/backend-protocol: HTTPS name: https

its working thanks

**Comment by thatsankur** [comment]
> > I encountered the same error and found that when installing ArgoCD, one can either add the `--insecure` flag (as written above) or you can update the ConfigMap to populate the environment variables used by `argo-server` (only the `data` object is new):
> > ```yaml
> > # [snip]
> > ---
> > apiVersion: v1
> > kind: ConfigMap
> > metadata:
> >   labels:
> >     app.kubernetes.io/name: argocd-cmd-params-cm
> >     app.kubernetes.io/part-of: argocd
> >   name: argocd-cmd-params-cm
> > data:
> >   server.insecure: "true"
> > ---
> > # [snip]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Unfortunately you can't apply this after running the installer since it will have no effect on the already deployed service, and applying it before the install will have the install overwrite it.
> > -- edit: While the install yaml file will overwrite this definition, you can put this in a separate file and apply it after the install yaml and _then_ force a restart of the argocd-server deployment, like so:
> > ```
> > 0. Put the contents shown above in a file called e.g. argocd-config.yaml
> > 
> > 1. `kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml`
> > 
> > 2. `kubectl apply -n argocd -f argocd-config.yaml`
> > 
> > 3. `kubectl scale -n argocd deployment/argocd-server --replicas=0 && kubectl scale -n argocd deployment/argocd-server --replicas=1`
> > ```
> 
> > ```yaml
> > apiVersion: networking.k8s.io/v1
> > kind: Ingress
> > metadata:
> >   name: argocd-server-http-ingress
> >   namespace: argocd
> >   annotations:
> >     kubernetes.io/ingress.class: "nginx"
> >     nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
> >     nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
> > spec:
> >   rules:
> >   - http:
> >       paths:
> >       - pathType: Prefix
> >         path: /
> >         backend:
> >           service:
> >             name: argocd-server
> >             port: 
> >               name: http
> >     host: argocd.example.com
> >   tls:
> >   - hosts:
> >     - argocd.example.com
> >     secretName: argocd-secret
> > `
> > I have changed the above ingress setting. Now, no looping for me
> > ```
These three annotations did the magic for me ! Thanks 
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"

**Comment by downvoteit** [comment]
On a newer version of Bitnami ArgoCD (Chart argo-cd-4.4.0, application 2.5.5) I just run this:

```bash
k patch $(k get deployment -l app.kubernetes.io/component=server -oname) --type=json \
  -p='[{
    "op" : "add" ,
    "path" : "/spec/template/spec/containers/0/args/-" ,
    "value" : "--insecure"
  }]'

k get deployment -l app.kubernetes.io/component=server -ojsonpath='{.items[0].spec.template.spec.containers[0].args}' | jq  
```

**Comment by Naradsingh** [comment]
I used this in aanotations and it worked for me 

kubernetes.io/ingress.class: "nginx"
nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
nginx.ingress.kubernetes.io/backend-protocol: "HTTP"

**Comment by aberenshtein** [comment]
After many hours of debugging....
We are running argocd with `--insecure` and with ingress with on special annotations.
Argo is installed with helm on an EKS cluster.
The problem for use was the argocd cli version.
With 2.3.12:
`argocd login <domain>:<port> --grpc-web` works
WIth 2.5.9:
`argocd login <domain>:<port> --grpc-web --skip-test-tls` works
This is what saved me https://github.com/argoproj/argo-cd/issues/9679

**Comment by dev-sareno** [comment]
Using Helm, I managed to set the `--insecure` [flag](https://artifacthub.io/packages/helm/argo/argo-cd?modal=values&path=configs.params.%22server\.insecure%22) using the following values (`values.yaml`)
```yaml
server:
  ingress:
    enabled: "true"
    ingressClassName: "nginx"
configs:
  params:
    server.insecure: "true"
```

```shell
$ helm install argocd -n argocd argo/argo-cd -f values.yaml
```

**Comment by AximPushpa** [comment]
For argocd 2.7.4 version, set **server.insecure: "true"** in the **argocd-cmd-params-cm** ConfigMap. 

apiVersion: v1
data:
  redis.server: argocd-redis-ha-haproxy:6379
  **server.insecure: "true"**

Also edit the env optional value of **ARGOCD_SERVER_INSECURE** to **false** in **argocd-server** deployment.

- name: ARGOCD_SERVER_INSECURE
          valueFrom:
            configMapKeyRef:
              key: server.insecure
              name: argocd-cmd-params-cm
              optional: **false**

**Comment by VesperDev** [comment]
The solution for me
Version ArgoCD: v2.7.6+00c914a.dirty

![image](https://github.com/argoproj/argo-cd/assets/14016458/023bf2d4-cf01-4647-a06b-58a24dfa0f5d)

**Comment by mztnnrt** [comment]
Thanks to all https://github.com/argoproj/argo-cd/issues/2953#issuecomment-932190859 we also resolved our dns about local environment. argocd-secret seems to has default `tls.crt` and `tls.key`


<details>
<summary>argocd-secret</summary>

```
┌─────────────────────────────────────────────────────────────────── Describe(argocd/argocd-secret) ───────────────────────────────────────────────────────────────────┐
│ Name:         argocd-secret                                                                                                                                          │
│ Namespace:    argocd                                                                                                                                                 │
│ Labels:       app.kubernetes.io/name=argocd-secret                                                                                                                   │
│               app.kubernetes.io/part-of=argocd                                                                                                                       │
│ Annotations:  <none>                                                                                                                                                 │
│                                                                                                                                                                      │
│ Type:  Opaque                                                                                                                                                        │
│                                                                                                                                                                      │
│ Data                                                                                                                                                                 │
│ ====                                                                                                                                                                 │
│ tls.crt:              1233 bytes                                                                                                                                     │
│ tls.key:              1679 bytes                                                                                                                                     │
│ admin.password:       60 bytes                                                                                                                                       │
│ admin.passwordMtime:  20 bytes                                                                                                                                       │
│ server.secretkey:     44 bytes                                                                                                                                       │
│                                                                                                                                                                      │
│                                                                                                                                                                      │
│                                                                                                                                                                      │
│                                                                                                                                                                      │
│                                                                                                                                                                      │
│                                                                                                                                                                      │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

</details>

**Comment by VitorNilson** [comment]
I have followed the quickstart of ArgoCD documentation https://argo-cd.readthedocs.io/en/stable/#quick-start

The only difference is that I deployed in `argo-cd` namespace instead of `argocd`.

Now, I'm having issues to access this application through my Nginx ingress. It's throwing `ERR_TOO_MANY_REDIRECTS` on the browser and in the logs of Nginx:

```
172.71.6.219 - - [05/Jul/2023:23:01:54 +0000] "GET / HTTP/1.1" 308 164 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" 904 0.000 [argo-cd-argocd-server-http] [] - - - - ba62103809faf5da2f9e2661a2c1f50b
172.71.6.219 - - [05/Jul/2023:23:01:54 +0000] "GET / HTTP/1.1" 308 164 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" 904 0.000 [argo-cd-argocd-server-http] [] - - - - 0d05a1f48fdceb5d4c557884c3850074
172.71.6.219 - - [05/Jul/2023:23:01:55 +0000] "GET / HTTP/1.1" 308 164 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" 904 0.000 [argo-cd-argocd-server-http] [] - - - - d724f5d890ce91e713c768db2126d44f
.......... more and more
```

On the ArgoCD server, I've setted the `server.insecure:"true"` on `argocd-cmd-params-cm`. 

This is my Ingress:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argo-cd
  annotations:
    cert-manager.io/issuer: prod-issuer
    cert-manager.io/issuer-kind: OriginIssuer
    cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  tls:
  - hosts:
    - '*.my_site.dev'
    secretName: argocd-secret
  ingressClassName: nginx
  rules:
  - host: argocd.my_site.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              name: http
```

I've tried to set  `server.insecure:"false"` and my Ingress like this:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argo-cd
  annotations:
    cert-manager.io/issuer: prod-issuer
    cert-manager.io/issuer-kind: OriginIssuer
    cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  tls:
  - hosts:
    - '*.my_site.dev'
    secretName: argocd-secret
  ingressClassName: nginx
  rules:
  - host: argocd.my_site.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              name: https
```

I've tried even to use another secret to store my TLS given that I'm using cloudflare certificates.

PS: Of course I've deleted the argo-cd-server between the changes on the ConfigMap.

Nothing is working.

Do you guys have any idea how to solve this?

**Comment by Erokos** [comment]
I have a similar case as @abdennour , of a load balancer that terminates TLS and behind it a kubernetes ingress nginx controller that is used for routing. The thing I'm trying to do is use paths  e.g. `example.com/argocd` instead of subdomains such as `argocd.example.com` to access the server, is this possible?

**Comment by kszpakowski** [comment]
Documentation suggests disabling the TLS on the Argo server side using deployment flags - https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#traefik-v22. Personally I don't think this is a good idea to use the server without the encryption, as you could get sensitive data by running tcpdump.

**Comment by zeyad-sitech** [comment]
## Helm Deployment [Nginx Ingress]
 I struggled with this issue for 3 days, the only thing worked for me was the following:

1. Change the following in `values.yaml`
```
server.insecure: false  -> server.insecure: true
```
2.  Make sure to use the following annotations:
```yaml
  ingress:
    # -- Enable an ingress resource for the Argo CD server
    enabled: true
    # -- Additional ingress annotations
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    # -- Additional ingress labels
    labels: {}
    # -- Defines which ingress controller will implement the resource
    ingressClassName: "nginx"

    # -- List of ingress hosts
    ## Argo Ingress.
    ## Hostnames must be provided if Ingress is enabled.
    ## Secrets must be manually created in the namespace
    hosts:
       - argocd.example.com

    # -- List of ingress paths
    paths:
      - /
    # -- Ingress path type. One of `Exact`, `Prefix` or `ImplementationSpecific`
    pathType: Prefix
    # -- Additional ingress paths
    extraPaths: []
      # - path: /*
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: ssl-redirect
      #       port:
      #         name: use-annotation

    # -- Ingress TLS configuration
    tls:
      - secretName: <Secret>
        hosts:
          - argocd.example.com

    # -- Uses 'server.service.servicePortHttps' instead 'server.service.servicePortHttp'
    https: false
```

**Comment by cmoulliard** [comment]
I succeeded on a kind cluster where ingress nginx controller is deployed using this `values.yml` config
```
server:
  ingress:
    # -- Enable an ingress resource for the Argo CD server
    enabled: true
    # -- Additional ingress annotations
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"

    # -- Defines which ingress controller will implement the resource
    ingressClassName: "nginx"

    # -- List of ingress hosts
    hosts:
      - argocd-ui.127.0.0.1.nip.io

    # -- Ingress TLS configuration
    #tls:
    #  - secretName: argocd-secret
    #    hosts:
    #    - argocd-ui.127.0.0.1.nip.io

    # -- Uses 'server.service.servicePortHttps' instead 'server.service.servicePortHttp'
    https: true
```
and
```
helm install argocd argo/argo-cd -n argocd --create-namespace=true -f values.yml
```

**Comment by christianh814** [comment]
I believe the original issue was solved by @kszpakowski's post [#issuecomment-93219085](https://github.com/argoproj/argo-cd/issues/2953#issuecomment-932190859). It's also [documented](https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#option-2-ssl-termination-at-ingress-controller). Therefore I'm closing this issue.

Please open another issue or ping us on Slack if you are still experiencing issues.

**Comment by vikas027** [comment]
On v2.9.3, this worked for me with an nginx controller

```bash
k patch $(k get deployment -l app.kubernetes.io/component=server -oname) --type=json \
  -p='[{
    "op" : "add" ,
    "path" : "/spec/template/spec/containers/0/args/-" ,
    "value" : "--insecure"
  }]'
```

```yaml
---
# NOTE: I did not had to use any special annotatations
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd
  namespace: argocd
spec:
  ingressClassName: nginx
  rules:
    - host: argocd.example.com
      http:
        paths:
          - backend:
              service:
                name: argocd-server
                port:
                  name: http
            path: /
            pathType: Prefix
```

**Comment by bloomingFlower** [comment]
Thanks to this thread, I was able to resolve it well. it's also necessary in Istio.

**Comment by gabriel-suela** [comment]
fixed this issue adding `nginx.ingress.kubernetes.io/rewrite-target: / ` to the ingress annotations.

**Comment by cooervo** [comment]
just adding in values yaml of argocd helm chart fixed it for me 

```
configs:
  params:
    server.insecure: "true"
```

then I ran `kubectl -n argocd rollout restart deploy` to restart all deployments in argocd namespace and it works 👍🏽

**Comment by escummy** [comment]
I was exploring solutions to set the `--insecure` flag to `true` for the deployment and configmap files mentioned above. However, with the current ArgoCD Helm chart `version 7.1.2` (and newer versions), the configuration has slightly changed:

- The `server.insecure` option is already set to `true` in the deployment YAML file. 

```
kubectl get deployment argo-cd-argocd-server -n argocd -o yaml
```

![deployment-argocd](https://github.com/argoproj/argo-cd/assets/90976678/62bc14d1-3cf1-4377-92d0-010b41dffc90)

- So you need simply apply this `true` value in the configmap new location file as below (by default it is set to `false`.

```
kubectl get configmap argocd-cmd-params-cm -n argocd -o yaml
```

![cinfigmap-argocd](https://github.com/argoproj/argo-cd/assets/90976678/1ab5c67c-6808-4a74-ac73-d649b36c07cc)

- Finally, use a rollout to restart deployment and your ingress should work properly.

```
 kubectl rollout restart deployment argo-cd-argocd-server -n argocd
```
I hope this helps!

**Comment by dmuiX** [comment]
Stumbling into 307 with a gateway-api tlsroute. Is there some possible way to solve this?
Already enabled server.insecure: "true" and passthrough in gateway is enabled as well...

**Comment by minhnd410** [comment]
This is still an issue for me

Env:
- Argocd: v2.12.3
- Ingress-nginx: 1.11.2

I followed the section [kubernetes/ingress-nginx](https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#kubernetesingress-nginx), and tried the two approaches it mentioned `SSL-Passthrough` and `SSL Termination at Ingress Controller` but neither of these worked.

** Apprach: SSL-Passthrough
1. add `--enable-ssl-passthrough` to nginx-ingress-controller
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  template:
    spec:
      containers:
          ...
          args: 
            - /nginx-ingress-controller
            - ...
            - --enable-ssl-passthrough
```
2. Ingress config as below
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server
  namespace: argocd
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  rules:
    - host: argocd.myapp.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 443
  tls:
    - hosts:
      - argocd.myapp.com
      secretName: argocd-server-tls
```

**Comment by myysophia** [comment]
> 3\. kubectl scale -n argocd deployment/argocd-server --replicas=0 && kubectl scale -n argocd deployment/argocd-server --replicas=1

Error: secret "argocd-redis" not found
