### ISSUE TITLE
Custom healthchecks not executed when custom resource is created

### ISSUE THREAD

**Issue by stujb** [argoproj/argo-cd#3744]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [X] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [X ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

Custom lua healthchecks configured in argocd-cm resource.customizations do not run at resource creation time. A restart of the argocd-application-controller pod is required for the healthchecks to be executed and the resource to move from a Missing/OutOfSync state to Healthy/Synced. After waiting 10 minutes from pod restart the creation of further custom resources exhibits the same issue and another restart of the argocd-application-controller is required.

**To Reproduce**

- Install cert-manager and/or sealedsecrets into k8s cluster
- Update resouce.customizations in argocd-cm configmap to contain healthchecks for customresource including debug print statements showing in argocd-application-controller pod logs when custom healthchecks have been executed
- Wait 10 minutes
- Configure a resource of the type Certificate or SealedSecret in the git repo being synced from
- Observe status of custom resources - they remain Missing/OutOfSync
- Check pod logs of argocd-application-controller - there will be no debug print statements indicating healthcheck scripts have not been executed
- Restart argocd-application-controller pod
- Custom Resources that were not previously syncing are now in Healthy/Synced state
- Pod logs from restarted argocd-application-controller show healthcheck scripts have been executed

**Expected behavior**

Healthchecks should be executed on new resources when they are created without having to restart argocd-application-controller pod 

**Screenshots**

N/A - all details shown in attached log

**Version**

```shell
$ argocd version
argocd: v1.5.6+f46333e
  BuildDate: 2020-06-02T18:40:52Z
  GitCommit: f46333ea82ad2157baffc5a8cf02a86720d4bad4
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.5.4+36bade7
  BuildDate: 2020-05-05T19:01:57Z
  GitCommit: 36bade7a2d7b69d1c0b0c4d41191f792a847d61c
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.5.4 GitCommit:3af514fa9f85430f0c1557c4a0291e62112ab026 BuildDate:2020-01-11T03:12:59Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.14.0
```

**Logs**

Logs and application status from initial sync of custom resources
```
Logs when applying the resources requiring custom healthchecks
time="2020-06-10T06:14:32Z" level=info msg="Refreshing app status (comparison expired. reconciledAt: 2020-06-10 06:11:32 +0000 UTC, expiry: 3m0s), level (2)" application=health
time="2020-06-10T06:14:32Z" level=info msg="Refreshing app status (comparison expired. reconciledAt: 2020-06-10 06:11:32 +0000 UTC, expiry: 3m0s), level (2)" application=argocd-app-of-apps
time="2020-06-10T06:14:32Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: bridge)" application=health
time="2020-06-10T06:14:32Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: argocd)" application=argocd-app-of-apps
time="2020-06-10T06:14:34Z" level=info msg="getRepoObjs stats" application=health build_options_ms=0 helm_ms=0 manifests_ms=2158 plugins_ms=0 repo_ms=0 time_ms=2158 unmarshal_ms=0 version_ms=0
time="2020-06-10T06:14:34Z" level=info msg="Skipping auto-sync: application status is Unknown" application=argocd-app-of-apps
time="2020-06-10T06:14:34Z" level=info msg="Initiated automated sync to 'd538b66198c18e4d4363ba6b92b98e171747861f'" application=health dest-namespace=bridge dest-server="https://kubernetes.default.svc" reason=OperationStarted type=Normal
time="2020-06-10T06:14:34Z" level=info msg="Update successful" application=argocd-app-of-apps
time="2020-06-10T06:14:34Z" level=info msg="Reconciliation completed" application=argocd-app-of-apps dedup_ms=0 dest-namespace=argocd dest-server="https://kubernetes.default.svc" diff_ms=0 fields.level=2 git_ms=2176 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=2188
time="2020-06-10T06:14:34Z" level=info msg="Initiated automated sync to 'd538b66198c18e4d4363ba6b92b98e171747861f'" application=health
time="2020-06-10T06:14:34Z" level=info msg="Updated sync status: Synced -> OutOfSync" application=health dest-namespace=bridge dest-server="https://kubernetes.default.svc" reason=ResourceUpdated type=Normal
time="2020-06-10T06:14:34Z" level=info msg="updated 'health' operation (phase: Running)"
time="2020-06-10T06:14:34Z" level=info msg="Initialized new operation: {&SyncOperation{Revision:d538b66198c18e4d4363ba6b92b98e171747861f,Prune:true,DryRun:false,SyncStrategy:nil,Resources:[]SyncOperationResource{},Source:nil,Manifests:[],SyncOptions:[],} { true}}" application=health
time="2020-06-10T06:14:34Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: bridge)" application=health
time="2020-06-10T06:14:34Z" level=info msg="Updated health status: Healthy -> Missing" application=health dest-namespace=bridge dest-server="https://kubernetes.default.svc" reason=ResourceUpdated type=Normal
time="2020-06-10T06:14:34Z" level=info msg="getRepoObjs stats" application=health build_options_ms=0 helm_ms=0 manifests_ms=8 plugins_ms=0 repo_ms=0 time_ms=8 unmarshal_ms=0 version_ms=0
time="2020-06-10T06:14:34Z" level=info msg=syncing application=health isSelectiveSync=false skipHooks=false started=false syncId=00001-UVDzL
time="2020-06-10T06:14:34Z" level=info msg=tasks application=health isSelectiveSync=false syncId=00001-UVDzL tasks="[Sync/0 resource /ConfigMap:bridge/seed-cm obj->nil (,,), Sync/0 resource /Service:bridge/test-healthcheck-service nil->obj (,,), Sync/0 resource cert-manager.io/Certificate:bridge/test-certificate-v1 nil->obj (,,), Sync/0 resource bitnami.com/SealedSecret:bridge/test-healthcheck-secret nil->obj (,,)]"
time="2020-06-10T06:14:34Z" level=info msg="Applying resource Service/test-healthcheck-service in cluster: https://172.30.0.1:443, namespace: bridge"
time="2020-06-10T06:14:34Z" level=info msg="Update successful" application=health
time="2020-06-10T06:14:34Z" level=info msg="Reconciliation completed" application=health dedup_ms=0 dest-namespace=bridge dest-server="https://kubernetes.default.svc" diff_ms=1 fields.level=2 git_ms=2159 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=2223
time="2020-06-10T06:14:34Z" level=info msg="Applying resource Certificate/test-certificate-v1 in cluster: https://172.30.0.1:443, namespace: bridge"
time="2020-06-10T06:14:34Z" level=info msg="Applying resource SealedSecret/test-healthcheck-secret in cluster: https://172.30.0.1:443, namespace: bridge"
time="2020-06-10T06:14:34Z" level=info msg="Updating operation state. phase: Running -> Running, message: '' -> 'one or more tasks are running'" application=health syncId=00001-UVDzL
time="2020-06-10T06:14:34Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=health
time="2020-06-10T06:14:34Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: bridge)" application=health
time="2020-06-10T06:14:34Z" level=info msg="adding resource result, status: 'Pruned', phase: 'Succeeded', message: 'pruned'" application=health kind=ConfigMap name=seed-cm namespace=bridge phase=Sync syncId=00001-UVDzL
time="2020-06-10T06:14:34Z" level=info msg="Applying resource Service/test-healthcheck-service in cluster: https://172.30.0.1:443, namespace: bridge"
time="2020-06-10T06:14:34Z" level=info msg="getRepoObjs stats" application=health build_options_ms=0 helm_ms=0 manifests_ms=6 plugins_ms=0 repo_ms=0 time_ms=6 unmarshal_ms=0 version_ms=0
time="2020-06-10T06:14:34Z" level=info msg="Skipping auto-sync: another operation is in progress" application=health
time="2020-06-10T06:14:35Z" level=info msg="Update successful" application=health
time="2020-06-10T06:14:35Z" level=info msg="Reconciliation completed" application=health dedup_ms=0 dest-namespace=bridge dest-server="https://kubernetes.default.svc" diff_ms=0 fields.level=1 git_ms=6 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=30
time="2020-06-10T06:14:35Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=health
time="2020-06-10T06:14:35Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: bridge)" application=health
time="2020-06-10T06:14:35Z" level=info msg="getRepoObjs stats" application=health build_options_ms=0 helm_ms=0 manifests_ms=6 plugins_ms=0 repo_ms=0 time_ms=6 unmarshal_ms=0 version_ms=0
time="2020-06-10T06:14:35Z" level=info msg="Skipping auto-sync: another operation is in progress" application=health
time="2020-06-10T06:14:35Z" level=info msg="Update successful" application=health
time="2020-06-10T06:14:35Z" level=info msg="Reconciliation completed" application=health dedup_ms=0 dest-namespace=bridge dest-server="https://kubernetes.default.svc" diff_ms=0 fields.level=1 git_ms=6 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=36
time="2020-06-10T06:14:35Z" level=info msg="adding resource result, status: 'Synced', phase: 'Running', message: 'service/test-healthcheck-service created'" application=health kind=Service name=test-healthcheck-service namespace=bridge phase=Sync syncId=00001-UVDzL
time="2020-06-10T06:14:35Z" level=info msg="Applying resource Certificate/test-certificate-v1 in cluster: https://172.30.0.1:443, namespace: bridge"
time="2020-06-10T06:14:35Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=health
time="2020-06-10T06:14:35Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: bridge)" application=health
time="2020-06-10T06:14:35Z" level=info msg="getRepoObjs stats" application=health build_options_ms=0 helm_ms=0 manifests_ms=6 plugins_ms=0 repo_ms=0 time_ms=6 unmarshal_ms=0 version_ms=0
time="2020-06-10T06:14:35Z" level=info msg="Skipping auto-sync: another operation is in progress" application=health
time="2020-06-10T06:14:35Z" level=info msg="Update successful" application=health
time="2020-06-10T06:14:35Z" level=info msg="Reconciliation completed" application=health dedup_ms=0 dest-namespace=bridge dest-server="https://kubernetes.default.svc" diff_ms=1 fields.level=1 git_ms=6 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=25
time="2020-06-10T06:14:35Z" level=info msg="Refreshing app status (controller refresh requested), level (0)" application=health
time="2020-06-10T06:14:35Z" level=info msg="No status changes. Skipping patch" application=health
time="2020-06-10T06:14:35Z" level=info msg="Reconciliation completed" application=health dest-namespace=bridge dest-server="https://kubernetes.default.svc" fields.level=0 time_ms=2
time="2020-06-10T06:14:35Z" level=info msg="adding resource result, status: 'Synced', phase: 'Running', message: 'certificate.cert-manager.io/test-certificate-v1 created'" application=health kind=Certificate name=test-certificate-v1 namespace=bridge phase=Sync syncId=00001-UVDzL
time="2020-06-10T06:14:35Z" level=info msg="Applying resource SealedSecret/test-healthcheck-secret in cluster: https://172.30.0.1:443, namespace: bridge"
time="2020-06-10T06:14:35Z" level=info msg="adding resource result, status: 'Synced', phase: 'Running', message: 'sealedsecret.bitnami.com/test-healthcheck-secret created'" application=health kind=SealedSecret name=test-healthcheck-secret namespace=bridge phase=Sync syncId=00001-UVDzL
time="2020-06-10T06:14:35Z" level=info msg="Updating operation state. phase: Running -> Succeeded, message: 'one or more tasks are running' -> 'successfully synced (all tasks run)'" application=health syncId=00001-UVDzL
time="2020-06-10T06:14:35Z" level=info msg="sync/terminate complete" application=health duration=1.112102672s syncId=00001-UVDzL
time="2020-06-10T06:14:35Z" level=info msg="updated 'health' operation (phase: Succeeded)"
time="2020-06-10T06:14:35Z" level=info msg="Sync operation to d538b66198c18e4d4363ba6b92b98e171747861f succeeded" application=health dest-namespace=bridge dest-server="https://kubernetes.default.svc" reason=OperationCompleted type=Normal
time="2020-06-10T06:14:35Z" level=info msg="Refreshing app status (controller refresh requested), level (2)" application=health
time="2020-06-10T06:14:35Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: bridge)" application=health
time="2020-06-10T06:14:36Z" level=info msg="getRepoObjs stats" application=health build_options_ms=0 helm_ms=0 manifests_ms=1345 plugins_ms=0 repo_ms=0 time_ms=1346 unmarshal_ms=0 version_ms=0
time="2020-06-10T06:14:36Z" level=info msg="Skipping auto-sync: already attempted sync to d538b66198c18e4d4363ba6b92b98e171747861f with timeout 5s (retrying in 3.049664482s)" application=health
time="2020-06-10T06:14:36Z" level=info msg="Update successful" application=health
time="2020-06-10T06:14:36Z" level=info msg="Reconciliation completed" application=health dedup_ms=0 dest-namespace=bridge dest-server="https://kubernetes.default.svc" diff_ms=1 fields.level=2 git_ms=1346 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=1370
time="2020-06-10T06:14:40Z" level=info msg="Refreshing app status (controller refresh requested), level (824656040800)" application=health
time="2020-06-10T06:14:40Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: bridge)" application=health
time="2020-06-10T06:14:40Z" level=info msg="getRepoObjs stats" application=health build_options_ms=0 helm_ms=0 manifests_ms=947 plugins_ms=0 repo_ms=0 time_ms=947 unmarshal_ms=0 version_ms=0
time="2020-06-10T06:14:40Z" level=info msg="Initiated automated sync to 'd538b66198c18e4d4363ba6b92b98e171747861f'" application=health dest-namespace=bridge dest-server="https://kubernetes.default.svc" reason=OperationStarted type=Normal
time="2020-06-10T06:14:40Z" level=info msg="Initiated automated sync to 'd538b66198c18e4d4363ba6b92b98e171747861f'" application=health
time="2020-06-10T06:14:40Z" level=info msg="updated 'health' operation (phase: Running)"
time="2020-06-10T06:14:40Z" level=info msg="Initialized new operation: {&SyncOperation{Revision:d538b66198c18e4d4363ba6b92b98e171747861f,Prune:true,DryRun:false,SyncStrategy:nil,Resources:[]SyncOperationResource{SyncOperationResource{Group:bitnami.com,Kind:SealedSecret,Name:test-healthcheck-secret,},SyncOperationResource{Group:cert-manager.io,Kind:Certificate,Name:test-certificate-v1,},},Source:nil,Manifests:[],SyncOptions:[],} { true}}" application=health
time="2020-06-10T06:14:40Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: bridge)" application=health
time="2020-06-10T06:14:40Z" level=info msg="getRepoObjs stats" application=health build_options_ms=0 helm_ms=0 manifests_ms=6 plugins_ms=0 repo_ms=0 time_ms=6 unmarshal_ms=0 version_ms=0
time="2020-06-10T06:14:40Z" level=info msg=syncing application=health isSelectiveSync=true skipHooks=true started=false syncId=00002-NLxKx
time="2020-06-10T06:14:40Z" level=info msg="Update successful" application=health
time="2020-06-10T06:14:40Z" level=info msg="Reconciliation completed" application=health dedup_ms=0 dest-namespace=bridge dest-server="https://kubernetes.default.svc" diff_ms=0 fields.level=824656040800 git_ms=947 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=994
time="2020-06-10T06:14:41Z" level=info msg=tasks application=health isSelectiveSync=true syncId=00002-NLxKx tasks="[Sync/0 resource cert-manager.io/Certificate:bridge/test-certificate-v1 nil->obj (,,), Sync/0 resource bitnami.com/SealedSecret:bridge/test-healthcheck-secret nil->obj (,,)]"
time="2020-06-10T06:14:41Z" level=info msg="Applying resource Certificate/test-certificate-v1 in cluster: https://172.30.0.1:443, namespace: bridge"
time="2020-06-10T06:14:41Z" level=info msg="Applying resource SealedSecret/test-healthcheck-secret in cluster: https://172.30.0.1:443, namespace: bridge"
time="2020-06-10T06:14:41Z" level=info msg="Updating operation state. phase: Running -> Running, message: '' -> 'one or more tasks are running'" application=health syncId=00002-NLxKx
time="2020-06-10T06:14:41Z" level=info msg="Applying resource Certificate/test-certificate-v1 in cluster: https://172.30.0.1:443, namespace: bridge"
time="2020-06-10T06:14:41Z" level=info msg="adding resource result, status: 'Synced', phase: 'Running', message: 'certificate.cert-manager.io/test-certificate-v1 unchanged'" application=health kind=Certificate name=test-certificate-v1 namespace=bridge phase=Sync syncId=00002-NLxKx
time="2020-06-10T06:14:41Z" level=info msg="Applying resource SealedSecret/test-healthcheck-secret in cluster: https://172.30.0.1:443, namespace: bridge"
time="2020-06-10T06:14:41Z" level=info msg="adding resource result, status: 'Synced', phase: 'Running', message: 'sealedsecret.bitnami.com/test-healthcheck-secret unchanged'" application=health kind=SealedSecret name=test-healthcheck-secret namespace=bridge phase=Sync syncId=00002-NLxKx
time="2020-06-10T06:14:41Z" level=info msg="Updating operation state. phase: Running -> Succeeded, message: 'one or more tasks are running' -> 'successfully synced (all tasks run)'" application=health syncId=00002-NLxKx
time="2020-06-10T06:14:41Z" level=info msg="sync/terminate complete" application=health duration=665.866613ms syncId=00002-NLxKx
time="2020-06-10T06:14:41Z" level=info msg="updated 'health' operation (phase: Succeeded)"
time="2020-06-10T06:14:41Z" level=info msg="Partial sync operation to d538b66198c18e4d4363ba6b92b98e171747861f succeeded" application=health dest-namespace=bridge dest-server="https://kubernetes.default.svc" reason=OperationCompleted type=Normal
time="2020-06-10T06:14:41Z" level=info msg="Refreshing app status (controller refresh requested), level (2)" application=health
time="2020-06-10T06:14:41Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: bridge)" application=health
time="2020-06-10T06:14:42Z" level=info msg="getRepoObjs stats" application=health build_options_ms=0 helm_ms=0 manifests_ms=953 plugins_ms=0 repo_ms=0 time_ms=953 unmarshal_ms=0 version_ms=0
time="2020-06-10T06:14:42Z" level=info msg="Skipping auto-sync: already attempted sync to d538b66198c18e4d4363ba6b92b98e171747861f with timeout 5s (retrying in 3.36548685s)" application=health
time="2020-06-10T06:14:42Z" level=info msg="Update successful" application=health
time="2020-06-10T06:14:42Z" level=info msg="Reconciliation completed" application=health dedup_ms=0 dest-namespace=bridge dest-server="https://kubernetes.default.svc" diff_ms=0 fields.level=2 git_ms=953 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=1000
time="2020-06-10T06:14:46Z" level=info msg="Refreshing app status (controller refresh requested), level (824698093632)" application=health
time="2020-06-10T06:14:46Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: bridge)" application=health
time="2020-06-10T06:14:46Z" level=info msg="getRepoObjs stats" application=health build_options_ms=0 helm_ms=0 manifests_ms=867 plugins_ms=0 repo_ms=0 time_ms=867 unmarshal_ms=0 version_ms=0
time="2020-06-10T06:14:46Z" level=info msg="Initiated automated sync to 'd538b66198c18e4d4363ba6b92b98e171747861f'" application=health dest-namespace=bridge dest-server="https://kubernetes.default.svc" reason=OperationStarted type=Normal
time="2020-06-10T06:14:46Z" level=info msg="Initiated automated sync to 'd538b66198c18e4d4363ba6b92b98e171747861f'" application=health
time="2020-06-10T06:14:46Z" level=info msg="updated 'health' operation (phase: Running)"
time="2020-06-10T06:14:46Z" level=info msg="Initialized new operation: {&SyncOperation{Revision:d538b66198c18e4d4363ba6b92b98e171747861f,Prune:true,DryRun:false,SyncStrategy:nil,Resources:[]SyncOperationResource{SyncOperationResource{Group:bitnami.com,Kind:SealedSecret,Name:test-healthcheck-secret,},SyncOperationResource{Group:cert-manager.io,Kind:Certificate,Name:test-certificate-v1,},},Source:nil,Manifests:[],SyncOptions:[],} { true}}" application=health
time="2020-06-10T06:14:46Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: bridge)" application=health
time="2020-06-10T06:14:46Z" level=info msg="getRepoObjs stats" application=health build_options_ms=0 helm_ms=0 manifests_ms=6 plugins_ms=0 repo_ms=0 time_ms=6 unmarshal_ms=0 version_ms=0
time="2020-06-10T06:14:46Z" level=info msg="Update successful" application=health
time="2020-06-10T06:14:46Z" level=info msg="Reconciliation completed" application=health dedup_ms=0 dest-namespace=bridge dest-server="https://kubernetes.default.svc" diff_ms=0 fields.level=824698093632 git_ms=867 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=910
time="2020-06-10T06:14:46Z" level=info msg=syncing application=health isSelectiveSync=true skipHooks=true started=false syncId=00003-HraJy
time="2020-06-10T06:14:46Z" level=info msg=tasks application=health isSelectiveSync=true syncId=00003-HraJy tasks="[Sync/0 resource cert-manager.io/Certificate:bridge/test-certificate-v1 nil->obj (,,), Sync/0 resource bitnami.com/SealedSecret:bridge/test-healthcheck-secret nil->obj (,,)]"
time="2020-06-10T06:14:46Z" level=info msg="Applying resource Certificate/test-certificate-v1 in cluster: https://172.30.0.1:443, namespace: bridge"
time="2020-06-10T06:14:47Z" level=info msg="Applying resource SealedSecret/test-healthcheck-secret in cluster: https://172.30.0.1:443, namespace: bridge"
time="2020-06-10T06:14:47Z" level=info msg="Updating operation state. phase: Running -> Running, message: '' -> 'one or more tasks are running'" application=health syncId=00003-HraJy
time="2020-06-10T06:14:47Z" level=info msg="Applying resource Certificate/test-certificate-v1 in cluster: https://172.30.0.1:443, namespace: bridge"
time="2020-06-10T06:14:47Z" level=info msg="adding resource result, status: 'Synced', phase: 'Running', message: 'certificate.cert-manager.io/test-certificate-v1 unchanged'" application=health kind=Certificate name=test-certificate-v1 namespace=bridge phase=Sync syncId=00003-HraJy
time="2020-06-10T06:14:47Z" level=info msg="Applying resource SealedSecret/test-healthcheck-secret in cluster: https://172.30.0.1:443, namespace: bridge"
time="2020-06-10T06:14:47Z" level=info msg="adding resource result, status: 'Synced', phase: 'Running', message: 'sealedsecret.bitnami.com/test-healthcheck-secret unchanged'" application=health kind=SealedSecret name=test-healthcheck-secret namespace=bridge phase=Sync syncId=00003-HraJy
time="2020-06-10T06:14:47Z" level=info msg="Updating operation state. phase: Running -> Succeeded, message: 'one or more tasks are running' -> 'successfully synced (all tasks run)'" application=health syncId=00003-HraJy
time="2020-06-10T06:14:47Z" level=info msg="sync/terminate complete" application=health duration=672.653337ms syncId=00003-HraJy
time="2020-06-10T06:14:47Z" level=info msg="updated 'health' operation (phase: Succeeded)"
time="2020-06-10T06:14:47Z" level=info msg="Partial sync operation to d538b66198c18e4d4363ba6b92b98e171747861f succeeded" application=health dest-namespace=bridge dest-server="https://kubernetes.default.svc" reason=OperationCompleted type=Normal
time="2020-06-10T06:14:47Z" level=info msg="Refreshing app status (controller refresh requested), level (2)" application=health
time="2020-06-10T06:14:47Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: bridge)" application=health
time="2020-06-10T06:14:48Z" level=info msg="getRepoObjs stats" application=health build_options_ms=0 helm_ms=0 manifests_ms=849 plugins_ms=0 repo_ms=0 time_ms=849 unmarshal_ms=0 version_ms=0
time="2020-06-10T06:14:48Z" level=info msg="Skipping auto-sync: already attempted sync to d538b66198c18e4d4363ba6b92b98e171747861f with timeout 5s (retrying in 3.537278561s)" application=health
time="2020-06-10T06:14:48Z" level=info msg="Update successful" application=health
time="2020-06-10T06:14:48Z" level=info msg="Reconciliation completed" application=health dedup_ms=0 dest-namespace=bridge dest-server="https://kubernetes.default.svc" diff_ms=1 fields.level=2 git_ms=850 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=877
time="2020-06-10T06:14:52Z" level=info msg="Refreshing app status (controller refresh requested), level (824710968304)" application=health
time="2020-06-10T06:14:52Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: bridge)" application=health

Application Status When Healthchecks are failing

$ oc get application -o yaml health
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: 2020-06-09T21:12:35Z
  generation: 1
  name: health
  namespace: argocd
  resourceVersion: "98320132"
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/argocd/applications/health
  uid: f0a84b7a-aa95-11ea-be6e-6e1ce29b84e4
spec:
  destination:
    namespace: bridge
    server: https://kubernetes.default.svc
  project: default
  source:
    path: openshift
    repoURL: <redacted>
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status:
  health:
    status: Missing
  history:
  - deployedAt: 2020-06-10T06:14:35Z
    id: 15
    revision: d538b66198c18e4d4363ba6b92b98e171747861f
    source:
      path: openshift
      repoURL: <redacted>
      targetRevision: HEAD
  observedAt: 2020-06-10T06:16:38Z
  operationState:
    finishedAt: 2020-06-10T06:16:38Z
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        automated: true
      sync:
        prune: true
        resources:
        - group: bitnami.com
          kind: SealedSecret
          name: test-healthcheck-secret
        - group: cert-manager.io
          kind: Certificate
          name: test-certificate-v1
        revision: d538b66198c18e4d4363ba6b92b98e171747861f
    phase: Succeeded
    startedAt: 2020-06-10T06:16:37Z
    syncResult:
      resources:
      - group: cert-manager.io
        hookPhase: Running
        kind: Certificate
        message: certificate.cert-manager.io/test-certificate-v1 unchanged
        name: test-certificate-v1
        namespace: bridge
        status: Synced
        syncPhase: Sync
        version: v1alpha2
      - group: bitnami.com
        hookPhase: Running
        kind: SealedSecret
        message: sealedsecret.bitnami.com/test-healthcheck-secret unchanged
        name: test-healthcheck-secret
        namespace: bridge
        status: Synced
        syncPhase: Sync
        version: v1alpha1
      revision: d538b66198c18e4d4363ba6b92b98e171747861f
      source:
        path: openshift
        repoURL: <redacted>
        targetRevision: HEAD
  reconciledAt: 2020-06-10T06:16:38Z
  resources:
  - health:
      status: Healthy
    kind: Service
    name: test-healthcheck-service
    namespace: bridge
    status: Synced
    version: v1
  - group: bitnami.com
    health:
      status: Missing
    kind: SealedSecret
    name: test-healthcheck-secret
    namespace: bridge
    status: OutOfSync
    version: v1alpha1
  - group: cert-manager.io
    health:
      status: Missing
    kind: Certificate
    name: test-certificate-v1
    namespace: bridge
    status: OutOfSync
    version: v1alpha2
  sourceType: Directory
  summary: {}
  sync:
    comparedTo:
      destination:
        namespace: bridge
        server: https://kubernetes.default.svc
      source:
        path: openshift
        repoURL: <redacted>
        targetRevision: HEAD
    revision: d538b66198c18e4d4363ba6b92b98e171747861f
    status: OutOfSync
$
```

Logs and application status after restarting argocd-application-controller pod
```
time="2020-06-10T06:19:18Z" level=info msg="appResyncPeriod=3m0s"
time="2020-06-10T06:19:18Z" level=info msg="Application Controller (version: v1.5.4+36bade7, built: 2020-05-05T19:02:17Z) starting (namespace: argocd)"
time="2020-06-10T06:19:18Z" level=info msg="Starting configmap/secret informers"
time="2020-06-10T06:19:18Z" level=info msg="Configmap/secret informer synced"
time="2020-06-10T06:19:18Z" level=info msg="0xc000184480 subscribed to settings updates"
time="2020-06-10T06:19:18Z" level=info msg="initializing cluster" server="https://kubernetes.default.svc"
time="2020-06-10T06:19:18Z" level=info msg="Start syncing cluster" server="https://kubernetes.default.svc"
LUA:CERTREQ
LUA:CERTREQ
LUA:CERTREQ
LUA:CERT
LUA:CERT
LUA:CERT
LUA:SEALEDSECRET
LUA:SEALEDSECRET
LUA:SEALEDSECRET
time="2020-06-10T06:19:19Z" level=info msg="Cluster successfully synced" server="https://kubernetes.default.svc"
time="2020-06-10T06:19:42Z" level=info msg="Refreshing app status (normal refresh requested), level (2)" application=health
time="2020-06-10T06:19:42Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: bridge)" application=health
time="2020-06-10T06:19:43Z" level=info msg="getRepoObjs stats" application=health build_options_ms=0 helm_ms=0 manifests_ms=820 plugins_ms=0 repo_ms=0 time_ms=821 unmarshal_ms=0 version_ms=0
LUA:SEALEDSECRET
LUA:CERT
time="2020-06-10T06:19:43Z" level=info msg="Skipping auto-sync: application status is Synced" application=health
time="2020-06-10T06:19:43Z" level=info msg="Updated sync status: OutOfSync -> Synced" application=health dest-namespace=bridge dest-server="https://kubernetes.default.svc" reason=ResourceUpdated type=Normal
time="2020-06-10T06:19:43Z" level=info msg="Updated health status: Missing -> Healthy" application=health dest-namespace=bridge dest-server="https://kubernetes.default.svc" reason=ResourceUpdated type=Normal
time="2020-06-10T06:19:43Z" level=info msg="Update successful" application=health
time="2020-06-10T06:19:43Z" level=info msg="Reconciliation completed" application=health dedup_ms=0 dest-namespace=bridge dest-server="https://kubernetes.default.svc" diff_ms=2 fields.level=2 git_ms=821 health_ms=1 live_ms=0 settings_ms=0 sync_ms=0 time_ms=856

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: 2020-06-09T21:12:35Z
  generation: 1
  name: health
  namespace: argocd
  resourceVersion: "98322142"
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/argocd/applications/health
  uid: f0a84b7a-aa95-11ea-be6e-6e1ce29b84e4
spec:
  destination:
    namespace: bridge
    server: https://kubernetes.default.svc
  project: default
  source:
    path: openshift
    repoURL: <redacted>
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status:
  health:
    status: Healthy
  history:
  - deployedAt: 2020-06-10T06:14:35Z
    id: 15
    revision: d538b66198c18e4d4363ba6b92b98e171747861f
    source:
      path: openshift
      repoURL: <redacted>
      targetRevision: HEAD
  observedAt: 2020-06-10T06:19:42Z
  operationState:
    finishedAt: 2020-06-10T06:17:16Z
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        automated: true
      sync:
        prune: true
        resources:
        - group: bitnami.com
          kind: SealedSecret
          name: test-healthcheck-secret
        - group: cert-manager.io
          kind: Certificate
          name: test-certificate-v1
        revision: d538b66198c18e4d4363ba6b92b98e171747861f
    phase: Succeeded
    startedAt: 2020-06-10T06:17:15Z
    syncResult:
      resources:
      - group: cert-manager.io
        hookPhase: Running
        kind: Certificate
        message: certificate.cert-manager.io/test-certificate-v1 unchanged
        name: test-certificate-v1
        namespace: bridge
        status: Synced
        syncPhase: Sync
        version: v1alpha2
      - group: bitnami.com
        hookPhase: Running
        kind: SealedSecret
        message: sealedsecret.bitnami.com/test-healthcheck-secret unchanged
        name: test-healthcheck-secret
        namespace: bridge
        status: Synced
        syncPhase: Sync
        version: v1alpha1
      revision: d538b66198c18e4d4363ba6b92b98e171747861f
      source:
        path: openshift
        repoURL: git@bitbucket.org:comcarde/test-healthchecks.git
        targetRevision: HEAD
  reconciledAt: 2020-06-10T06:19:42Z
  resources:
  - health:
      status: Healthy
    kind: Service
    name: test-healthcheck-service
    namespace: bridge
    status: Synced
    version: v1
  - group: bitnami.com
    health:
      status: Healthy
    kind: SealedSecret
    name: test-healthcheck-secret
    namespace: bridge
    status: Synced
    version: v1alpha1
  - group: cert-manager.io
    health:
      message: Certificate is up to date and has not expired
      status: Healthy
    kind: Certificate
    name: test-certificate-v1
    namespace: bridge
    status: Synced
    version: v1alpha2
  sourceType: Directory
  summary: {}
  sync:
    comparedTo:
      destination:
        namespace: bridge
        server: https://kubernetes.default.svc
      source:
        path: openshift
        repoURL: <redacted>
        targetRevision: HEAD
    revision: d538b66198c18e4d4363ba6b92b98e171747861f
    status: Synced
```

argocd-cm configmap with configured custom healthchecks
```
apiVersion: v1
data:
  accounts.jenkinspipeline: apiKey
  admin.enabled: "false"
  dex.config: |
    connectors:
      # OpenShift
      - type: "openshift"
        id: "openshift"
        name: "OpenShift"
        config:
          issuer: <redacted>
          clientID: "system:serviceaccount:argocd:argocd-dex-server"
          clientSecret: <redacted>
          redirectURI: <redacted>
          insecureCA: true
  repository.credentials: |-
    - url: ‘<redacted>’
      sshPrivateKeySecret:
        name: 'bitbucket-readonly'
        key: 'sshPrivateKey'
  resource.customizations: |-
    bitnami.com/SealedSecret:
      health.lua: |
        print ("LUA:SEALEDSECRET")
        hs = {}
        if obj.status ~= nil then
          if obj.status.conditions ~= nil then
            for i, condition in ipairs(obj.status.conditions) do
              if condition.type == "Synced" and condition.status == "False" then
                hs.status = "Degraded"
                hs.message = condition.message
                return hs
              end
              if condition.type == "Synced" and condition.status == "True" then
                hs.status = "Healthy"
                hs.message = condition.message
                return hs
              end
            end
          end
        end

        hs.status = "Progressing"
        hs.message = "Waiting for secret to be created"
        return hs
    cert-manager.io/Certificate:
      health.lua: |
        print ("LUA:CERT")
        hs = {}
        if obj.status ~= nil then
          if obj.status.conditions ~= nil then
            for i, condition in ipairs(obj.status.conditions) do
              if condition.type == "Ready" and condition.status == "False" then
                hs.status = "Degraded"
                hs.message = condition.message
                return hs
              end
              if condition.type == "Ready" and condition.status == "True" then
                hs.status = "Healthy"
                hs.message = condition.message
                return hs
              end
            end
          end
        end

        hs.status = "Progressing"
        hs.message = "Waiting for certificate"
        return hs
    cert-manager.io/CertificateRequest:
      health.lua: |
        print ("LUA:CERTREQ")
        hs = {}
        if obj.status ~= nil then
          if obj.status.conditions ~= nil then
            for i, condition in ipairs(obj.status.conditions) do
              if condition.type == "Ready" and condition.status == "False" then
                hs.status = "Degraded"
                hs.message = condition.message
                return hs
              end
              if condition.type == "Ready" and condition.status == "True" then
                hs.status = "Healthy"
                hs.message = condition.message
                return hs
              end
            end
          end
        end

        hs.status = "Progressing"
        hs.message = "Waiting for certificaterequest"
        return hs
  url: <redacted>
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"argocd-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-cm","namespace":"argocd"}}
  creationTimestamp: 2020-03-30T11:35:51Z
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
  resourceVersion: "98006588"
  selfLink: /api/v1/namespaces/argocd/configmaps/argocd-cm
  uid: 9c28a4c5-727a-11ea-a32f-6e1ce29b84e4
```

**Comment by stujb** [comment]
To mitigate this issue I have configured a cronjob to restart the argocd-application-controller pod every 5 minutes. With this in place we no longer have any issues with custom resources that have custom healthchecks configured

**Comment by mayzhang2000** [comment]
I can reproduce this issue in V1.5.4 by configuring a custom health check in argocd-cm for a custom resource, then create an application which has a CRD and a Custom Resource. This application got stuck at refresh and requires restart of controller.

Tried with the latest code and do not see this issue. This issue is fixed in https://github.com/argoproj/argo-cd/pull/3637/files

**Comment by stujb** [comment]
I have tested this with v1.5.6 and v1.6.1 and I am still seeing the same issues occuring. The custom healthchecks are not running without a restart of the application-controller.

**Comment by jopit** [comment]
I can take a look at this one.  Please assign to me.

**Comment by jopit** [comment]
I have not been able to reproduce this with the latest code from the master branch.  When I follow the steps described, the custom health checks do run as shown by the output to the application-controller's logs, and the custom resources are successfully synched.
```
time="2020-11-03T14:08:47Z" level=info msg="Refreshing app status (comparison expired. reconciledAt: 2020-11-03 14:05:47 +0000 UTC, expiry: 3m0s), level (2)" application=guestbook
time="2020-11-03T14:08:47Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2020-11-03T14:08:47Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: default)" application=guestbook
time="2020-11-03T14:08:47Z" level=info msg="getRepoObjs stats" application=guestbook build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=410 unmarshal_ms=410 version_ms=0
time="2020-11-03T14:08:47Z" level=info msg="Initiated automated sync to '73417ff5a0450b2bda4abe52e7f8e17b6abd8057'" application=guestbook dest-namespace=default dest-server="https://kubernetes.default.svc" reason=OperationStarted type=Normal
time="2020-11-03T14:08:47Z" level=info msg="Initiated automated sync to '73417ff5a0450b2bda4abe52e7f8e17b6abd8057'" application=guestbook
time="2020-11-03T14:08:47Z" level=info msg="Updated sync status: Synced -> OutOfSync" application=guestbook dest-namespace=default dest-server="https://kubernetes.default.svc" reason=ResourceUpdated type=Normal
time="2020-11-03T14:08:47Z" level=info msg="updated 'guestbook' operation (phase: Running)"
time="2020-11-03T14:08:47Z" level=info msg="Initialized new operation: {&SyncOperation{Revision:73417ff5a0450b2bda4abe52e7f8e17b6abd8057,Prune:false,DryRun:false,SyncStrategy:nil,Resources:[]SyncOperationResource{},Source:nil,Manifests:[],SyncOptions:[],} { true} [] {5 nil}}" application=guestbook
time="2020-11-03T14:08:47Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2020-11-03T14:08:47Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: default)" application=guestbook
time="2020-11-03T14:08:47Z" level=info msg="Updated health status: Healthy -> Missing" application=guestbook dest-namespace=default dest-server="https://kubernetes.default.svc" reason=ResourceUpdated type=Normal
time="2020-11-03T14:08:47Z" level=info msg="getRepoObjs stats" application=guestbook build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=9 unmarshal_ms=9 version_ms=0
time="2020-11-03T14:08:47Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2020-11-03T14:08:47Z" level=info msg=Syncing application=guestbook skipHooks=false started=false syncId=00002-oYlGx
time="2020-11-03T14:08:47Z" level=info msg="Update successful" application=guestbook
time="2020-11-03T14:08:47Z" level=info msg="Reconciliation completed" application=guestbook dedup_ms=0 dest-name= dest-namespace=default dest-server="https://kubernetes.default.svc" diff_ms=6 fields.level=2 git_ms=410 health_ms=0 live_ms=1 settings_ms=0 sync_ms=0 time_ms=477
LUA:CERT
time="2020-11-03T14:08:50Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=guestbook
time="2020-11-03T14:08:50Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2020-11-03T14:08:50Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: default)" application=guestbook
time="2020-11-03T14:08:50Z" level=info msg="getRepoObjs stats" application=guestbook build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=10 unmarshal_ms=10 version_ms=0
LUA:CERT
LUA:CERT
time="2020-11-03T14:08:50Z" level=info msg="Skipping auto-sync: another operation is in progress" application=guestbook
time="2020-11-03T14:08:50Z" level=info msg="Update successful" application=guestbook
time="2020-11-03T14:08:50Z" level=info msg="Reconciliation completed" application=guestbook dedup_ms=0 dest-name= dest-namespace=default dest-server="https://kubernetes.default.svc" diff_ms=52 fields.level=1 git_ms=10 health_ms=1 live_ms=3 settings_ms=0 sync_ms=0 time_ms=93
time="2020-11-03T14:08:50Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=guestbook
time="2020-11-03T14:08:50Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2020-11-03T14:08:50Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: default)" application=guestbook
time="2020-11-03T14:08:50Z" level=info msg="getRepoObjs stats" application=guestbook build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=27 unmarshal_ms=27 version_ms=0
LUA:CERT
time="2020-11-03T14:08:50Z" level=info msg="Skipping auto-sync: another operation is in progress" application=guestbook
LUA:CERT
time="2020-11-03T14:08:50Z" level=info msg="Update successful" application=guestbook
time="2020-11-03T14:08:50Z" level=info msg="Reconciliation completed" application=guestbook dedup_ms=0 dest-name= dest-namespace=default dest-server="https://kubernetes.default.svc" diff_ms=19 fields.level=1 git_ms=27 health_ms=1 live_ms=2 settings_ms=0 sync_ms=0 time_ms=81
time="2020-11-03T14:08:50Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=guestbook
time="2020-11-03T14:08:50Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2020-11-03T14:08:50Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: default)" application=guestbook
time="2020-11-03T14:08:50Z" level=info msg="getRepoObjs stats" application=guestbook build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=9 unmarshal_ms=9 version_ms=0
LUA:CERT
time="2020-11-03T14:08:50Z" level=info msg="Skipping auto-sync: another operation is in progress" application=guestbook
time="2020-11-03T14:08:50Z" level=info msg="No status changes. Skipping patch" application=guestbook
time="2020-11-03T14:08:50Z" level=info msg="Reconciliation completed" application=guestbook dedup_ms=0 dest-name= dest-namespace=default dest-server="https://kubernetes.default.svc" diff_ms=16 fields.level=1 git_ms=9 health_ms=1 live_ms=1 settings_ms=0 sync_ms=0 time_ms=38
time="2020-11-03T14:08:51Z" level=info msg="sync/terminate complete" application=guestbook duration=3.379575493s syncId=00002-oYlGx
time="2020-11-03T14:08:51Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=guestbook
time="2020-11-03T14:08:51Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2020-11-03T14:08:51Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: default)" application=guestbook
time="2020-11-03T14:08:51Z" level=info msg="getRepoObjs stats" application=guestbook build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=7 unmarshal_ms=7 version_ms=0
LUA:CERT
time="2020-11-03T14:08:51Z" level=info msg="Skipping auto-sync: another operation is in progress" application=guestbook
time="2020-11-03T14:08:51Z" level=info msg="Updated sync status: OutOfSync -> Synced" application=guestbook dest-namespace=default dest-server="https://kubernetes.default.svc" reason=ResourceUpdated type=Normal
time="2020-11-03T14:08:51Z" level=info msg="updated 'guestbook' operation (phase: Succeeded)"
time="2020-11-03T14:08:51Z" level=info msg="Sync operation to 73417ff5a0450b2bda4abe52e7f8e17b6abd8057 succeeded" application=guestbook dest-namespace=default dest-server="https://kubernetes.default.svc" reason=OperationCompleted type=Normal
time="2020-11-03T14:08:51Z" level=info msg="Updated health status: Missing -> Degraded" application=guestbook dest-namespace=default dest-server="https://kubernetes.default.svc" reason=ResourceUpdated type=Normal
time="2020-11-03T14:08:51Z" level=info msg="Update successful" application=guestbook
time="2020-11-03T14:08:51Z" level=info msg="Reconciliation completed" application=guestbook dedup_ms=0 dest-name= dest-namespace=default dest-server="https://kubernetes.default.svc" diff_ms=11 fields.level=1 git_ms=7 health_ms=1 live_ms=1 settings_ms=0 sync_ms=0 time_ms=56
time="2020-11-03T14:08:51Z" level=info msg="Refreshing app status (controller refresh requested), level (2)" application=guestbook
time="2020-11-03T14:08:51Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2020-11-03T14:08:51Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: default)" application=guestbook
LUA:CERT
LUA:CERTREQ
LUA:CERTREQ
LUA:CERT
time="2020-11-03T14:08:51Z" level=info msg="getRepoObjs stats" application=guestbook build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=115 unmarshal_ms=115 version_ms=0
LUA:CERT
time="2020-11-03T14:08:51Z" level=info msg="Skipping auto-sync: application status is Synced" application=guestbook
time="2020-11-03T14:08:51Z" level=info msg="Update successful" application=guestbook
time="2020-11-03T14:08:51Z" level=info msg="Reconciliation completed" application=guestbook dedup_ms=0 dest-name= dest-namespace=default dest-server="https://kubernetes.default.svc" diff_ms=8 fields.level=2 git_ms=115 health_ms=1 live_ms=1 settings_ms=0 sync_ms=0 time_ms=145
time="2020-11-03T14:08:51Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=guestbook
time="2020-11-03T14:08:51Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2020-11-03T14:08:51Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: default)" application=guestbook
time="2020-11-03T14:08:51Z" level=info msg="getRepoObjs stats" application=guestbook build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=7 unmarshal_ms=7 version_ms=0
LUA:CERT
time="2020-11-03T14:08:51Z" level=info msg="Skipping auto-sync: application status is Synced" application=guestbook
time="2020-11-03T14:08:51Z" level=info msg="Update successful" application=guestbook
time="2020-11-03T14:08:51Z" level=info msg="Reconciliation completed" application=guestbook dedup_ms=0 dest-name= dest-namespace=default dest-server="https://kubernetes.default.svc" diff_ms=7 fields.level=1 git_ms=7 health_ms=1 live_ms=1 settings_ms=0 sync_ms=0 time_ms=34
LUA:CERT
time="2020-11-03T14:08:51Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=guestbook
time="2020-11-03T14:08:51Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2020-11-03T14:08:51Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: default)" application=guestbook
time="2020-11-03T14:08:51Z" level=info msg="getRepoObjs stats" application=guestbook build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=7 unmarshal_ms=7 version_ms=0
LUA:CERT
time="2020-11-03T14:08:51Z" level=info msg="Skipping auto-sync: application status is Synced" application=guestbook
time="2020-11-03T14:08:51Z" level=info msg="No status changes. Skipping patch" application=guestbook
time="2020-11-03T14:08:51Z" level=info msg="Reconciliation completed" application=guestbook dedup_ms=0 dest-name= dest-namespace=default dest-server="https://kubernetes.default.svc" diff_ms=7 fields.level=1 git_ms=7 health_ms=1 live_ms=1 settings_ms=0 sync_ms=0 time_ms=23
LUA:CERT
time="2020-11-03T14:08:52Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=guestbook
time="2020-11-03T14:08:52Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2020-11-03T14:08:52Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: default)" application=guestbook
time="2020-11-03T14:08:52Z" level=info msg="getRepoObjs stats" application=guestbook build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=7 unmarshal_ms=6 version_ms=0
LUA:CERT
time="2020-11-03T14:08:52Z" level=info msg="Skipping auto-sync: application status is Synced" application=guestbook
time="2020-11-03T14:08:52Z" level=info msg="Updated health status: Degraded -> Healthy" application=guestbook dest-namespace=default dest-server="https://kubernetes.default.svc" reason=ResourceUpdated type=Normal
time="2020-11-03T14:08:52Z" level=info msg="Update successful" application=guestbook
time="2020-11-03T14:08:52Z" level=info msg="Reconciliation completed" application=guestbook dedup_ms=0 dest-name= dest-namespace=default dest-server="https://kubernetes.default.svc
```

**Comment by FestineOnGCP** [comment]
Hi Guy. I have implemented a custom health check for github actions runner deployment but the health check only works for the custom resource but does not affect the status of the pods created by this custom resources. How do I go about this issue? Thanks.

**Comment by edas-smith** [comment]
Have the same issue as the above.
