### ISSUE TITLE
ArgoCD authentication handshake failed

### ISSUE THREAD

**Issue by storm1kk** [argoproj/argo-cd#5110]
**Describe the bug**

Hello ArgoCD Team!

We have upgraded our ArgoCD instances recently and facing bothering issue now. Time to time ArgoCD starts sync process and looks like it hanging somewhere. Then it works normally and then hit again.

We also noticed that restart of ```argocd-repo-server``` can help for a short moment.

We have one replica of ```argocd-repo-server``` and two replicas of ```argocd-server```.

**To Reproduce**

N/A.

**Expected behavior**

ArgoCD is not hanging during app sync

**Screenshots**

![Screenshot 2020-12-22 at 16 03 04](https://user-images.githubusercontent.com/8113941/102893827-3cfbe100-4473-11eb-9aee-557d11d3d7bf.png)

**Version**

```shell
argocd: v1.8.1+c2547dc
  BuildDate: 2020-12-10T02:57:57Z
  GitCommit: c2547dca95437fdbb4d1e984b0592e6b9110d37f
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
time="2020-12-22T12:43:44Z" level=info msg="Sync operation to  failed: ComparisonError: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: authentication handshake failed: remote error: tls: internal error\"" application=graph-db-graphdb-api-instances dest-namespace=graph-db dest-server="https://kubernetes.default.svc" reason=OperationCompleted type=Warning
```

**Comment by jannfis** [comment]
@alexmt Probably similar issue as the one we recently talked about.

**Comment by jessesuen** [comment]
Yes we are facing this internally as well. We suspect the upgrade in gRPC libraries may have caused this but haven't confirmed. In an internal build, we put in place a gRPC health check which kills the repo-server when this happened and that allowed us to recover, but doesn't address the root cause.

**Comment by jannfis** [comment]
As discussed on Slack already, it would be really valuable if someone could inspect the argocd-repo-server listener when its failing. with another TLS capable client that gives some more information about handshake.

For example, full output of `openssl s_client -host <host_of_failing_reposerver_pod> -port <port_on_pod>` (or service instead of pod, if there's only one replica of repo-server), which might give us some more indications of what happens on TLS handshake level.

I have also taken a look at our gRPC stack, it looks terrible :) We have updated some of the components, but others not, and its not easy to get this straight due to many legacy constructs in the code. I'm working on it, tho.

I'm still trying to reproduce the issue locally, but without much luck.

**Comment by storm1kk** [comment]
> As discussed on Slack already, it would be really valuable if someone could inspect the argocd-repo-server listener when its failing. with another TLS capable client that gives some more information about handshake.
> 
> For example, full output of `openssl s_client -host <host_of_failing_reposerver_pod> -port <port_on_pod>` (or service instead of pod, if there's only one replica of repo-server), which might give us some more indications of what happens on TLS handshake level.
> 

We will try to catch it next time ArgoCD hangs.

**Comment by Issif** [comment]
Hi,

We're currently facing the issue, here the result of the command (run internally of a repo-server):

```bash

argocd@argocd-repo-server-c4d8c7f6b-cwhjj:~$ openssl s_client -host localhost -port 8081

CONNECTED(00000003)
Can't use SSL_get_servername
depth=0 O = Argo CD
verify error:num=18:self signed certificate
verify return:1
depth=0 O = Argo CD
verify return:1
140146647491712:error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../ssl/record/rec_layer_s3.c:1544:SSL alert number 80
---
Certificate chain
 0 s:O = Argo CD
   i:O = Argo CD
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIDETCCAfmgAwIBAgIRAKGoOTg9C6uM6wu2GonmFT4wDQYJKoZIhvcNAQELBQAw
EjEQMA4GA1UEChMHQXJnbyBDRDAeFw0yMDEyMjIxNjMyMjRaFw0yMTEyMjIxNjMy
MjRaMBIxEDAOBgNVBAoTB0FyZ28gQ0QwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAw
ggEKAoIBAQCsshiDMHQ61J55+0AOApeCY4xgmbQ+/+YqWKQDbRpBbHdDEgf4Bux8
Ij1XUBgC4iTlI6LNu1rXgt3wIr3peeiNsrjcHR73C0A5WVAPsbD+ueyAj9mdA1RM
Iq70WwvdJv7ITGSCfJ2di4gV3AeMVO2qBH5A5GOtIaVt4dbskvG4i7cvvr+Rvnrq
4xX1jMbjh1pkhCnXrNhnyxPrwHgYV0Lz4+eeirMsJD603OJgekYDHGT/v9AtnW/8
KN/6VGHy4qvjjlms7wXaeANK1wu9h0dfublFuC8jvr/BUdHdMqZ71vn/FluRVdqa
smAHQWO2DxdbR2CHXuTuLaKdZYTwOso3AgMBAAGjYjBgMA4GA1UdDwEB/wQEAwIC
pDATBgNVHSUEDDAKBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCgGA1UdEQQh
MB+CCWxvY2FsaG9zdIISYXJnb2NkLXJlcG8tc2VydmVyMA0GCSqGSIb3DQEBCwUA
A4IBAQCargXh/niqJcbKZGkhDp7SY72Fmy9wSjnfSALOJtiomHeAt2kuOmmcu8v6
B62xIHYHMIU/bVecV4CgdyoVOeNmA9Hs3UUuIMBWWuCPFnUJUIpijY34/xdYceXB
AHX8OGmjY/VdLQgRM5fQg+ufZiqNRRPnB9uxxzpqy1VxGKetoXdCzfATmIsNh32N
0otUE2PGEufM01ggJWD3sUoKewlBHPmyAocEzDDLFVsQdKfFFB4PsYPCDZvlH2mq
CoDvRcSQ2Y2D7U6DlzQOrDBhqVMmpC9GHp8wHtH+rMgo1ZJyAfZgIvYJTgdfn2HC
LqFFE09tUWyK8ZZSIhLtSE53QZsZ
-----END CERTIFICATE-----
subject=O = Argo CD

issuer=O = Argo CD

---
No client certificate CA names sent
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 1009 bytes and written 283 bytes
Verification error: self signed certificate
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 18 (self signed certificate)
---
```

Hope I will help.

**Comment by jannfis** [comment]
OK, this one is interesting

> `140146647491712:error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../ssl/record/rec_layer_s3.c:1544:SSL alert number 80`

Apparently, for `openssl` client, this error is transient while for our golang/gRPC client, it is not.

Will investigate further.

Thank you for this additional information, @Issif

**Comment by eroji** [comment]
Having the same issue here.

@Issif when you said you deleted the repo-server can you clarify what exactly you did? Did you delete the pods for `argocd-repo-server` deployment?

**Comment by Issif** [comment]
> Having the same issue here.
> 
> @Issif when you said you deleted the repo-server can you clarify what exactly you did? Did you delete the pods for `argocd-repo-server` deployment?

Exactly. I just deleted the pod and let the deployment recreate it.

**Comment by eroji** [comment]
Got it. I guess I'll use that as a workaround until this is fixed.

**Comment by alexmt** [comment]
We've added livenessProbe that restart repo server as a workaround. Here is merge patch that introduce the probe:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      containers:
      - name: argocd-repo-server
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
          exec:
            command: [ "/usr/local/bin/grpc-health-probe", "-addr=:8081", "-tls", "-tls-no-verify" ]
        volumeMounts:
        - mountPath: /usr/local/bin/grpc-health-probe
          name: custom-tools
          subPath: grpc-health-probe
      volumes:
      - name: custom-tools
        emptyDir: {}
      initContainers:
      - name: download-grpc-health-probe
        image: docker.intuit.com/oicp/alpine3.8:latest
        command: [sh, -c]
        args:
          - wget --no-check-certificate https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/v0.3.5/grpc_health_probe-linux-amd64 &&
            mv grpc_health_probe-linux-amd64 /custom-tools/grpc-health-probe &&
            chmod ugo+x /custom-tools/grpc-health-probe
        volumeMounts:
          - mountPath: /custom-tools
            name: custom-tools
```

@jannfis , @jessesuen do you think we should add it by default until issue is resolved?

**Comment by jessesuen** [comment]
Yes, I think we should. The consequence of not having this is users have repo-servers which will eventually be rendered inoperable.

**Comment by alexmt** [comment]
I don't like fork/exec and additional init container though. Instead of doing that we could just change an existing HTTP health check implementation to call GRPC health check on localhost. So `GET /healthz` handler should call grpc GetHealth on localhost:8080 . What do you think?

**Comment by jannfis** [comment]
> I don't like fork/exec and additional init container though. Instead of doing that we could just change an existing HTTP health check implementation to call GRPC health check on localhost. So `GET /healthz` handler should call grpc GetHealth on localhost:8080 . What do you think?

Is that a built-in function? Or do we need to implement a dummy RPC for that, as described in https://github.com/grpc/grpc/blob/master/doc/health-checking.md?

**Comment by jannfis** [comment]
So just to gather more information, this issue started for people after upgrading to 1.8 right?

May I ask from what exact versions you were upgrading from, that was not affected by this issue? We update Go with v1.7.9 and it would be interesting to know if this and later 1.7 versions are affected as well.

**Comment by jessesuen** [comment]
> I don't like fork/exec and additional init container though. Instead of doing that we could just change an existing HTTP health check implementation to call GRPC health check on localhost. So GET /healthz handler should call grpc GetHealth on localhost:8080 . What do you think?

I'm also weary of fork/exec so I like this suggestion, assuming it can catch the issue.

> So just to gather more information, this issue started for people after upgrading to 1.8 right?

Yes, we only started noticing this after upgrade from Argo CD from v1.7 to v1.8.

**Comment by storm1kk** [comment]
> So just to gather more information, this issue started for people after upgrading to 1.8 right?
> 
> May I ask from what exact versions you were upgrading from, that was not affected by this issue? We update Go with v1.7.9 and it would be interesting to know if this and later 1.7 versions are affected as well.

We did upgrade from 1.7 to 1.8 and I confirm that 1.7 has no this issue.

**Comment by himberjack** [comment]
We saw this from 1.7 -> 1.8 as well

**Comment by jannfis** [comment]
I'm still not able to reproduce this issue - it doesn't happen in my production environment (HA setup with 1 controller, 2 API server and 2 repo server instances), and also not with a local test setup where I'm hammering forced refreshs of applications against the repo server.

May I ask people for the following information:

1. What Kubernetes version are you running on?
2. How does your setup look like (in terms of scaling, and do you deviate from standard settings as in the installation manifests - e.g. changed command line parameters, etc)
3. How many apps is your Argo CD managing, and on how many clusters?

Also, if it is happening quite often in your environment, it might be worth trying to downgrade repo server TLS endpoint from TLS 1.3 to TLS 1.2 by setting `--tlsmaxversion 1.2` to the startup parameters for Argo CD repo server. Could anyone please try that and see if that helps the situation?

**Comment by Issif** [comment]
We didn't faced the issue again. Here the details about the cluster which got the problem:

- EKS 1.18
- Argocd v1.8.1+c2547dc
- 6 Nodes
- 1 controller + 1 repo server + 1 server
- ~16 apps
- arguments (all defaults except for controller):

```yaml
            - argocd-application-controller
            - --app-resync
            - "600"
            - --status-processors
            - "55"
            - --operation-processors
            - "30"
            - --kubectl-parallelism-limit
            - "70"
```

This is a very small cluster, for QA of tierced apps version.

Our main cluster is between 70-100 nodes with 2500-3500 apps, and we didn't faced TLS issues with, even if it has 10 repo servers on it.

**Comment by jsoref** [comment]
@jannfis, I think our upgrade was:
```diff
-  _ARGO_PROJECT: argocd@sha256:3e300c3c421ef15278daf662fc125d75050dc0816570cfbe08295a734a342314
+  _ARGO_PROJECT: argocd@sha256:26e1632e83e7f72ac7e6c6361dbd83ae52e8ad06cc1c266a1917054a0ae03f12
```
Sadly, I'm not sure I can actually convert those SHAs into anything useful

**Comment by jeliasson** [comment]
> We've added livenessProbe that restart repo server as a workaround. Here is merge patch that introduce the probe:
> ```yaml
> apiVersion: apps/v1
> [...]
>       initContainers:
>       - name: download-grpc-health-probe
>         image: docker.intuit.com/oicp/alpine3.8:latest

@alexmt 
Thanks for the patch! Would you kindly update the comment to have image to `alpine:3.8` rather than `docker.intuit.com/oicp/alpine3.8:latest` so other users don't hit a 403 Unauthorized. Thanks! 😊

**Comment by rumstead** [comment]
We are experiencing this as well after the 1.7 -> 1.8 upgrade. Is there a published version of the repo server image that I can use with the probes? 
```
ArgoCD Version: v1.8.1+c2547dc
Standard ArgoCD Deployment
5 Clusters, 50 ish applications
```

**Comment by alexmt** [comment]
@rumstead , just published https://github.com/argoproj/argo-cd/releases/tag/v1.8.2 

It includes liveness probe that auto-restart repo-server

**Comment by alexmt** [comment]
We've been using liveness probe for a long time - it is pretty good workaround and buys us some time. Next will try to upgrade grpc and golang versions.

**Comment by storm1kk** [comment]
We're going to update ArgoCD to 1.8.2 version. Although, I have to say, we did not hit this issue again since 22 Dec 2020. I think, long holidays could be a reason for this.

**Comment by mars64** [comment]
Just chiming in with my setup:

*  First noticed this issue in argocd`v1.8.1+c2547dc` in a "low volume" dev cluster, we ended up hitting this issue. Bouncing repo-server appeared to resolve the immediate issue. I've updated to `1.8.2` anyway -- issue still appears to be resolved. We never saw the issue on `1.7.x`
* non-ha -- 1 x argocd-server, 1 x repo server, etc
* installation-wise, argocd is a totally vanilla install: `https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml` 
* the only things we change are after the fact -- custom rbac-cm (create dev accout + permissions), we inject `--insecure` to the deploy spec (since we tls terminate at our traefik instance)
* manages one cluster - eks: `1.18.9-eks`, 8 x nodes in the cluster. 
* repo-server is hooked up to 8 repos -- 7 x public github repos, and 1 x chart repo (https://kubernetes-charts.storage.googleapis.com/)
* 4 parent appOfApps, 30 applications in total

**Comment by alexmt** [comment]
We've been running v2.0-rc1 in production for several weeks now and no longer seeing that issue. The v1.8 had that issue 1~2 times per week. Most likely issue is fixed by upgrading golang to v1.16.x . Closing ticket since issue is now longer reproducible. Please comment if you able to reproduce it using v2.0

**Comment by simax** [comment]
Hi Team,

We're seeing a similar error with V2.0.0. We setup Argo CD as few weeks ago and everything seemed fine for a while. Nothing is in production  yet we're just trying things out. Our cluster in AWS eks. 

Argo CD
v2.0.0+d085636
Build Date
2021-03-30T19:10:08Z
Go Version
go1.16
Go Compiler
gc
Platform
linux/amd64
ksonnet
v0.13.1
jsonnet
v0.17.0
kustomize
v3.9.4 2021-02-09T19:22:10Z
Helm
v3.5.1+g32c2223
kubectl
v0.20.4

We're seeing sync error:

![argo-cd-connection-error](https://user-images.githubusercontent.com/1292469/113508576-aeeec680-9548-11eb-8440-4cd23b51ab5f.PNG)

**Comment by jannfis** [comment]
@simax The error you see does not seem to be related to the one described in this issue. Your error most likely indicates that the `argocd-repo-server` pod is not running.

**Comment by yovizzle** [comment]
> We've been running v2.0-rc1 in production for several weeks now and no longer seeing that issue. The v1.8 had that issue 1~2 times per week. Most likely issue is fixed by upgrading golang to v1.16.x . Closing ticket since issue is now longer reproducible. Please comment if you able to reproduce it using v2.0

I started seeing this last night after previously having no problems. This morning I updated to v2.0.0 to try and fix it, but it's still occurring. I was on 1.8 or 1.9 (stupidly didn't check the version before updating).

It alternates between these two errors:
![image](https://user-images.githubusercontent.com/22759569/114115900-0e711b80-9927-11eb-9757-ba46fa835d0e.png)
![image](https://user-images.githubusercontent.com/22759569/114118584-60687000-992c-11eb-8750-b904fe330ced.png)

I'm running istio aswell, and I suspect I may have an Istio misconfiguration causing this, as the argocd-repo-server container is actually running fine, but the istio-proxy container is not entering ready state, and keeps looping this message:

```
2021-04-09T01:55:24.066597Z    info    xdsproxy    connecting to upstream XDS server: istiod.istio-system.svc:15012
2021-04-09T01:55:24.073749Z    error    xdsproxy    failed to read token file "/var/run/secrets/kubernetes.io/serviceaccount/token": open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
2021-04-09T01:55:24.073804Z    error    xdsproxy    failed to create upstream grpc client: rpc error: code = Unauthenticated desc = transport: failed to read token file "/var/run/secrets/kubernetes.io/serviceaccount/token": open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
2021-04-09T01:55:24.073809Z    info    xdsproxy    disconnected from XDS server: istiod.istio-system.svc:15012
2021-04-09T01:55:24.074359Z    warning    envoy config    StreamAggregatedResources gRPC config stream closed: 16, transport: failed to read token file "/var/run/secrets/kubernetes.io/serviceaccount/token": open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
2021-04-09T01:55:25.552886Z    warn    Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 0 successful, 0 rejected; lds updates: 0 successful, 0 rejected
```

But, other istio-proxy containers in the same namespace are running and ready with no problems (eg. argocd-server; argo-dex-server). No istio-proxy readiness issues in other namespaces either. 

Any advice on how to proceed @alexmt ?

**Comment by alexmt** [comment]
Version v2.0 introduced a set of flags that allow disabling repo-server SSL (https://github.com/argoproj/argo-cd/pull/5764) . You can add `--repo-server-plaintext` flag to the `argocd-repo-server` Deployment args and terminate SSL using Istio.

**Comment by yovizzle** [comment]
Thanks for the very quick reply!

Unfortunately it's still not working. I just tried adding that flag to `argocd-server` (tried first on `argocd-repo-server` as you said, got a `argocd-repo-server Error: unknown flag: --repo-server-plaintext`).

The istio-proxy is still not reaching ready.

After looking at  #5764 I was checking that --repo-server is pointing to the sidecar properly, and it's going to `argocd-repo-server:8081`. Is this the correct way of addressing the sidecar? 

I also noticed that the argocd-repo-server:8081 clusterIp has no endpoints.
```
NAME                      ENDPOINTS                                         AGE
...
argocd-repo-server                                                          5m28s
argocd-server             10.52.5.54:8080,10.52.5.54:8080                   4h44m
...```

Any thoughts?

**Comment by msuthar-splunk** [comment]
Seeing the same issue as @simax on v2.0.3. @shubhamagarwal19 are you planning on creating a PR for your fix?

**Comment by jannfis** [comment]
Reading above error messages, especially:

```
2021-04-09T01:55:24.073749Z    error    xdsproxy    failed to read token file "/var/run/secrets/kubernetes.io/serviceaccount/token": open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
2021-04-09T01:55:24.073804Z    error    xdsproxy    failed to create upstream grpc client: rpc error: code = Unauthenticated desc = transport: failed to read token file "/var/run/secrets/kubernetes.io/serviceaccount/token": open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
```
Does istio (or Envoy sidecar, for that matter) require the main pod to mount a service account token? If yes, the `argocd-repo-server` explicitly choses not to, due to security reasons.

**Comment by jannfis** [comment]
> Unfortunately it's still not working. I just tried adding that flag to argocd-server (tried first on argocd-repo-server as you said, got a argocd-repo-server Error: unknown flag: --repo-server-plaintext).

This should be `--disable-tls` for `argocd-repo-server`, and `--repo-server-plaintext` for `argocd-server` and `argocd-application-controller` workloads, depending on your needs.

**Comment by u2m4c6** [comment]
I am seeing this as well with v2 and go 1.16. I have restarted all of the argocd pods. Any ideas how to fix this?

{
    "Version": "v2.1.1+aab9542",
    "BuildDate": "2021-08-25T15:12:04Z",
    "GitCommit": "aab9542f8b3354f0940945c4295b67622f0af296",
    "GitTreeState": "clean",
    "GoVersion": "go1.16.5",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v4.2.0 2021-06-30T22:49:26Z",
    "HelmVersion": "v3.6.0+g7f2df64",
    "KubectlVersion": "v0.21.0",
    "JsonnetVersion": "v0.17.0"
}

**Comment by u2m4c6** [comment]
If it helps, this problem started happening after I tried to access argocd with the CLI with Ingress Nginx. So my argocd ui is at argocd.example.com and my cli endpoint is grpc.argocd.example.com.

**Comment by bentcoder** [comment]
The issue is still present.

```json
{
    "Version": "v2.2.4+78d749e",
    "BuildDate": "2022-02-03T20:41:00Z",
    "GitCommit": "78d749ec88bea5a5e851fc48b9404fdf067192b6",
    "GitTreeState": "clean",
    "GoVersion": "go1.16.11",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v4.2.0 2021-06-30T22:49:26Z",
    "HelmVersion": "v3.7.1+g1d11fcb",
    "KubectlVersion": "v0.22.2",
    "JsonnetVersion": "v0.17.0"
}
```

**Comment by abdelkader-brahem** [comment]
sdf
