### ISSUE TITLE
Show orphaned button only works when page is scrolled to the top

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#5161]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The show orphaned checkbox isn't clickable most of the time

**To Reproduce**

1. Enable the orphaned button (see other issues)
2. Go to an application that has orphans
3. Scroll through the view
4. Click the cute button
5. Repeat steps 3-4 observing the response

**Expected behavior**

Clicking a check box that isn't disabled should toggle the checkbox regardless of anything else that may be scrolled around it.

**Screenshots**

https://user-images.githubusercontent.com/2119212/103421171-fa1fc480-4b68-11eb-98de-550abc4f1a98.mov

**Version**

```shell
{
    "Version": "v1.8.1+c2547dc",
    "BuildDate": "2020-12-10T02:59:21Z",
    "GitCommit": "c2547dca95437fdbb4d1e984b0592e6b9110d37f",
    "GitTreeState": "clean",
    "GoVersion": "go1.14.12",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.8.1 2020-07-16T00:58:46Z",
    "HelmVersion": "v3.4.1+gc4e7485",
    "KubectlVersion": "v1.17.8",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

**Comment by silverraven691** [comment]
This looks fixed in 2.0.0

**Comment by jsoref** [comment]
Seems doubtful.  We're running newer than 2.0.0 and still hit it. We plan to upgrade to latest this week. But I'd be fairly surprised if it was fixed.

Post a video?

**Comment by silverraven691** [comment]
No, it just works for me on Chrome with v2.0.0+e9ce61d installed, so it might be a browser compatibility issue.

**Comment by jsoref** [comment]
Seriously, please post a video (like the one here). It's still broken for me in current Chrome (macOS, as pictured before) in https://github.com/argoproj/argo-cd/commits/d085636.

**Comment by silverraven691** [comment]
No, I don't care that you don't trust me, lol.
