### ISSUE TITLE
ignoreDifferences.managedFieldsManagers not working as expected

### ISSUE THREAD

**Issue by spyder007** [argoproj/argo-cd#9071]
**Describe the bug**

Setting ignoreDifferences.managedFieldsManagers is not ignoring fields marked as managed by `external-secrets`

**To Reproduce**

1. Create an application for external-secrets.io using their [helm chart](https://github.com/external-secrets/external-secrets/tree/main/deploy/charts/external-secrets) (version 0.5.1).  Be sure you set `installCRDs=true`
2.  Add this application with the following application spec:
```yaml
- name: external-secrets
      namespace: argo
      destination:
        namespace: external-secrets
        server: https://kubernetes.default.svc
      project: argocd
      source:
        helm:
          version: v3
          valueFiles:
          - values.yaml
        path: external-secrets
        repoURL: https://<url-to-your-argo-repo>
        targetRevision: HEAD
      ignoreDifferences:
      - group: "*"
        kind: "*"
        managedFieldsManagers:
        - external-secrets
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        - RespectIgnoreDifferences=true

```
3.  Sync the application
4. Notice that two validating webhooks and three CRDs will show as out of sync because their fields are modified by the external-secrets controller
5. If you look at the manifests for these resources, you'll notice that the fields that are different are also marked in .metadata.managedFields as being managed by `external-secrets`.

**Expected behavior**

Setting `.ignoreDifferences.managedFieldsManagers` to `external-secrets` should ignore the fields managed marked as managed by the external-secrets controller.

**Screenshots**
External Secrets resources after sync
![image](https://user-images.githubusercontent.com/4701399/162820310-41fe2122-a321-4481-b094-e47b4a5bc29e.png)

*** Managed Fields for one of the validating webhooks
![image](https://user-images.githubusercontent.com/4701399/162821693-ff2a8969-e70c-47fa-b90e-7b417a89cc1b.png)

*** Diff of the validating webhook from above
![image](https://user-images.githubusercontent.com/4701399/162822031-0b26148a-efd6-48f7-8585-323f04da8b0d.png)

**Version**

```shell
argocd: v2.3.1+b65c169
  BuildDate: 2022-03-11T00:05:18Z
  GitCommit: b65c1699fa2a2daa031483a3890e6911eac69068
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: windows/amd64
time="2022-04-11T15:56:03-04:00" level=warning msg="Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web."
argocd-server: v2.3.3+07ac038
  BuildDate: 2022-03-30T00:06:18Z
  GitCommit: 07ac038a8f97a93b401e824550f0505400a8c84e
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.4.1 2021-11-11T23:36:27Z
  Helm Version: v3.8.0+gd141386
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0
```

**Logs**

I don't have any relevant logs:  the applications sync correctly, but then the controller immediately changes the fields, causing them to be out of sync.

**Comment by leoluz** [comment]
@spyder007 Tks for the detailed info!

I tried to deploy locally to reproduce the issue but I am getting errors in the `external-secrets-webhook` and `external-secrets-cert-controller` deployments.

The webhook one is failing with:
`stat /tmp/certs/tls.crt: no such file or directory"`

The cert controller with:
`"msg":"could not update webhook config","Webhookconfig":"/secretstore-validate","error":"ca cert not yet ready"`

I deployed the helm chart in my local setup like you described. I am sorry but I don't know anything about this `external-secrets` controller and how it is supposed to work. Can you pls provide a working example?

**Comment by leoluz** [comment]
Cool. I can reproduce the issue now. Thank you.

**Comment by leoluz** [comment]
There are two different problems in current ignore diff config implementation:
1. Application specific diff configs discarded for CRD definitions. (Addressed by https://github.com/argoproj/argo-cd/pull/9092)
2. Wrongly calculating diffs inside nested lists in CRDs with managed fields ignore configs.

**Comment by spyder007** [comment]
@leoluz So, it looks like the CRD case will be fixed with the next release.  What about the ValidatingWebHook?

**Comment by hi-artem** [comment]
@spyder007 Have you managed deploying external-secrets in ArgoCD? We are getting the same issue and would appreciate some work around until the bugs are addressed.

**Comment by spyder007** [comment]
@hi-artem It deploys, but the problems with the application differences causes it to show as out of sync.  For now, I turned off automated sync, which solves the constant cycling of synchronization.  @leoluz's changes in #9092 should correct some of the sync issues, so I'm currently waiting for the next release which includes the above changes to test.

**Comment by hi-artem** [comment]
The other work around I have found that works using `jqPathExpressions`:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: 'https://charts.external-secrets.io'
    targetRevision: 0.5.1
    helm:
      values: |-
        serviceAccount:
          name: external-secrets
    chart: external-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jqPathExpressions:
    - .spec.conversion.webhook.clientConfig.caBundle
    - .spec.conversion.webhook.clientConfig.service.name
    - .spec.conversion.webhook.clientConfig.service.namespace
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[]?.clientConfig.caBundle
 ```

**Comment by leoluz** [comment]
> The other work around I have found that works using `jqPathExpressions`:


Using `jqPathExpressions` is a viable alternative to the current bug with the `managedFieldManagers`. 

@hi-artem This config will avoid displaying the diffs in ArgoCD however it will still sync with the desired state value which is probably something you don't want. To avoid this problem you can enable the following sync option:
```yaml
      syncPolicy:
        syncOptions:
        - RespectIgnoreDifferences=true
```

**Comment by hi-artem** [comment]
@leoluz Gotcha! Thank you for this detail. `RespectIgnoreDifferences` is definitely the desired behavior.

**Comment by spyder007** [comment]
@leoluz 

As of 2.3.4, I was able to get this working with the following spec:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets-tool
  labels:
    spydersoft.io/category: cluster-tools
spec:
  generators:
   - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
          spydersoft.io/external-secrets: 'true'
  template:
    metadata:
      name: '{{ nameNormalized }}-external-secrets'
      labels:
        spydersoft.io/category: cluster-tools 
    spec:
      project: cluster-tools
      source:
        repoURL: https://bitbucket.org/spydersoftteam/ops-argo
        targetRevision: main
        path: 'cluster-tools/tools/external-secrets'
        helm: {}
      destination:
        server: '{{ server }}'
        namespace: 'external-secrets'
      ignoreDifferences:
      - group: "*"
        kind: "*"
        managedFieldsManagers:
        - external-secrets
      - group: '*'
        kind: '*'
        jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'
        - '.webhooks[]?.client'
      syncPolicy:
        # automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
        #   prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
        #   selfHeal: false
        syncOptions:     # Sync options which modifies sync behavior
        - CreateNamespace=true
        - RespectIgnoreDifferences=true
```

My assumption is that the managedFieldsManagers setting, coupled with the jqPathExpressions, allowed Argo to sufficiently ignore the changed fields.

I deployed 2.4.0-rc5 and then changed my spec:

```yaml
...
      ignoreDifferences:
      - group: "*"
        kind: "*"
        managedFieldsManagers:
        - external-secrets
      syncPolicy:
        # automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
        #   prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
        #   selfHeal: false
        syncOptions:     # Sync options which modifies sync behavior
        - CreateNamespace=true
        - RespectIgnoreDifferences=true

```

This change seems to work:  the application is ignoring fields managed by external-secrets without the additional jqPathExpressions.

**Comment by thesuperzapper** [comment]
@leoluz I think someone must have broken [your fix](https://github.com/argoproj/argo-cd/pull/9170), because it's not working in 2.7.4, see issue: https://github.com/argoproj/argo-cd/issues/9696

Its also possible that your fix did not account for `managedFields` that look like this (where only a single key within a map is managed):

```
- apiVersion: apps/v1
  fieldsType: FieldsV1
  fieldsV1:
    f:spec:
      f:template:
        f:metadata:
          f:annotations:
            .: {}
            f:secret-version/my-secret: {}
  manager: background-controller
  operation: Update
  time: "2023-07-04T02:09:08Z"    
```

**Comment by mars64** [comment]
I can confirm the above fix did not work for me either.

K8s: v1.24.17-eks-4f4795d
ArgoCD: v2.8.4+c279299

However, I was able to work around this issue by setting `.Values.installCRDs: false` in the `external-secrets` chart and explicitly installing the CRD bundle in a priority syncwave. For example, in my `application` spec: 

```
{{- if .Values.externalSecrets.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: external-secrets-crds
  namespace: argocd
spec:
  destination:
    namespace: {{ .Values.externalSecrets.namespace }}
    server: https://kubernetes.default.svc
  project: {{ .Values.project }}
  source:
    helm:
      values: ""
    path: deploy/crds
    repoURL: 'https://github.com/external-secrets/external-secrets'
    targetRevision: {{ .Values.externalSecrets.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: external-secrets
  namespace: argocd
spec:
  destination:
    namespace: {{ .Values.externalSecrets.namespace }}
    server: https://kubernetes.default.svc
  project: {{ .Values.project }}
  source:
    helm:
      values: |
{{ omit .Values.externalSecrets "namespace" | toYaml | indent 8 }}
    path: deploy/charts/external-secrets
    repoURL: 'https://github.com/external-secrets/external-secrets'
    targetRevision: {{ .Values.externalSecrets.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
```

**Comment by jsolana** [comment]
Hi, the same using:

- ArgoCD v2.10.1+a79e0ea
- K8s Server Version: v1.27.11-eks-b9c9ed7

I Tried using `IgnoreDifference` at SystemLevel using `ManagedFieldManagers` didn't work:

```yaml
resource.customizations.ignoreDifferences.ConfigMap: |
  managedFieldsManagers:
   - my-manager
```

But CM seems `OutOfSync`.

LiveManifest:

```yaml
apiVersion: v1
data:
  POKE_VARIABLE: whatever-value
  SERVER_VARIABLE: 'my-server.example.com'
kind: ConfigMap
metadata:
  creationTimestamp: '2024-04-16T08:31:31Z'
  labels:
    app: test-env-interpolator
    argocd.argoproj.io/instance: test-env-interpolator
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          'f:SERVER_VARIABLE': {}
      manager: my-manager
      operation: Update
      time: '2024-04-16T08:35:02Z'
  name: test-env-interpolator-cm
  namespace: test-env-interpolator
  resourceVersion: '37036218'
  uid: 5b549ab6-47cd-4635-89dd-c5c1485490c8
```

**Comment by shastaxc** [comment]
I'm having the same issue due to the Reloader application. It applies an env var to my deployment dynamically. It is listed as a manager in the managed fields section just for that one env var:
```
metadata:
  managedFields:
    - manager: Reloader
      operation: Update
      apiVersion: apps/v1
      time: '2024-09-11T21:02:50Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:template:
            f:spec:
              f:containers:
                k:{"name":"best-container"}:
                  f:env:
                    .: {}
                    k:{"name":"STAKATER_MY_COOL_CONFIGMAP"}:
                      .: {}
                      f:name: {}
                      f:value: {}
```

My argo spec includes:
```
spec:
  ignoreDifferences:
  - group: "*"
    kind: "*"
    managedFieldsManagers:
    - Reloader
```
But it is still showing a diff on this env var `STAKATER_MY_COOL_CONFIGMAP`.

I am using ArgoCD v2.11.4

**Comment by sabreensalama** [comment]
I have the same issue with argocd v2.8.4 and eks 1.30, it is out of sync due to the below item 
![image](https://github.com/user-attachments/assets/9218e598-8b3d-4b05-bfef-e5e140dfa5df)

**Comment by Sturgelose** [comment]
Also same issue in version 3.0.6 of Argocd in AKS and EKS 1.32.4.

I'm trying to ignore all the changes by background-controller (kyverno) and even with RespectIgnoreDifferences, seems to not to be honored.

I've tried with the following config at cluster and app level:
```
 ignoreDifferences:
  - group: '*'
    kind: '*'
    managedFieldsManagers:
      - background-controller
 ```

**Comment by efekete** [comment]
Also having same issue on 3.0.6 while trying to use replicator:

```
      ignoreDifferences:
        - group: '*'
          kind: '*'
          managedFieldsManagers:
            - replicator
```

**Comment by andrey-parkhomets** [comment]
For me works next:
```yaml
ignoreDifferences:
  - group: argoproj.io
    kind: Rollout
    jqPathExpressions: 
    - '.spec.template.spec.containers[].env[]?|select(.name | startswith("STAKATER") )'
```
ArgoCD Server v3.1.7+511ebd7
