### ISSUE TITLE
Argocd app diff failing with the URL scheme 'secrets' is not allowed

### ISSUE THREAD

**Issue by MeNsaaH** [argoproj/argo-cd#9200]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
I have configured my `helm.valuesFilesSchemes`. 
```yaml
    helm.valuesFileSchemes: http, https, secrets
```
However, when I run argocd app diff with the application that has a `secrets://values.yaml` valuesfile, it fails with the error `the URL scheme 'secrets' is not allowed`. The application works however, if deployed. But diff fails
**To Reproduce**

- configure `helm.valuesFilesSchemes` to allow secrets
- Create an argocd helm application that references a values file using `secrets://<values-file>`
- Run `argocd app diff <app-name> --local . --local-repo-root .`
**Expected behavior**

**Screenshots**

**Version**

```shell
argocd: v2.3.3+07ac038.dirty
  BuildDate: 2022-03-30T05:20:18Z
  GitCommit: 07ac038a8f97a93b401e824550f0505400a8c84e
  GitTreeState: dirty
  GoVersion: go1.18
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.3.3+07ac038
  BuildDate: 2022-03-30T00:06:18Z
  GitCommit: 07ac038a8f97a93b401e824550f0505400a8c84e
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.4.1 2021-11-11T23:36:27Z
  Helm Version: v3.8.0+gd141386
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by arthurk** [comment]
I have the same issue with Argo CD 2.4.3. We have helm-secrets installed and configured:

`helm.valuesFileSchemes: http, https, secrets`

Everything works fine when deploying/syncing applications, just the `argocd app diff` command fails with the `URL scheme 'secrets' is not allowed` error.

**Comment by arthurk** [comment]
Looking a bit more into this, it looks like when the `--local` flag is passed the settings are not read.

https://github.com/argoproj/argo-cd/blob/b52476971425d396cfd63306d53193a3e9f54df6/cmd/argocd/commands/app.go#L838
(It uses a `ClusterClient` instead of a `SettingsClient` for local diff)

**Comment by MeNsaaH** [comment]
@arthurk how are the two different? Maybe we could propose a merge request

**Comment by arthurk** [comment]
If I remember correctly the ClusterClient fetches the settings from the Cluster (the configmap) and the other one didn't.

With the recent merge of server-side-generate https://github.com/argoproj/argo-cd/issues/8145 this issue might be solved, need to try it out sometime

**Comment by MeNsaaH** [comment]
Wierd one that I've installed the latest release and the changes in the PR are not there 🤦🏿

**Comment by MeNsaaH** [comment]
Seems it'll be on version `2.5 RC`: https://github.com/argoproj/argo-cd/pull/10019#issuecomment-1249566344

**Comment by myrondev** [comment]
I still have this issue, is there any resolutions?

**Comment by MeNsaaH** [comment]
@myrondev you should be able to upgrade your argocd and use serverside diffs now

**Comment by myrondev** [comment]
> erside diffs now

What do yo mean? I just added to argo cm: helm.valuesFileSchemes: http, https, secrets. But still the same issue?

**Comment by myrondev** [comment]
> @myrondev you should be able to upgrade your argocd and use serverside diffs now

What do yo mean? I just added to argo cm: helm.valuesFileSchemes: http, https, secrets. But still the same issue?

**Comment by alexef** [comment]
@myrondev can you try with:

```argocd app diff <app-name> --local . --local-repo-root . --server-side-generate``` ?

**Comment by myrondev** [comment]
> @myrondev can you try with:
> 
> `argocd app diff <app-name> --local . --local-repo-root . --server-side-generate` ?

I can't use CLI. Can I change this in values.yaml for ArgoCD? Now my app-of-app looks this way: 

![argo33](https://user-images.githubusercontent.com/92361461/201909571-2d631408-cd8f-41be-9712-10159d43fa5b.png)

**Comment by alexef** [comment]
@myrondev what version of argocd does the UI report?

**Comment by myrondev** [comment]
> @myrondev what version of argocd does the UI report?

Argo CD
v2.2.5+8f981cc

**Comment by myrondev** [comment]
This command **argocd app diff <app-name> --local . --local-repo-root . --server-side-generate**  will not change anything, right? I mean in values.yaml file.

**Comment by alexef** [comment]
@myrondev the issue you are facing has been fixed in version 2.5, so you need to upgrade argocd, as you are running version 2.2

**Comment by myrondev** [comment]
> @myrondev the issue you are facing has been fixed in version 2.5, so you need to upgrade argocd, as you are running version 2.2

Hi, on 2.5.2 there is the same issue.

**Comment by obiesmans** [comment]
Hello, I have the same issue with and without the `--server-side` flag. Running 2.5.2 server and client.


```
argocd: v2.5.2+unknown
  BuildDate: 2022-11-09T22:25:07Z
  GitCommit: 
  GitTreeState: 
  GitTag: 2.5.2
  GoVersion: go1.19.3
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.5.2+148d8da
  BuildDate: 2022-11-07T16:42:47Z
  GitCommit: 148d8da7a996f6c9f4d102fdd8e688c2ff3fd8c7
  GitTreeState: clean
  GoVersion: go1.18.8
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.1+g9f88ccb
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.18.0

```

**Comment by myrondev** [comment]
Hi, I updated ArgoCD to 5.14.1 and added  **config:
    helm.valuesFileSchemes: http, https, secrets** and issue seems to be resolved.

**Comment by emmahsax** [comment]
This is what version I am using, and I am still getting the same error:
```json
{
    "Version": "v2.10.9+c071af8",
    "BuildDate": "2024-04-30T15:53:28Z",
    "GitCommit": "c071af808170bfc39cbdf6b9be4d0212dd66db0c",
    "GitTreeState": "clean",
    "GoVersion": "go1.21.3",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.2.1 2023-10-19T20:13:51Z",
    "HelmVersion": "v3.14.3+gf03cc04",
    "KubectlVersion": "v0.26.11",
    "JsonnetVersion": "v0.20.0"
}
```

Config: 
![image](https://github.com/argoproj/argo-cd/assets/7562793/66e4f6e1-c092-4d61-9822-3bccc79fbe51)

**Comment by fmeier-nera** [comment]
> Esta es la versión que estoy usando y sigo recibiendo el mismo error:
> 
> ```json
> {
>     "Version": "v2.10.9+c071af8",
>     "BuildDate": "2024-04-30T15:53:28Z",
>     "GitCommit": "c071af808170bfc39cbdf6b9be4d0212dd66db0c",
>     "GitTreeState": "clean",
>     "GoVersion": "go1.21.3",
>     "Compiler": "gc",
>     "Platform": "linux/amd64",
>     "KustomizeVersion": "v5.2.1 2023-10-19T20:13:51Z",
>     "HelmVersion": "v3.14.3+gf03cc04",
>     "KubectlVersion": "v0.26.11",
>     "JsonnetVersion": "v0.20.0"
> }
> ```
> 
> Configuración: ![imagen](https://private-user-images.githubusercontent.com/7562793/327521612-66e4f6e1-c092-4d61-9822-3bccc79fbe51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2OTUxMDEsIm5iZiI6MTcxNTY5NDgwMSwicGF0aCI6Ii83NTYyNzkzLzMyNzUyMTYxMi02NmU0ZjZlMS1jMDkyLTRkNjEtOTgyMi0zYmNjYzc5ZmJlNTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTRUMTM1MzIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmU0YjVhMjZmOWRkYTE3MWJiMWFlNDNiMzQ5YzNiNmMxMzYwYjdjMzcxNDEwOWE5NWE1MjYzNmIyYTMwMzUxNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.uLumuqUfvChbVzz8ZX2ROfnMIDjB_SINWD1iFSZ3Zvc)


Same problem with the same version
