### ISSUE TITLE
argocd application do not update when values file changed in helm repo.

### ISSUE THREAD

**Issue by hillbun** [argoproj/argo-cd#9214]
argocd v2.1.7

When I create application connect to helm repo, when values file in helm repo is changed, application do not update, even I click sync or refresh.

Application only changed when I click hard refresh.

How to solve it?

**Comment by dw-3** [comment]
我也遇到了此类问题，而且我还发现同一个版本的chart，比如增加了另外一个value文件values-poc.yaml，valueFiles为values-poc.yaml时，部署时会报错values-poc.yaml: no such file or directory

**Comment by dw-3** [comment]
I also encountered such problems, and I also found that the same version of the chart, such as adding another value file values-poc.yaml, when valueFiles is values-poc.yaml, will report an error values-poc.yaml during deployment: no such file or directory

**Comment by vvatlin** [comment]
Looks like I have the same issue 
my application.yaml looks like this:
```apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
spec:
  source:
    targetRevision: 1.13.3
    helm:
      values: |-
        global:
          hub: gcr.io/istio-release
          tag: 1.13.3
        meshConfig:
          accessLogFile: /dev/stdout
          ingressService: istio-ingress
          ingressSelector: ingress
```

When I change values for helm chart nothing happen, even if I do sync, I still have the same old ConfigMap for Istio.

**Comment by mbaldessari** [comment]
I have observed this as well. From my initial cursory testing it seems that a hard-refresh fixes things. E.g.:
```
argocd app get test --hard-refresh
```

**Comment by crenshaw-dev** [comment]
Does anyone have a public repo I can test against?

I just tried with 2.4.2, and changing `replicaCount` was reflected in the UI with a simple "Refresh." https://github.com/crenshaw-dev/argocd-example-apps/commits/values-change

(Aside @EnriqueHormilla I'd upgrade ASAP if your instance is anything other than a test instance, there are [11 CVEs](https://github.com/argoproj/argo-cd/security/advisories) against 2.0.5.)

**Comment by EnriqueHormilla** [comment]
Hi @crenshaw-dev thanks for the support. 
I know the change is reflected in the UI, but despite that, argoCD doesn't do anything with this change. In this picture, i have configured argo in my repo like that:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apache-custom
  namespace: argocd
spec:
  destination:
    namespace: apache-custom
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-stg.yaml
    path: path/apache-custom
    repoURL: git@github.com:privateRepo/repo.git
    targetRevision: test
```

In my values-stg.yaml I have replicaCount :6, but I have only one pod.
![image](https://user-images.githubusercontent.com/16726452/175895263-70a80463-78e4-4c60-a848-3d2cf0f3fa7d.png)

If I configured Argo directly to helm repo:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
  namespace: argocd
spec:
  project: default
  source:
    chart: apache
    helm:
      parameters:
        - name: replicaCount
          value: '6'
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 9.1.11        
  destination:
    server: https://kubernetes.default.svc
    namespace: apache-custom
  syncPolicy:
    automated: {}
```
Its work and the deployment increase the pods.
![image](https://user-images.githubusercontent.com/16726452/175897009-b2665757-ccf7-461b-b9df-d0dda1d53235.png)

**Comment by EnriqueHormilla** [comment]
Hi @crenshaw-dev  finally I did the workaround suggest for the community in https://github.com/argoproj/argo-cd/issues/2789#issuecomment-1167345080 .

**Comment by EnriqueHormilla** [comment]
> Ah, that use case will require #2789 to be resolved. There's currently a draft PR, and it's planned for 2.5 in August.

Thanks @crenshaw-dev , good news!

**Comment by hillbun** [comment]
@crenshaw-dev 

current release is v2.4.11, so this bug is not fixed yet?

**Comment by xgt001** [comment]
I am grateful to have found this thread as I was going a bit crazy thinking I am doing something somehow wrong. 😄 
Can confirm in our own setup that only values.yaml is read and it doesnt bother reading even from inline `values:` as such 


```
  source:
    repoURL: git@github.blah/helm.git
    path: kubernetes/helm/bootstrap
    helm:
      #the below values are merrily ignored
      values: |
        testFeature:
          enabled: true
          overlay: non-production
 ```

**Comment by maaft** [comment]
@xgt001  what exactly is in `application.yaml` in your case?

I've installed a helm chart from a public repository. Now I want to change `values.yaml` and expect that argocd re-deploys pods, which is not the case.

**Comment by duxing** [comment]
@crenshaw-dev I'm also running into this issue.

I'm running `argocd@v2.4.0+91aefab`
```
argocd: v2.4.0+91aefab
  BuildDate: 2022-06-10T17:23:37Z
  GitCommit: 91aefabc5b213a258ddcfe04b8e69bb4a2dd2566
  GitTreeState: clean
  GoVersion: go1.18.3
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.4.0+91aefab
  BuildDate: 2022-06-10T17:23:37Z
  GitCommit: 91aefabc5b213a258ddcfe04b8e69bb4a2dd2566
  GitTreeState: clean
  GoVersion: go1.18.3
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.4.1 2021-11-11T23:36:27Z
  Helm Version: v3.8.1+g5cb9af4
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0
``` 

and the application configuration yaml (`datadog` helm chart in this case):
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datadog
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: "default"
  source:
    repoURL: https://helm.datadoghq.com
    targetRevision: 3.1.3
    chart: datadog
    helm:
      values: |
        <content-of-my-values.yaml>
  destination:
    server: https://kubernetes.default.svc
    namespace: datadog
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
```


when I modified the content inside the `content-of-my-values.yaml` block (`.spec.source.helm.values`) the app is marked as "synced" but the last applied configuration does not pick up my changes.

I checked `argocd app get datadog -oyaml` and `.status.history[0]` has the correct timestamp (days after I pushed a removal-only configuration change) but `.status.history[0].source.helm.values` was still using the revision before the push. 

I noticed `repo-server` logs mentioning cache hit but I guess that's for the chart repo, which doesn't affect this. That lead me to believe the argocd server is responsible for the stale copy of the configuration.

**Comment by duxing** [comment]
the correct fix has been postponed to v2.6 ([reference](https://github.com/argoproj/argo-cd/issues/2789#issuecomment-1267242015))

an alternative solution: https://github.com/argoproj/argo-cd/issues/2789#issuecomment-1176820186

**Comment by emmercm** [comment]
I believe I'm still experiencing this issue with v2.6.3 using in-line Helm values similar to:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: <redacted>
  namespace: argo-cd-dev
spec:
  project: <redacted>
  source:
    repoURL: <redacted>
    targetRevision: <redacted>
    chart: <redacted>
    helm:
      values: |
        server:
          replicaCount: 0
        # Many more lines of deeply-nested YAML...

  destination:
    name: k8s-dev
    namespace: <redacted>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=background
```

Editing `spec.source.helm.values` in either Git (application is set to auto sync) or the Argo UI does not cause the replica count of my deployment to change. Initiating a forceful sync via the Argo UI afterward does cause the replica count to change.

**Comment by maaft** [comment]
@emmercm Until this is solved, here's what I did:
- create extra repo with your helm-chart
- if you have any 3rd party charts, use helm dependencies
- update `values.yaml` in that repository directly and argocd will correctly update deployements

**Comment by migueleliasweb** [comment]
I just wanted to leave an idea here as well. The company I work for, we were definitely stuck with this problem for a while now.

The way we we've fixed it was to completely ditch the native helm integration and create our own plugin (https://argo-cd.readthedocs.io/en/stable/operator-manual/config-management-plugins/). This plugin has some smarts around to fix some of the use cases we needed. E.g: Helm recursive dependencies, multi values files, multiple sources, mixed applications with Helm + Kustomize, etc.

I reckon if you're not afraid to write software, that is a much more complete solution instead of waiting for the open source to catch up and fix all your edge cases.

**Comment by Dreamystify** [comment]
Not sure if this is relevant to anyone but was the fix I had for my situation.
I created a sub chart that had prometheus as a dependency. I had a values file with the values from the prometheus chart with my sub chart. The values would never update, they would always have the prometheus defaults. I had configured the values file wrong for the dependency chart. the prometheus chart needs to have its values in the sub-chart values file formatted like so:
```
prometheus:
   <prometheus chart values>:
<another dependency chart>:
   <values>...
```
After that they updated as expected

**Comment by LukePavelka** [comment]
this is still problem :(

**Comment by simonloach** [comment]
Hitting this issue as well right now.

**Comment by galaxyware241** [comment]
same issue here for us too.

**Comment by crenshaw-dev** [comment]
For the life of me, I cannot reproduce this. When I change the values, I immediately see the app go out of sync.

https://github.com/argoproj/argo-cd/assets/350466/8338e124-d9c3-4dec-bf28-500eebe8e6fb

**Comment by dglumac-nex** [comment]
Here's another little use case to try and help diagnose this. I am experience this problem in ArgoCD 2.8.2, and in my case the values is updating a Job which has already completed. I tried various options like forcing a `Replace=true` on the sync-option annotations, I have even gone as far as naming the job with something from the values.yaml file.

Set-up:
- ArgoCD application monitors a path in another GitHub repository on the main branch
- The monitored path has a Helm chart with a single dependency and nothing else - in effect it just deploys that dependency
- Dependency chart has, among other things, a Job which changes the name based on a value in its values.yaml file
- I override the said value in the values.yaml file and push it to the main branch of the monitored GitHub repo
- ArgoCD is set up to auto sync with defaults (3 mins poll time etc)

What happens:
- ArgoCD eventually detects that there has been a change to the path of the monitored repository, it updates the commit reference and the comment in the Sync Status section - second from the left in the ribbon at the top
- The Last Sync section - the third form the left in the ribbon at the top - still shows the previous commit reference and the commit message
- Sync Status section shows Synced status (to the latest commit)
- Last Sync section shows Sync OK status (to the previous commit)

Now I click on the Sync button.

The Sync popup overlay shows all other resources in the Synchronize Resources section at the bottom *except* the Job which I am trying to update/replace.

I wonder if it has something to do with the fact that the Job has completed and is now no longer seen as "updateable".

But, when I then click on Synchronize (which I presume triggers a hard sync) the new commit is actually deployed, and the replacement job does appear and run.

I hope that helps.

**Comment by kvaps** [comment]
Hi all, I made another workaround for this:

```yaml
server:
  extraContainers:
  - name: argocd-hard-refresher
    image: bitnami/kubectl:1.26.9
    command:
    - /bin/sh
    - -c
    args:
      - |
        while kubectl annotate application.argoproj.io -A -l hard-refresh=true argocd.argoproj.io/refresh=hard; do
          sleep 30
        done
```

Now any app that has `hard-refresh=true` label with be hard refreshed for every 30 seconds

**Comment by yukccy** [comment]
> For the life of me, I cannot reproduce this. When I change the values, I immediately see the app go out of sync.
> 
>  Screen.Recording.2023-08-18.at.11.30.50.AM.mov 
> 
> Same when I use a Helm repo instead of a Helm chart hosted in git.
> 
>  Screen.Recording.2023-08-18.at.11.35.14.AM.mov

In my case, I got the problem in a combination of public Helm repo with a values.yaml from a private Git repo. it can do auto sync while newer chart version. But when I do a push to the values.yaml, it didn't catch this commit and do the auto sync. I have to do a hard refresh for the application.

I am using ArgoCD to deploy my GitLab Runner by following YAML.
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-runner
spec:
  destination:
    name: ''
    namespace: gitlab-runner
    server: 'https://kubernetes.default.svc'
  sources:
    - path: ''
      repoURL: 'https://charts.gitlab.io'
      targetRevision: 0.*
      chart: gitlab-runner
      helm:
        valueFiles:
          - $values/runner/values.yaml
    - repoURL: 'https://gitlab.example.com/example-proj/gitlab.git'
      targetRevision: main
      ref: values
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
```

As you modified the manifest section that directly passing new variable into the application, it should be another case.

**Comment by ionutz89** [comment]
Is it any update about this issue?

**Comment by mpycio** [comment]
really weird, we've been using argocd for almost a year with no sync issues, sometimes I had to use hard refresh. Today came across this issue, for no apparent reason it just won't recognise new image version I'm trying to push - UI shows all in sync and displays correct commit sha but uses old version.

**Comment by soony88** [comment]
I've also just suddenly started experiencing this issue today,

It was fine last week,
It was just as I went to demo Argo to my team when it started breaking, sorry all, looks like the Demo Gods have broken Argo for everybody.

**Comment by MinaMohammadi** [comment]
# What is my probem?
Greetings,

I'm currently facing an issue with my setup. I've installed Argo CD version `v2.9.1` along with Helm Chart version `5.51.4` on my cluster. Additionally, I've installed Argo CD Image Updater version `v0.12.2` with Helm Chart version `0.9.1` to manage the deployment of new program versions. My configuration  in Argo CD  Image Updater employs the `argocd method` for staging  and the `git-write-back method` for production.

## Application
This is my Application config file:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: 'cephs3sync={{ cephs3sync_image_url }}'
    argocd-image-updater.argoproj.io/cephs3sync.pull-secret: 'pullsecret:argocd/registry'
    argocd-image-updater.argoproj.io/cephs3sync.update-strategy: '{{ 'latest' if stagingcluster is defined and stagingcluster | default(false) else 'semver' }}'
    argocd-image-updater.argoproj.io/cephs3sync.force-update: 'true'
{% if not stagingcluster | default(false) %}
    argocd-image-updater.argoproj.io/cephs3sync.allow-tags: 'regexp:^[0-9]+(\.[0-9]+){0,2}$'
{% endif %}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: cephs3sync
  namespace: argocd
spec:
  project: default
  source:
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.repository
          value: '{{ cephs3sync_image_url }}'
        - name: image.tag
          value: '{{ cephs3sync_image_tag }}'
    repoURL: https://{{ git_url }}/iaas/cephs3sync.git
    path: charts
    targetRevision: '{{ 'dev' if stagingcluster is defined and stagingcluster | default(false) else 'main' }}'
  destination:
    server: https://kubernetes.default.svc
    namespace: interface
  syncPolicy:
{% if stagingcluster is defined and stagingcluster | default(false) %}
    automated:
      selfHeal: true
      prune: true
      allowEmpty: false
{% endif %}
    syncOptions:
      - CreateNamespace=true
      - Validate=true
      - PruneLast=true
      - PrunePropagationPolicy=foreground
      - Replace=true
      - ApplyOutOfSyncOnly=true

```

While the first method(argocd method) operates smoothly, I've encountered an issue with the second method(git-write-back method) where the program doesn't reflect any changes in the Argo CD UI. After thorough investigation, I reviewed the logs of all containers, and there were no apparent errors or problems.

## Argo CD Image Updater Logs

Furthermore, I've noted that there might be additional insights in the Argo CD Image Updater logs during the notice and redeployment of the new version of my app.

```
time="2023-12-05T14:52:28Z" level=info msg="Successfully updated image 'reg.arvan.com/interface/prod/cephs3sync:0.4.2' to 'reg.arvan.com/interface/prod/cephs3sync:0.4.3', but pending spec update (dry run=false)" alias=cephs3sync application=cephs3sync image_name=interface/prod/cephs3sync image_tag=0.4.2 registry=reg.arvan.com
time="2023-12-05T14:52:28Z" level=info msg="Committing 1 parameter update(s) for application cephs3sync" application=cephs3sync
time="2023-12-05T14:52:28Z" level=info msg="Initializing https://git.arvan.com/iaas/cephs3sync.git to /tmp/git-cephs3sync3949202410"
time="2023-12-05T14:52:28Z" level=info msg="rm -rf /tmp/git-cephs3sync3949202410" dir= execID=443e4
time="2023-12-05T14:52:28Z" level=info msg=Trace args="[rm -rf /tmp/git-cephs3sync3949202410]" dir= operation_name="exec rm" time_ms=1.803898
time="2023-12-05T14:52:28Z" level=info msg="git fetch origin --tags --force" dir=/tmp/git-cephs3sync3949202410 execID=12bd4
time="2023-12-05T14:52:29Z" level=info msg=Trace args="[git fetch origin --tags --force]" dir=/tmp/git-cephs3sync3949202410 operation_name="exec git" time_ms=1043.440004
time="2023-12-05T14:52:29Z" level=info msg="git config user.name argocd-image-updater" dir=/tmp/git-cephs3sync3949202410 execID=2adbf
time="2023-12-05T14:52:29Z" level=info msg=Trace args="[git config user.name argocd-image-updater]" dir=/tmp/git-cephs3sync3949202410 operation_name="exec git" time_ms=3.326561
time="2023-12-05T14:52:29Z" level=info msg="git config user.email noreply@argoproj.io" dir=/tmp/git-cephs3sync3949202410 execID=37e0b
time="2023-12-05T14:52:29Z" level=info msg=Trace args="[git config user.email noreply@argoproj.io]" dir=/tmp/git-cephs3sync3949202410 operation_name="exec git" time_ms=8.85276
time="2023-12-05T14:52:29Z" level=info msg="git checkout --force argocd" dir=/tmp/git-cephs3sync3949202410 execID=3bd3a
time="2023-12-05T14:52:29Z" level=info msg=Trace args="[git checkout --force argocd]" dir=/tmp/git-cephs3sync3949202410 operation_name="exec git" time_ms=30.662612999999997
time="2023-12-05T14:52:29Z" level=info msg="git clean -fdx" dir=/tmp/git-cephs3sync3949202410 execID=b80e3
time="2023-12-05T14:52:29Z" level=info msg=Trace args="[git clean -fdx]" dir=/tmp/git-cephs3sync3949202410 operation_name="exec git" time_ms=5.5891530000000005
time="2023-12-05T14:52:29Z" level=info msg="Successfully updated the live application spec" application=cephs3sync
time="2023-12-05T14:52:29Z" level=info msg="Processing results: applications=1 images_considered=1 images_skipped=0 images_updated=1 errors=0"
```

As you can see through the above logs, the Argo CD Image Updater appears to be working fine with no problems.

##  Argo CD UI

Additionally, in the photo below, you will notice that even in the Argo CD UI, the changes are displayed, indicating that the version of the program has transitioned from 0.4.2 to 0.4.3. However, despite this UI indication, the program is not deployed to the next version.

![image](https://github.com/argoproj/argo-cd/assets/99136795/6a343a76-7790-4788-96af-4ca43c82b5eb)

Does anyone have any insights or help for my problem?

**Comment by jrkarnes** [comment]
@crenshaw-dev I have replicated the problem with video but the video is too large to host on Github.com so [I have hosted it on Reddit instead](https://www.reddit.com/r/ArgoCD/comments/1afozd9/argocd_applicationset_not_updating_issue_9214/).

Please let me know if you need any further information.

**Comment by mxchinegod** [comment]
This is happening to me too, exactly as described here:
https://github.com/argoproj/argo-cd/issues/9214#issuecomment-1847177438

**Comment by lior-eng** [comment]
> # What is my probem?
> Greetings,
> 
> I'm currently facing an issue with my setup. I've installed Argo CD version `v2.9.1` along with Helm Chart version `5.51.4` on my cluster. Additionally, I've installed Argo CD Image Updater version `v0.12.2` with Helm Chart version `0.9.1` to manage the deployment of new program versions. My configuration in Argo CD Image Updater employs the `argocd method` for staging and the `git-write-back method` for production.
> 
> ## Application
> This is my Application config file:
> 
> ```
> apiVersion: argoproj.io/v1alpha1
> kind: Application
> metadata:
>   annotations:
>     argocd-image-updater.argoproj.io/image-list: 'cephs3sync={{ cephs3sync_image_url }}'
>     argocd-image-updater.argoproj.io/cephs3sync.pull-secret: 'pullsecret:argocd/registry'
>     argocd-image-updater.argoproj.io/cephs3sync.update-strategy: '{{ 'latest' if stagingcluster is defined and stagingcluster | default(false) else 'semver' }}'
>     argocd-image-updater.argoproj.io/cephs3sync.force-update: 'true'
> {% if not stagingcluster | default(false) %}
>     argocd-image-updater.argoproj.io/cephs3sync.allow-tags: 'regexp:^[0-9]+(\.[0-9]+){0,2}$'
> {% endif %}
>   finalizers:
>     - resources-finalizer.argocd.argoproj.io
>   name: cephs3sync
>   namespace: argocd
> spec:
>   project: default
>   source:
>     helm:
>       valueFiles:
>         - values.yaml
>       parameters:
>         - name: image.repository
>           value: '{{ cephs3sync_image_url }}'
>         - name: image.tag
>           value: '{{ cephs3sync_image_tag }}'
>     repoURL: https://{{ git_url }}/iaas/cephs3sync.git
>     path: charts
>     targetRevision: '{{ 'dev' if stagingcluster is defined and stagingcluster | default(false) else 'main' }}'
>   destination:
>     server: https://kubernetes.default.svc
>     namespace: interface
>   syncPolicy:
> {% if stagingcluster is defined and stagingcluster | default(false) %}
>     automated:
>       selfHeal: true
>       prune: true
>       allowEmpty: false
> {% endif %}
>     syncOptions:
>       - CreateNamespace=true
>       - Validate=true
>       - PruneLast=true
>       - PrunePropagationPolicy=foreground
>       - Replace=true
>       - ApplyOutOfSyncOnly=true
> ```
> 
> While the first method(argocd method) operates smoothly, I've encountered an issue with the second method(git-write-back method) where the program doesn't reflect any changes in the Argo CD UI. After thorough investigation, I reviewed the logs of all containers, and there were no apparent errors or problems.
> 
> ## Argo CD Image Updater Logs
> Furthermore, I've noted that there might be additional insights in the Argo CD Image Updater logs during the notice and redeployment of the new version of my app.
> 
> ```
> time="2023-12-05T14:52:28Z" level=info msg="Successfully updated image 'reg.arr.com/interface/prod/cephs3sync:0.4.2' to 'reg.arr.com/interface/prod/cephs3sync:0.4.3', but pending spec update (dry run=false)" alias=cephs3sync application=cephs3sync image_name=interface/prod/cephs3sync image_tag=0.4.2 registry=reg.arr.com
> time="2023-12-05T14:52:28Z" level=info msg="Committing 1 parameter update(s) for application cephs3sync" application=cephs3sync
> time="2023-12-05T14:52:28Z" level=info msg="Initializing https://git.arr.com/iaas/cephs3sync.git to /tmp/git-cephs3sync3949202410"
> time="2023-12-05T14:52:28Z" level=info msg="rm -rf /tmp/git-cephs3sync3949202410" dir= execID=443e4
> time="2023-12-05T14:52:28Z" level=info msg=Trace args="[rm -rf /tmp/git-cephs3sync3949202410]" dir= operation_name="exec rm" time_ms=1.803898
> time="2023-12-05T14:52:28Z" level=info msg="git fetch origin --tags --force" dir=/tmp/git-cephs3sync3949202410 execID=12bd4
> time="2023-12-05T14:52:29Z" level=info msg=Trace args="[git fetch origin --tags --force]" dir=/tmp/git-cephs3sync3949202410 operation_name="exec git" time_ms=1043.440004
> time="2023-12-05T14:52:29Z" level=info msg="git config user.name argocd-image-updater" dir=/tmp/git-cephs3sync3949202410 execID=2adbf
> time="2023-12-05T14:52:29Z" level=info msg=Trace args="[git config user.name argocd-image-updater]" dir=/tmp/git-cephs3sync3949202410 operation_name="exec git" time_ms=3.326561
> time="2023-12-05T14:52:29Z" level=info msg="git config user.email noreply@argoproj.io" dir=/tmp/git-cephs3sync3949202410 execID=37e0b
> time="2023-12-05T14:52:29Z" level=info msg=Trace args="[git config user.email noreply@argoproj.io]" dir=/tmp/git-cephs3sync3949202410 operation_name="exec git" time_ms=8.85276
> time="2023-12-05T14:52:29Z" level=info msg="git checkout --force argocd" dir=/tmp/git-cephs3sync3949202410 execID=3bd3a
> time="2023-12-05T14:52:29Z" level=info msg=Trace args="[git checkout --force argocd]" dir=/tmp/git-cephs3sync3949202410 operation_name="exec git" time_ms=30.662612999999997
> time="2023-12-05T14:52:29Z" level=info msg="git clean -fdx" dir=/tmp/git-cephs3sync3949202410 execID=b80e3
> time="2023-12-05T14:52:29Z" level=info msg=Trace args="[git clean -fdx]" dir=/tmp/git-cephs3sync3949202410 operation_name="exec git" time_ms=5.5891530000000005
> time="2023-12-05T14:52:29Z" level=info msg="Successfully updated the live application spec" application=cephs3sync
> time="2023-12-05T14:52:29Z" level=info msg="Processing results: applications=1 images_considered=1 images_skipped=0 images_updated=1 errors=0"
> ```
> 
> As you can see through the above logs, the Argo CD Image Updater appears to be working fine with no problems.
> 
> ## Argo CD UI
> Additionally, in the photo below, you will notice that even in the Argo CD UI, the changes are displayed, indicating that the version of the program has transitioned from 0.4.2 to 0.4.3. However, despite this UI indication, the program is not deployed to the next version.
> 
> ![image](https://private-user-images.githubusercontent.com/99136795/290104674-6a343a76-7790-4788-96af-4ca43c82b5eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMjkxNTcsIm5iZiI6MTcxMTAyODg1NywicGF0aCI6Ii85OTEzNjc5NS8yOTAxMDQ2NzQtNmEzNDNhNzYtNzc5MC00Nzg4LTk2YWYtNGNhNDNjODJiNWViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDEzNDczN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3ZDgxOTU1ZGI4MjY4ZDY4MjNmNmQwOTA5MzJlZDk1ZTYwYmZhMTMxM2U5NWQ4OTI2ODM1NDk2MDRkZTNkZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Sc9vnxJcic_o8Yxv_mLdqnUSfRQi3hLhX8gjozrKWIs)
> 
> Does anyone have any insights or help for my problem?

The logs look good.
I fixed it by adding another annotation. (I used it with helm).
here is the documentation I added the image-name and image-tag.
https://argocd-image-updater.readthedocs.io/en/stable/configuration/images/#specifying-helm-parameter-names

**Comment by jinleileiking** [comment]
same

**Comment by archae0pteryx** [comment]
Interesting 2 year long thread... I initially was doing the wrapped chart approach and thought it felt a little "hacky". now i too have the same issue.

**Comment by kubeden** [comment]
Long thread... I thought I was doing something wrong (or going crazy).

**I noticed if I rename the values file referenced, it is being reflected by ArgoCD.**

My workaround was to create a pipeline (azdo) to change the values file name but quickly found out this is not a feasible solution as my GIT history is becoming rather long... and the pipeline is taking a lot of time too.. so not good for development.

Following the thread, interested in a long-term fix.

**Comment by MauroSoli** [comment]
> I haven't experienced this issue on Argo, but from the initial description it sounds like behavior related to the helm flags `--reset-values` and `--reuse-values` which are slightly whacky, see: [helm/helm#8085](https://github.com/helm/helm/issues/8085)


Do you know how we can use them using the [Helm Declarative way](https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#declarative) ?

**Comment by Glaaj** [comment]
I'm currently experiencing this on a fresh cluster, I too was questioning my existence for a moment until I ran into this thread.

Is there a workaround or temporary fix for this?

**Comment by cabdominguesdc** [comment]
Hi. I had similar problem, but then i realized that I had some override values in argocd parameters.

**Comment by davidt-gh** [comment]
Hard refresh helped me in here. but still this is a big issue.

**Comment by eyearian** [comment]
I'm also seeing this on applications that are pulling a helm chart and setting some `valuesObject`.  In this instance i'm updating a value for the aws-load-balancer-controller.  If I update a helm parameter in the `valuesObject` section and merge that change (with autosync turned on) nothing happens.  The only way to get around this is to apply that application.yaml to the cluster or do a hard refresh.

**Comment by imuneeeb** [comment]
same problem

**Comment by eyearian** [comment]
> For the life of me, I cannot reproduce this. When I change the values, I immediately see the app go out of sync.
> 
>  Screen.Recording.2023-08-18.at.11.30.50.AM.mov 
> Same when I use a Helm repo instead of a Helm chart hosted in git.
> 
>  Screen.Recording.2023-08-18.at.11.35.14.AM.mov

Hi @crenshaw-dev you may not be able to reproduce this because i've noticed that changing replicas when pulling externally hosted helm charts actually works without issue.  I think you should try to update the `targetRevision` - I find that this consistently shows the issue.  We pull most of the applications that live in kube-system via helm charts - autoscaler, vpc-cni, load-balancer-controller etc.  I'm currently running into this issue with the cluster autoscaler.  Here is my setup:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-cluster-autoscaler
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://cluster-id.us-east-1.eks.amazonaws.com/
  project: aws-test-k8s-use1
  source:
    repoURL: https://kubernetes.github.io/autoscaler
    chart: cluster-autoscaler
    targetRevision: 9.37.0
    helm:
      releaseName: cluster-autoscaler
      valuesObject:
        <values>
   syncPolicy:
     automated: {}
     ```
     
I was running `targetRevision` 9.35.0, and updated the autoscaler to run 9.37.0.  With autosync turned on, I merge my change and the application says healthy and in-sync - yet the update to 9.37 never happens.  The controller logs report that the app is in sync, and there are no updates required.  If I initiate a hard-refresh, ArgoCD realizes it's out of sync and updates the app to the new target revision.

I know my autosync policy is working - another example to illustrate, we are pulling the vpc-cni helm chart to run the cni in our eks clusters.  The helm chart deploys the cni into our clusters main subnet.  For various reasons, we have a secondary subnet and are using raw manifests to deploy the cni daemonset to our secondary pod subnet.  This is set up as a multi-source application.  Subnet 1 gets the helm chart daemonset, subnet 2 gets the raw manifest cni daemonset.  Both running the same image version. When container image is updated, we update the `targetRevision` as well as the secondary daemonset manifest.  When merging a version update with autosync turned on, ArgoCD updates our secondary subnet container image, but the main subnet image doesn't autosync, and the application states that it's healthy and in-sync, and controller logs say no sync is required.  Once a hard-refresh is initiated, the helm chart portion of the cni receives the new version.

This indicates to me that while autosync is working, the way raw manifests and externally pulled helm charts are synced/diffed are being handled differently.  Hope this helps!

**Comment by IvanJosipovic** [comment]
Any updates on this?

**Comment by reggie-k** [comment]
As there was no success on reproducing the issue on the maintainers side, it would be super helpful for us to receive the following info from anyone still experiencing this with **Argo CD version >= 2.13** so that we can make progress with this issue:
- Application manifest with the problematic behavior that uses a **public** Helm chart
- Above application manifest before and after the change 
- `values.yaml` in Git, if it exists, before and after the change with the problematic behavior
- `argocd-cm ` config map manifest
- `argocd-cmd-params-cm `
- Output of `argocd version`
- Logs of `application-controller` and `repo-server` with a timestamp of the change in `values` file
- Short explanation of your scenario

**Comment by reggie-k** [comment]
Closing as no additional input received on this during the last month, the above comment includes additional info request if the issue reoccurs.
